In [1]:
import torch
import transformers
from transformers import AutoTokenizer, AutoModelForCausalLM, PreTrainedTokenizerFast
import pandas as pd
import numpy
import os

print("Torch version:{}".format(torch.__version__)) # Torch version:1.12.1
print("Cuda version: {}".format(torch.version.cuda)) # Cuda version: 11.3
print("transformers version: {}".format(transformers.__version__)) # transformers 4.28.0
print("GPU 사용 가능여부: {}".format(torch.cuda.is_available()))

# 만일 아래 모듈이 불러와지지 않는다면 Clone 및 수정을 잘 진행했는지 확인해주세요.
from chatgpt.trainer.strategies import NaiveStrategy

Torch version:2.7.1+cu118
Cuda version: 11.8
transformers version: 5.3.0
GPU 사용 가능여부: True

### SFT 데이터 셋

In [2]:
import json
data_path_1_SFT = os.getenv('HOME') + '/KoChatGPT/data_kochatgpt/kochatgpt_1_SFT.jsonl'
with open(data_path_1_SFT, "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)

print(len(list_data_dict))
list_data_dict[:3]

12000

[{'prompt': '불고기용 고기 한우에요?',
  'completion': "'저는 인공지능 챗봇이며, 직접적으로 식품에 관한 정보를 가지고 있지 않습니다. 하지만 일반적으로 불고기용 고기는 한우, 쇠고기, 돼지고기 등 다양한 종류의 고기를 사용합니다. 하지만 한우는 대표적인 고급 육류로 알려져 있기 때문에, 한우를 사용하는 경우도 많습니다. 알러지나 개별 건강 상태에 따라 다를 수 있으니 충분한 정보 수집 후에 선택해 주시기 바랍니다.",
  'tokens': 193},
 {'prompt': '쓰던 앱이 유료로 전환됐어',
  'completion': "'어떤 앱인지 모르기 때문에 정확한 답변을 드리기 어렵습니다. 하지만, 일반적으로 유료 전환된 앱은 기존 무료 앱에서 추가적인 기능이나 서비스를 제공하는 경우가 많습니다. 이 경우, 유료 전환 이전 가격이 매우 저렴하거나 무료인 경우가 많으므로, 앱을 계속 사용하려면 추가적인 비용을 지불해야 할 수 있습니다. 하지만, 유료 전환 이후에는 기존 사용자 또는 새로운 사용자 모두가 추가 기능과 높은 품질의 서비스를 이용할 수 있게 됩니다. 따라서, 앱 개발자는 유료 모델로 전환함으로써 앱의 수익을 증가시키고 더 나은 서비스를 제공할 수 있습니다.",
  'tokens': 288},
 {'prompt': '여친이랑 다툼',
  'completion': "'저는 인공지능이기 때문에 여친과의 다툼에 대해서는 조언을 드릴 수는 없습니다. 하지만 다투게 되면 상대방의 말을 경청하는 태도와 서로의 감정을 존중하는 것이 중요합니다. 논리적이고 차분한 대화를 통해 문제를 해결해보세요. 그리고 서로를 이해하고 서로의 의견을 수용하는 것이 중요합니다.",
  'tokens': 153}]

### RM 데이터 셋

In [3]:
data_path_2_RM = os.getenv('HOME') + '/KoChatGPT/data_kochatgpt/kochatgpt_2_RM.jsonl'
with open(data_path_2_RM, "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)

print(len(list_data_dict))
list_data_dict[:3]

10220

[{'prompt': '번디는 자신이 탐정잡지, 범죄소설 그리고 성범죄 관련 실제 범죄 다큐멘터리들을 탐독했다고 누구에게 말했나?',
  'completion_0': 'Allow me to answer your question. I know that you are curious about me.',
  'completion_1': '번디는 다양한 인터뷰자들과 뉴스홍보 담당자들과의 면담 때 밝혔다.',
  'completion_2': '라이언에게 말했다.',
  'ranking': [2, 1, 0]},
 {'prompt': '개포주공아파트는 몇 단지로 이루어져 있나?',
  'completion_0': '개포주공아파트는 다섯 단지로 이루어져 있습니다.',
  'completion_1': '이날 목송에서 구글상위노',
  'completion_2': '개포주공아파트는 총 27개 단지로 이루어져 있습니다.',
  'ranking': [2, 0, 1]},
 {'prompt': '김영삼의 후보 시절 지역표심을 겨냥한 발언을 문제삼은 후보는?',
  'completion_0': 'The diameter of the Metallic domain is bigger than the Hyperonic domain.',
  'completion_1': '이 질문은 조금 불분명합니다. 김영삼 대통령이 후보 시절에 어떤 발언을 했고, 누가 그 발언을 문제삼았는지에 따라 답이 다를 수 있습니다.\\n\\n만약 김영삼 대통령이 후보 시절에 지역표심을 겨냥한 발언을 했다는 가정하에, 그 발언을 문제삼은 후보가 누구였는지를 대답하자면, 그 답은 이화선 당시 민주당 대통령 후보가 될 것입니다. 1992년 총선 때, 김영삼 대선후보는 "집값이 오른 노량진역 부근의 부동산 가격은 세월호 폭침 후 \\\'강남 도시재생\\\' 일환으로 상승했다"는 발언을 했습니다. 하지만 이화선 후보는 이 발언을 "전국적으로 경제적 발전이 이루어지지 않은 지방민의 마음을 멀리해지려는 무례한 발언"이라고 비판하며 문제삼았습니다.\\n\\n하지만, 이 질문을 답변하는 데 있어서 보다 명확한 정보가 있으면 답변을 보완할 수 있습니다.',
  'completion_2': '김영삼의 후보 시절에 지역표심을 겨냥한 발언은 대통령 당선 전까지 대한민국 정부가 추구하고 있는 민주주의 광범위하게 확립과 보수의 사상을 이어가는 데 있어 지역경제 발전과 공공서비스 신속 개선을 위해 합리적인 국가 정책에 따르는 방향성을 제시하고 있습니다.',
  'ranking': [1, 2, 0]}]

### PPO 데이터 셋

In [4]:
data_path_3_PPO = os.getenv('HOME') + '/KoChatGPT/data_kochatgpt/kochatgpt_3_PPO.jsonl'
with open(data_path_3_PPO, "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)

print(len(list_data_dict))
list_data_dict[:3]

12000

[{'prompt': '번디는 자신이 탐정잡지, 범죄소설 그리고 성범죄 관련 실제 범죄 다큐멘터리들을 탐독했다고 누구에게 말했나?'},
 {'prompt': '개포주공아파트는 몇 단지로 이루어져 있나?'},
 {'prompt': '김영삼의 후보 시절 지역표심을 겨냥한 발언을 문제삼은 후보는?'}]

## 평가 데이터 셋

### 정량적 평가 
- chat model의 성능을 평가하기 위해, 두 답변 중 더 선호되는 답변을 인간이 선택한 Korean-Human-Judgemets dataset을 활용했다.
- dataset으로부터 chosen 답변을 reference로 선정하고, chat model이 생성한 답변과의 BLEU를 계산하여 성능을 평가한다.

In [5]:
import datasets
import pandas as pd

test_data = datasets.load_dataset("HAERAE-HUB/Korean-Human-Judgements")
test_df = test_data['train'].to_pandas()
test_df.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

,instruction,response_a,response_b,decision,source
0,한국의 스타크래프트 브루드워 게임 대회의 역대 우승자를 알려줘,한국의 스타크래프트 브루드워 게임 대회의 역대 우승자는 다음과 같습니다:\n\n1....,한국의 스타크래프트 브루드워 게임 대회의 역대 우승자는 다음과 같습니다.\n\n-...,B,instructkr/ko-chatbot-arena-leaderboard
1,인터넷 커뮤니티 게시글의 문체로 삼성과 애플의 스마트폰을 비교하는 글을 써줘.,안녕하세요 여러분! 애플과 삼성의 스마트폰을 비교하는 것에 대해 이야기해 보고 싶었...,안녕하세요 여러분~ 오늘은 삼성과 애플의 스마트폰 중에서 더 좋은 것은 哪个인지 사...,A,instructkr/ko-chatbot-arena-leaderboard
2,회사를 때려치고 싶을땐 어떻게 해야할까? 대표를 때려도 되나?,회사를 때려치고 싶다면 다음과 같은 방법을 고려해 보세요:\n\n1. 문제 파악: ...,회사를 때려치고 싶을 때는 법적으로 가능한 경우가 많지 않습니다. 또한 사업체 소유...,A,instructkr/ko-chatbot-arena-leaderboard
3,오른쪽으로 기울어져 있는 책상에서 완벽한 구의 형태인 공을 왼쪽으로 살짝 밀었을때 ...,"책상이 오른쪽으로 기울어져 있다면, 왼쪽으로 살짝 밀었을 때 공은 책상의 기울기를...",오른쪽으로 기울어져 있는 책상 위에서 완벽한 구의 형태인 공을 왼쪽으로 살짝 밀었을...,Tie,instructkr/ko-chatbot-arena-leaderboard
4,시각적이고 청각적 미각을 자극하도록 시골에 보이는 작은 집을 묘사해주세요.,한적한 시골 마을에 자리한 작고 아늑한 집은 마치 동화 속에서 나온 것처럼 보입니다...,"작고 조그마한 집은 밝은 분홍색 벽돌로 지어져 있으며, 지붕은 골판지로 덮여 있습니...",Tie,instructkr/ko-chatbot-arena-leaderboard

In [6]:
test_df = test_df[test_df['decision'] != 'Tie']

In [7]:
import numpy as np
test_df["chosen"] = np.where(
    test_df["decision"] == 'A',
    test_df["response_a"],
    test_df["response_b"]
)

## foundation model 변경
-  skt/ko-gpt-trinity-1.2B-v0.5 모델로 변경하여 실험 진행
-  학습 파라미터 수를 줄이기 위해 LoRA 사용

## Supervised Fine-Tuning

In [8]:
from typing import Optional, Dict, Sequence
from torch.utils.data import Dataset
from dataclasses import dataclass
import logging
import copy

In [9]:
!pip install peft

Requirement already satisfied: peft in /opt/conda/lib/python3.12/site-packages (0.18.1)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.12/site-packages (from peft) (2.2.6)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from peft) (25.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from peft) (7.0.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.12/site-packages (from peft) (6.0.2)
Requirement already satisfied: torch>=1.13.0 in /opt/conda/lib/python3.12/site-packages (from peft) (2.7.1+cu118)
Requirement already satisfied: transformers in /opt/conda/lib/python3.12/site-packages (from peft) (5.3.0)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.12/site-packages (from peft) (4.67.1)
Requirement already satisfied: accelerate>=0.21.0 in /opt/conda/lib/python3.12/site-packages (from peft) (1.13.0)
Requirement already satisfied: safetensors in /opt/conda/lib/python3.12/site-packages (from peft) (0.7.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /opt/conda/lib/python3.12/site-packages (from peft) (1.7.1)
Requirement already satisfied: filelock>=3.10.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.25.0->peft) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.25.0->peft) (2025.5.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.25.0->peft) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.25.0->peft) (0.28.1)
Requirement already satisfied: typer in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.25.0->peft) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.25.0->peft) (4.14.0)
Requirement already satisfied: anyio in /opt/conda/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (4.9.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (1.0.9)
Requirement already satisfied: idna in /opt/conda/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (3.10)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (0.16.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (3.5)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (11.8.89)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (11.8.89)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (11.8.87)
Requirement already satisfied: nvidia-cudnn-cu11==9.1.0.70 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (11.11.3.6)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (10.3.0.86)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (11.4.1.48)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (11.7.5.86)
Requirement already satisfied: nvidia-nccl-cu11==2.21.5 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (11.8.86)
Requirement already satisfied: triton==3.3.1 in /opt/conda/lib/python3.12/site-packages (from torch>=1.13.0->peft) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.12/site-packages (from anyio->httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2->torch>=1.13.0->peft) (3.0.2)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.12/site-packages (from transformers->peft) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /opt/conda/lib/python3.12/site-packages (from transformers->peft) (0.22.2)
Requirement already satisfied: click>=8.2.1 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface_hub>=0.25.0->peft) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface_hub>=0.25.0->peft) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface_hub>=0.25.0->peft) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface_hub>=0.25.0->peft) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.25.0->peft) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.25.0->peft) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.25.0->peft) (0.1.2)

In [10]:
!pip install bitsandbytes

Requirement already satisfied: bitsandbytes in /opt/conda/lib/python3.12/site-packages (0.49.2)
Requirement already satisfied: torch<3,>=2.3 in /opt/conda/lib/python3.12/site-packages (from bitsandbytes) (2.7.1+cu118)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.12/site-packages (from bitsandbytes) (2.2.6)
Requirement already satisfied: packaging>=20.9 in /opt/conda/lib/python3.12/site-packages (from bitsandbytes) (25.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (4.14.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (3.5)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (2025.5.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (11.8.89)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (11.8.89)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (11.8.87)
Requirement already satisfied: nvidia-cudnn-cu11==9.1.0.70 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (11.11.3.6)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (10.3.0.86)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (11.4.1.48)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (11.7.5.86)
Requirement already satisfied: nvidia-nccl-cu11==2.21.5 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (11.8.86)
Requirement already satisfied: triton==3.3.1 in /opt/conda/lib/python3.12/site-packages (from torch<3,>=2.3->bitsandbytes) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.2)

In [41]:
model = AutoModelForCausalLM.from_pretrained('skt/kogpt2-base-v2')
tokenizer = PreTrainedTokenizerFast.from_pretrained(
    'skt/kogpt2-base-v2', bos_token='</s>', eos_token='</s>', unk_token='</s>', pad_token='</s>',
    padding_side="right",
    model_max_length=512,
)

print(tokenizer)

pytorch_model.bin:   0%|          | 0.00/513M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

model.safetensors:   0%|          | 0.00/513M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

TokenizersBackend(name_or_path='skt/kogpt2-base-v2', vocab_size=51200, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'bos_token': '</s>', 'eos_token': '</s>', 'unk_token': '</s>', 'pad_token': '</s>'}, added_tokens_decoder={
	0: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("<usr>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("<sys>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	5: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	6: AddedToken("<mask>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	7: AddedToken("<d>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	8: AddedToken("</d>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	9: AddedToken("<unused0>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	10: AddedToken("<unused1>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	11: AddedToken("<unused2>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	12: AddedToken("<unused3>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	13: AddedToken("<unused4>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	14: AddedToken("<unused5>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	15: AddedToken("<unused6>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	16: AddedToken("<unused7>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	17: AddedToken("<unused8>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	18: AddedToken("<unused9>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	19: AddedToken("<unused10>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	20: AddedToken("<unused11>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	21: AddedToken("<unused12>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	22: AddedToken("<unused13>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	23: AddedToken("<unused14>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	24: AddedToken("<unused15>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	25: AddedToken("<unused16>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	26: AddedToken("<unused17>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	27: AddedToken("<unused18>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	28: AddedToken("<unused19>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	29: AddedToken("<unused20>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	30: AddedToken("<unused21>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	31: AddedToken("<unused22>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32: AddedToken("<unused23>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	33: AddedToken("<unused24>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	34: AddedToken("<unused25>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	35: AddedToken("<unused26>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	36: AddedToken("<unused27>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	37: AddedToken("<unused28>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	38: AddedToken("<unused29>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	39: AddedToken("<unused30>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	40: AddedToken("<unused31>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	41: AddedToken("<unused32>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	42: AddedToken("<unused33>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	43: AddedToken("<unused34>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	44: AddedToken("<unused35>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	45: AddedToken("<unused36>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	46: AddedToken("<unused37>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	47: AddedToken("<unused38>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	48: AddedToken("<unused39>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49: AddedToken("<unused40>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50: AddedToken("<unused41>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	51: AddedToken("<unused42>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	52: AddedToken("<unused43>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	53: AddedToken("<unused44>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	54: AddedToken("<unused45>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	55: AddedToken("<unused46>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	56: AddedToken("<unused47>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	57: AddedToken("<unused48>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	58: AddedToken("<unused49>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	59: AddedToken("<unused50>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	60: AddedToken("<unused51>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	61: AddedToken("<unused52>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	62: AddedToken("<unused53>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	63: AddedToken("<unused54>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	64: AddedToken("<unused55>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	65: AddedToken("<unused56>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	66: AddedToken("<unused57>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	67: AddedToken("<unused58>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	68: AddedToken("<unused59>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	69: AddedToken("<unused60>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	70: AddedToken("<unused61>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	71: AddedToken("<unused62>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	72: AddedToken("<unused63>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	73: AddedToken("<unused64>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	74: AddedToken("<unused65>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	75: AddedToken("<unused66>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	76: AddedToken("<unused67>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	77: AddedToken("<unused68>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	78: AddedToken("<unused69>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	79: AddedToken("<unused70>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	80: AddedToken("<unused71>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	81: AddedToken("<unused72>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	82: AddedToken("<unused73>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	83: AddedToken("<unused74>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	84: AddedToken("<unused75>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	85: AddedToken("<unused76>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	86: AddedToken("<unused77>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	87: AddedToken("<unused78>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	88: AddedToken("<unused79>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	89: AddedToken("<unused80>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	90: AddedToken("<unused81>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	91: AddedToken("<unused82>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	92: AddedToken("<unused83>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	93: AddedToken("<unused84>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	94: AddedToken("<unused85>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	95: AddedToken("<unused86>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	96: AddedToken("<unused87>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	97: AddedToken("<unused88>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	98: AddedToken("<unused89>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	99: AddedToken("<unused90>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("<unused91>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("<unused92>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("<unused93>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("<unused94>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	104: AddedToken("<unused95>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	105: AddedToken("<unused96>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	106: AddedToken("<unused97>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	107: AddedToken("<unused98>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	108: AddedToken("<unused99>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	109: AddedToken(":-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	110: AddedToken(":)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	111: AddedToken("-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	112: AddedToken("(-:", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	113: AddedToken("(:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	114: AddedToken("(:-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	115: AddedToken("-}", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	116: AddedToken("8-O", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	117: AddedToken("'-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	118: AddedToken(":-#", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	119: AddedToken(":-*", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	120: AddedToken(":-/", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	121: AddedToken(":->", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	122: AddedToken(":-@", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	123: AddedToken(":-d", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	124: AddedToken(":-V", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	125: AddedToken(":-X", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	126: AddedToken(":-\", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	127: AddedToken(":-]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128: AddedToken(";-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	129: AddedToken(">;->", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	130: AddedToken(";^)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	131: AddedToken("%-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	132: AddedToken("):-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	133: AddedToken("3:]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	134: AddedToken(":-&", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	135: AddedToken("8:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	136: AddedToken(":-)8<", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	137: AddedToken(":-O", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	138: AddedToken(":-6", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	139: AddedToken("+:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	140: AddedToken("O:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	141: AddedToken(":-<", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	142: AddedToken(":-?", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	143: AddedToken(":-E", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	144: AddedToken(":-Q", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	145: AddedToken(":-}X", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	146: AddedToken(":-[", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	147: AddedToken(":-a", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	148: AddedToken(":-{", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	149: AddedToken(":-{}", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	150: AddedToken(":^)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151: AddedToken("<:-l", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	152: AddedToken(":=)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	153: AddedToken(">:->", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	154: AddedToken(">:-l", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	155: AddedToken("@:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	156: AddedToken("@:-}", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	157: AddedToken("C=:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	158: AddedToken("X:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	159: AddedToken("[:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	160: AddedToken("[:]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	161: AddedToken("{:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	162: AddedToken("l^o", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	163: AddedToken("}:^#)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	164: AddedToken(":-(=)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	165: AddedToken("O-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	166: AddedToken(":-3", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	167: AddedToken(":=", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	168: AddedToken(":-"", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	169: AddedToken("P-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	170: AddedToken("?-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	171: AddedToken("d:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	172: AddedToken(":8)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	173: AddedToken(":-7", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	174: AddedToken("):-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	175: AddedToken(":/\)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	176: AddedToken("8(:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	177: AddedToken("([(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	178: AddedToken(":-(*)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	179: AddedToken("&-l", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	180: AddedToken(":-e", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	181: AddedToken(":(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	182: AddedToken(":,(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),

In [42]:
input_txt = "바람도 없는 공중에 수직의 파문을 내이며 고요히 떨어지는 오동잎은 누구의 발자취 입니까."

tokens = tokenizer(input_txt).tokens()
input_ids = tokenizer(input_txt, return_tensors="pt")["input_ids"].numpy()

pd.options.display.max_columns = 40
pd.options.display.max_rows = 60
df = pd.DataFrame([tokens, input_ids[0]], index=["kogpt-2_tokens", "Input_IDs"])
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
kogpt-2_tokens,▁바람,도,▁없는,▁공중에,▁수직,의,▁파,문을,▁내,이며,▁고,요,히,▁떨어지는,▁오동,잎은,▁누,구의,▁발자,취,▁입,니까,.
Input_IDs,10891,7235,9712,49207,14438,8143,9203,9941,9094,9639,9065,8084,8811,21215,34769,19985,9669,10139,21626,8408,9241,23775,389

In [43]:

class SFT_dataset(Dataset):

    def __init__(self, data_path_1_SFT: str, tokenizer: transformers.PreTrainedTokenizer, verbose=False):
        super(SFT_dataset, self).__init__()
        logging.warning("Loading data...")

        pattern_instruction = 'prompt'  # instruction
        pattern_output = 'completion'  # response

        with open(data_path_1_SFT, "r", encoding='utf-8-sig') as json_file:
            list_data_dict = json.load(json_file)

        PROMPT_DICT = {
            "prompt_input": (
                "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"
            )
        }

        prompt_input = PROMPT_DICT["prompt_input"]

        sources = []
        for example in list_data_dict:
            tmp = prompt_input.format_map(example)
            sources.append(tmp)

        targets = []
        for example in list_data_dict:
            targets.append(f"{example[pattern_output]}{tokenizer.eos_token}")
        examples = [s + t for s, t in zip(sources, targets)]

        sources_tokenized = self._tokenize_fn(sources, tokenizer)  # source
        examples_tokenized = self._tokenize_fn(examples, tokenizer)  # source + target

        input_ids = examples_tokenized["input_ids"]
        labels = copy.deepcopy(input_ids)
        for label, source_len in zip(labels, sources_tokenized["input_ids_lens"]):
            label[:source_len] = -100

        data_dict = dict(input_ids=input_ids, labels=labels)

        self.input_ids = data_dict["input_ids"]
        self.labels = data_dict["labels"]
        logging.warning("Loading data done!!: %d"%(len(self.labels)))


    def _tokenize_fn(self, strings: Sequence[str], tokenizer: transformers.PreTrainedTokenizer) -> Dict:
        tokenized_list = [
            tokenizer(
                text,
                return_tensors="pt",
                padding="longest",
                max_length=tokenizer.model_max_length,
                truncation=True,
            )
            for text in strings
        ]
        input_ids = labels = [tokenized.input_ids[0] for tokenized in tokenized_list]
        input_ids_lens = labels_lens = [
            tokenized.input_ids.ne(tokenizer.pad_token_id).sum().item() for tokenized in tokenized_list
        ]
        return dict(
            input_ids=input_ids,
            labels=labels,
            input_ids_lens=input_ids_lens,
            labels_lens=labels_lens,
        )


    def __len__(self):
        return len(self.input_ids)


    def __getitem__(self, i) -> Dict[str, torch.Tensor]:
        return dict(input_ids=self.input_ids[i], labels=self.labels[i])

In [44]:
@dataclass
class DataCollatorForSupervisedDataset(object):

    tokenizer: transformers.PreTrainedTokenizer

    def __call__(self, instances: Sequence[Dict]) -> Dict[str, torch.Tensor]:
        input_ids, labels = tuple([instance[key] for instance in instances] for key in ("input_ids", "labels"))
        input_ids = torch.nn.utils.rnn.pad_sequence(
            input_ids, batch_first=True, padding_value=self.tokenizer.pad_token_id
        )
        labels = torch.nn.utils.rnn.pad_sequence(labels, batch_first=True, padding_value= -100)
        return dict(
            input_ids=input_ids,
            labels=labels,
            attention_mask=input_ids.ne(self.tokenizer.pad_token_id),
        )

In [45]:
train_dataset = SFT_dataset(data_path_1_SFT=os.getenv('HOME') +'/KoChatGPT/data_kochatgpt/kochatgpt_1_SFT.jsonl', tokenizer=tokenizer)
data_collator = DataCollatorForSupervisedDataset(tokenizer=tokenizer)

print('input : %s'%train_dataset.input_ids[0])
print('output: %s'%train_dataset.labels[0])

WARNING:root:Loading data...
WARNING:root:Loading data done!!: 12000

input : tensor([  739,   378,   378,   378, 14659, 13394, 37091, 10651,   383, 25841,
         8006, 14914,   375,  7673, 20479,  8091, 22311,  9036, 30902, 13675,
          375,   378,   378,   378, 41951,   454,  9549, 20549,   383,  8142,
         7192, 14914,   382, 37767, 13753,  8263,  7166,   739,  8352,  7659,
         9594, 25585, 13600,  8022,  9378, 11532,  9887, 11218,  9111, 16691,
        10351, 10561,  9128, 20479,  8091,  9065,  9446,  9036, 28420, 26521,
        10163, 26367,  6958,  9030,  9882, 12317, 25882,  9209, 37194, 10351,
         9036, 12168, 10529, 15989,  9719, 15434, 10552, 11188, 13362,  9036,
        15805, 11300, 11846,  9146, 16691,  9181,  7397, 15806, 13480, 11342,
        17596,  9161, 19996,  9025, 25006, 18595,  9966, 12592, 10751, 11814,
         8711,  9046, 12450,  9117,  7377, 12521,     1])
output: tensor([ -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,   382, 37767, 13753,  8263,  7166,   739,  8352,  7659,
         9594, 25585, 13600,  8022,  9378, 11532,  9887, 11218,  9111, 16691,
        10351, 10561,  9128, 20479,  8091,  9065,  9446,  9036, 28420, 26521,
        10163, 26367,  6958,  9030,  9882, 12317, 25882,  9209, 37194, 10351,
         9036, 12168, 10529, 15989,  9719, 15434, 10552, 11188, 13362,  9036,
        15805, 11300, 11846,  9146, 16691,  9181,  7397, 15806, 13480, 11342,
        17596,  9161, 19996,  9025, 25006, 18595,  9966, 12592, 10751, 11814,
         8711,  9046, 12450,  9117,  7377, 12521,     1])

In [28]:
training_args = transformers.TrainingArguments(
    output_dir="test",
    num_train_epochs=1,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=5,
    prediction_loss_only=True,
    fp16 = True
    )
trainer = transformers.Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset
)

In [29]:
trainer.train()
model.save_pretrained('models/output_1_SFT')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [46]:
generator = transformers.pipeline('text-generation', model='models/output_1_SFT', tokenizer=tokenizer)

generation_args = dict(
    num_beams=4,
    repetition_penalty=2.0,
    no_repeat_ngram_size=4,
    eos_token_id=375, # \n
    max_new_tokens=64,
    do_sample=True,
    top_k=50,
    early_stopping=True
)

PROMPT_DICT = {
    "prompt_input": (
        "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"
    )
}

list_prompt = ['불고기용 고기 한우에요?',
               '리처드 닉슨이 43대 부통령직을 수행한 년도는?',
               '시카고 오헤어 국제공항은 어디에 있어?',
               '오늘 미세먼지 어때?']

list_prompt = [PROMPT_DICT['prompt_input'].format_map({'prompt' : tmp}) for tmp in list_prompt]

list_result = generator(list_prompt, **generation_args)
for prompt, result in zip(list_prompt, list_result):
    print()
    print((result[0]['generated_text']))

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
Passing `generation_config` together with generation-related arguments=({'eos_token_id', 'max_new_tokens', 'repetition_penalty', 'no_repeat_ngram_size', 'num_beams', 'top_k', 'early_stopping', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

### Instruction(명령어):
불고기용 고기 한우에요?

### Response(응답):'저는 인공지능 어시스턴트이기 때문에 고기를 먹을 수 없습니다. 하지만 일반적으로 불고기용 고기는 건강에 좋은 음식 중 하나입니다. 쇠고기의 영양가가 높아 건강에도 좋기 때문입니다. 따라서 고기를 먹는 것은 매우 중요합니다.辛丑)辛丑申丑申丑辛丑辛丑辰丑

### Instruction(명령어):
리처드 닉슨이 43대 부통령직을 수행한 년도는?

### Response(응답):'리처드 닉슨은 41대 부통령직을 수행했습니다.恩恩恩恩殷恩恩恩銀恩恩恩은 1951년부터 1952년까지 부통령직을 수행하였습니다. 이 기간 동안 그는 미국 역사상 가장 큰 대통령 중 한 명이었습니다.恩隱恩恩恩)은 1954년부터 1964년까지 부통령직을 맡았

### Instruction(명령어):
시카고 오헤어 국제공항은 어디에 있어?

### Response(응답):'저는 인공지능 어시스턴트이기 때문에 시카고에 대한 정보를 가지고 있지 않습니다. 하지만 시카고는 미국 캘리포니아주 로스앤젤레스에 위치한 도시입니다.高橋라고도 불립니다.高橋)은 시카고에서 가장 오래된 도시 중 하나입니다.鼓橋는 시카고에서 가장 유명한 도시 중 하나이기도 합니다.鼓

### Instruction(명령어):
오늘 미세먼지 어때?

### Response(응답):'저는 인공지능 챗봇이기 때문에 미세먼지에 대한 정보를 알 수 없습니다. 하지만, 미세먼지는 건강에 매우 중요한 요소 중 하나입니다. 건강한 생활습관을 유지하는 것이 중요합니다. 또한, 미세먼지가 심한 날에는 마스크를 착용하여 미세먼지를 차단하는 것이 좋습니다.了

## SFT - BLEU

In [47]:
from tqdm import tqdm
from nltk.translate.bleu_score import sentence_bleu
from nltk.translate.bleu_score import SmoothingFunction

list_prompt = test_df['instruction'][:100]

list_prompt = [PROMPT_DICT['prompt_input'].format_map({'prompt' : tmp}) for tmp in list_prompt]

list_result = generator(list_prompt, **generation_args)

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Token indices sequence length is longer than the specified maximum sequence length for this model (816 > 512). Running this sequence through the model will result in indexing errors
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [48]:
idx = 0
total_bleu_score = 0.0
generate_sentence = []
for i, (prompt, result) in tqdm(enumerate(zip(list_prompt, list_result))):
    generate_sentence.append(result[0]['generated_text'])
    reference = tokenizer(test_df['chosen'].iloc[idx]).tokens()
    gen_sen = result[0]['generated_text'][result[0]['generated_text'].index('Response(응답):')+13:]
    candidate = tokenizer(gen_sen).tokens()
    
    bleu_score = sentence_bleu([reference], candidate, smoothing_function=SmoothingFunction().method1)
    total_bleu_score += bleu_score
    if i < 5:
        print()
        print(result[0]['generated_text'])
    idx+=1
print('Average BLEU score',total_bleu_score / idx)

28it [00:00, 222.21it/s]

### Instruction(명령어):
한국의 스타크래프트 브루드워 게임 대회의 역대 우승자를 알려줘

### Response(응답):'저는 인공지능 어시스턴트이기 때문에 정확한 답변을 제공할 수 없습니다. 하지만, 한국 프로게이머들의 대회 사상 우승자는 다음과 같습니다.\n\n1. KOREA (Korean League of the Esports)\n2. NC 다이노스(N

### Instruction(명령어):
인터넷 커뮤니티 게시글의 문체로 삼성과 애플의 스마트폰을 비교하는 글을 써줘.

### Response(응답):'저는 인공지능 어시스턴트이기 때문에, 인터넷 커뮤니티에서 사용되는 글들이 어떤 문맥에서 작성되었는지 알 수 없습니다. 하지만, 인터넷 커뮤니티에서 사용하는 글들은 대체로 다음과 같습니다.\n\n1. 삼성 갤럭시 노트\n2. 애플 아이패드\n3. 애플 아이

### Instruction(명령어):
회사를 때려치고 싶을땐 어떻게 해야할까? 대표를 때려도 되나?

### Response(응답):'저는 인공지능 어시스턴트이기 때문에 회사의 상황에 대한 정보를 알 수 없습니다. 하지만 일반적으로 회사에서는 대표이사를 때려치고 싶은 이유가 있을 수 있습니다. 이를 위해 다음과 같은 방법을 시도해 볼 수 있습니다.\n\n1. 경영전략 수립: 회사가 어떤 방향으로 나아갈지에 따라 다르지만, 중요한 것은 경영전략

### Instruction(명령어):
반말로 말하자. 그나저나 질문 하나 할게. 다층 퍼셉트론이 뭐야?

### Response(응답):'저는 인공지능 어시스턴트이기 때문에 답변을 드리기 어렵습니다. 하지만 일반적으로 반말을 사용하는 사람들은 다음과 같습니다.\n\n1. "반말": 반말을 사용하는 것은 자연스러운 표현입니다. 예를 들어, "안녕하세요", "미안해요", "죄송합니다"

### Instruction(명령어):
예수금이랑 인출가능금액 차이나는 이유가 뭔가요?제가 신한 해외 주식 소수점 7천원대를 2개 매수 신청했다가 미체결 됐는데요다시 다른 주식을 매수하려보니 잔액이 부족하다고 뜨네요근데 순자산은 2만원인데.. 미체결된 금액은 어디로 간건지 모르겠어요 ㅜ검색해보니 주식을 다시 매도해야 한다는 글을 봤는데, 소수점 거래라 매도 방식을 모르겠네요..

### Response(응답):'죄송합니다, 저는 인공지능 어시스턴트이기 때문에 정확한 답변을 제공할 수 없습니다. 추가적인 정보를 제공해주시면 더 정확한 답변을 드릴 수 있을 것 같습니다. 감사합니다.出るーンん

100it [00:00, 333.29it/s]

Average BLEU score 0.00229137119020834

## SFT -  ko-gpt-trinity-1.2B-v0.5

In [40]:
torch.cuda.empty_cache()

In [6]:
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

model_name = "skt/ko-gpt-trinity-1.2B-v0.5"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

tokenizer = PreTrainedTokenizerFast.from_pretrained(model_name,  bos_token='</s>', eos_token='</s>', unk_token='</s>', pad_token='</s>',
    padding_side="right",
    model_max_length=512,)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: skt/ko-gpt-trinity-1.2B-v0.5
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...23}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [7]:
input_txt = "바람도 없는 공중에 수직의 파문을 내이며 고요히 떨어지는 오동잎은 누구의 발자취 입니까."

tokens = tokenizer(input_txt).tokens()
input_ids = tokenizer(input_txt, return_tensors="pt")["input_ids"].numpy()

pd.options.display.max_columns = 40
pd.options.display.max_rows = 60
df = pd.DataFrame([tokens, input_ids[0]], index=["kogpt-2_tokens", "Input_IDs"])
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
kogpt-2_tokens,▁바람,도,▁없는,▁공,중에,▁수직,의,▁파,문을,▁내,이며,▁고요,히,▁떨어지는,▁오,동,잎,은,▁누구,의,▁발자,취,▁입,니까.
Input_IDs,31140,20780,30359,30016,31373,41427,25792,30163,31047,30024,31111,51068,29936,36152,30027,20801,25846,25768,31199,25792,44202,27472,30148,37708

### LoRA 설정

In [8]:
for name, module in model.named_modules():
    print(name)

transformer
transformer.wte
transformer.wpe
transformer.drop
transformer.h
transformer.h.0
transformer.h.0.ln_1
transformer.h.0.attn
transformer.h.0.attn.c_attn
transformer.h.0.attn.c_proj
transformer.h.0.attn.attn_dropout
transformer.h.0.attn.resid_dropout
transformer.h.0.ln_2
transformer.h.0.mlp
transformer.h.0.mlp.c_fc
transformer.h.0.mlp.c_proj
transformer.h.0.mlp.act
transformer.h.0.mlp.dropout
transformer.h.1
transformer.h.1.ln_1
transformer.h.1.attn
transformer.h.1.attn.c_attn
transformer.h.1.attn.c_proj
transformer.h.1.attn.attn_dropout
transformer.h.1.attn.resid_dropout
transformer.h.1.ln_2
transformer.h.1.mlp
transformer.h.1.mlp.c_fc
transformer.h.1.mlp.c_proj
transformer.h.1.mlp.act
transformer.h.1.mlp.dropout
transformer.h.2
transformer.h.2.ln_1
transformer.h.2.attn
transformer.h.2.attn.c_attn
transformer.h.2.attn.c_proj
transformer.h.2.attn.attn_dropout
transformer.h.2.attn.resid_dropout
transformer.h.2.ln_2
transformer.h.2.mlp
transformer.h.2.mlp.c_fc
transformer.h.2.mlp.c_proj
transformer.h.2.mlp.act
transformer.h.2.mlp.dropout
transformer.h.3
transformer.h.3.ln_1
transformer.h.3.attn
transformer.h.3.attn.c_attn
transformer.h.3.attn.c_proj
transformer.h.3.attn.attn_dropout
transformer.h.3.attn.resid_dropout
transformer.h.3.ln_2
transformer.h.3.mlp
transformer.h.3.mlp.c_fc
transformer.h.3.mlp.c_proj
transformer.h.3.mlp.act
transformer.h.3.mlp.dropout
transformer.h.4
transformer.h.4.ln_1
transformer.h.4.attn
transformer.h.4.attn.c_attn
transformer.h.4.attn.c_proj
transformer.h.4.attn.attn_dropout
transformer.h.4.attn.resid_dropout
transformer.h.4.ln_2
transformer.h.4.mlp
transformer.h.4.mlp.c_fc
transformer.h.4.mlp.c_proj
transformer.h.4.mlp.act
transformer.h.4.mlp.dropout
transformer.h.5
transformer.h.5.ln_1
transformer.h.5.attn
transformer.h.5.attn.c_attn
transformer.h.5.attn.c_proj
transformer.h.5.attn.attn_dropout
transformer.h.5.attn.resid_dropout
transformer.h.5.ln_2
transformer.h.5.mlp
transformer.h.5.mlp.c_fc
transformer.h.5.mlp.c_proj
transformer.h.5.mlp.act
transformer.h.5.mlp.dropout
transformer.h.6
transformer.h.6.ln_1
transformer.h.6.attn
transformer.h.6.attn.c_attn
transformer.h.6.attn.c_proj
transformer.h.6.attn.attn_dropout
transformer.h.6.attn.resid_dropout
transformer.h.6.ln_2
transformer.h.6.mlp
transformer.h.6.mlp.c_fc
transformer.h.6.mlp.c_proj
transformer.h.6.mlp.act
transformer.h.6.mlp.dropout
transformer.h.7
transformer.h.7.ln_1
transformer.h.7.attn
transformer.h.7.attn.c_attn
transformer.h.7.attn.c_proj
transformer.h.7.attn.attn_dropout
transformer.h.7.attn.resid_dropout
transformer.h.7.ln_2
transformer.h.7.mlp
transformer.h.7.mlp.c_fc
transformer.h.7.mlp.c_proj
transformer.h.7.mlp.act
transformer.h.7.mlp.dropout
transformer.h.8
transformer.h.8.ln_1
transformer.h.8.attn
transformer.h.8.attn.c_attn
transformer.h.8.attn.c_proj
transformer.h.8.attn.attn_dropout
transformer.h.8.attn.resid_dropout
transformer.h.8.ln_2
transformer.h.8.mlp
transformer.h.8.mlp.c_fc
transformer.h.8.mlp.c_proj
transformer.h.8.mlp.act
transformer.h.8.mlp.dropout
transformer.h.9
transformer.h.9.ln_1
transformer.h.9.attn
transformer.h.9.attn.c_attn
transformer.h.9.attn.c_proj
transformer.h.9.attn.attn_dropout
transformer.h.9.attn.resid_dropout
transformer.h.9.ln_2
transformer.h.9.mlp
transformer.h.9.mlp.c_fc
transformer.h.9.mlp.c_proj
transformer.h.9.mlp.act
transformer.h.9.mlp.dropout
transformer.h.10
transformer.h.10.ln_1
transformer.h.10.attn
transformer.h.10.attn.c_attn
transformer.h.10.attn.c_proj
transformer.h.10.attn.attn_dropout
transformer.h.10.attn.resid_dropout
transformer.h.10.ln_2
transformer.h.10.mlp
transformer.h.10.mlp.c_fc
transformer.h.10.mlp.c_proj
transformer.h.10.mlp.act
transformer.h.10.mlp.dropout
transformer.h.11
transformer.h.11.ln_1
transformer.h.11.attn
transformer.h.11.attn.c_attn
transformer.h.11.attn.c_proj
transformer.h.11.attn.attn_dropout
transformer.h.11.attn.resid_dropout
transformer.h.11.ln_2
transformer.h.11.mlp
transformer.h.11.mlp.c_fc
transformer.h.11.mlp.c_proj
transformer.h.11.mlp.act
transformer.h.11.mlp.dropout
transformer.h.12
transformer.h.12.ln_1
transformer.h.12.attn
transformer.h.12.attn.c_attn
transformer.h.12.attn.c_proj
transformer.h.12.attn.attn_dropout
transformer.h.12.attn.resid_dropout
transformer.h.12.ln_2
transformer.h.12.mlp
transformer.h.12.mlp.c_fc
transformer.h.12.mlp.c_proj
transformer.h.12.mlp.act
transformer.h.12.mlp.dropout
transformer.h.13
transformer.h.13.ln_1
transformer.h.13.attn
transformer.h.13.attn.c_attn
transformer.h.13.attn.c_proj
transformer.h.13.attn.attn_dropout
transformer.h.13.attn.resid_dropout
transformer.h.13.ln_2
transformer.h.13.mlp
transformer.h.13.mlp.c_fc
transformer.h.13.mlp.c_proj
transformer.h.13.mlp.act
transformer.h.13.mlp.dropout
transformer.h.14
transformer.h.14.ln_1
transformer.h.14.attn
transformer.h.14.attn.c_attn
transformer.h.14.attn.c_proj
transformer.h.14.attn.attn_dropout
transformer.h.14.attn.resid_dropout
transformer.h.14.ln_2
transformer.h.14.mlp
transformer.h.14.mlp.c_fc
transformer.h.14.mlp.c_proj
transformer.h.14.mlp.act
transformer.h.14.mlp.dropout
transformer.h.15
transformer.h.15.ln_1
transformer.h.15.attn
transformer.h.15.attn.c_attn
transformer.h.15.attn.c_proj
transformer.h.15.attn.attn_dropout
transformer.h.15.attn.resid_dropout
transformer.h.15.ln_2
transformer.h.15.mlp
transformer.h.15.mlp.c_fc
transformer.h.15.mlp.c_proj
transformer.h.15.mlp.act
transformer.h.15.mlp.dropout
transformer.h.16
transformer.h.16.ln_1
transformer.h.16.attn
transformer.h.16.attn.c_attn
transformer.h.16.attn.c_proj
transformer.h.16.attn.attn_dropout
transformer.h.16.attn.resid_dropout
transformer.h.16.ln_2
transformer.h.16.mlp
transformer.h.16.mlp.c_fc
transformer.h.16.mlp.c_proj
transformer.h.16.mlp.act
transformer.h.16.mlp.dropout
transformer.h.17
transformer.h.17.ln_1
transformer.h.17.attn
transformer.h.17.attn.c_attn
transformer.h.17.attn.c_proj
transformer.h.17.attn.attn_dropout
transformer.h.17.attn.resid_dropout
transformer.h.17.ln_2
transformer.h.17.mlp
transformer.h.17.mlp.c_fc
transformer.h.17.mlp.c_proj
transformer.h.17.mlp.act
transformer.h.17.mlp.dropout
transformer.h.18
transformer.h.18.ln_1
transformer.h.18.attn
transformer.h.18.attn.c_attn
transformer.h.18.attn.c_proj
transformer.h.18.attn.attn_dropout
transformer.h.18.attn.resid_dropout
transformer.h.18.ln_2
transformer.h.18.mlp
transformer.h.18.mlp.c_fc
transformer.h.18.mlp.c_proj
transformer.h.18.mlp.act
transformer.h.18.mlp.dropout
transformer.h.19
transformer.h.19.ln_1
transformer.h.19.attn
transformer.h.19.attn.c_attn
transformer.h.19.attn.c_proj
transformer.h.19.attn.attn_dropout
transformer.h.19.attn.resid_dropout
transformer.h.19.ln_2
transformer.h.19.mlp
transformer.h.19.mlp.c_fc
transformer.h.19.mlp.c_proj
transformer.h.19.mlp.act
transformer.h.19.mlp.dropout
transformer.h.20
transformer.h.20.ln_1
transformer.h.20.attn
transformer.h.20.attn.c_attn
transformer.h.20.attn.c_proj
transformer.h.20.attn.attn_dropout
transformer.h.20.attn.resid_dropout
transformer.h.20.ln_2
transformer.h.20.mlp
transformer.h.20.mlp.c_fc
transformer.h.20.mlp.c_proj
transformer.h.20.mlp.act
transformer.h.20.mlp.dropout
transformer.h.21
transformer.h.21.ln_1
transformer.h.21.attn
transformer.h.21.attn.c_attn
transformer.h.21.attn.c_proj
transformer.h.21.attn.attn_dropout
transformer.h.21.attn.resid_dropout
transformer.h.21.ln_2
transformer.h.21.mlp
transformer.h.21.mlp.c_fc
transformer.h.21.mlp.c_proj
transformer.h.21.mlp.act
transformer.h.21.mlp.dropout
transformer.h.22
transformer.h.22.ln_1
transformer.h.22.attn
transformer.h.22.attn.c_attn
transformer.h.22.attn.c_proj
transformer.h.22.attn.attn_dropout
transformer.h.22.attn.resid_dropout
transformer.h.22.ln_2
transformer.h.22.mlp
transformer.h.22.mlp.c_fc
transformer.h.22.mlp.c_proj
transformer.h.22.mlp.act
transformer.h.22.mlp.dropout
transformer.h.23
transformer.h.23.ln_1
transformer.h.23.attn
transformer.h.23.attn.c_attn
transformer.h.23.attn.c_proj
transformer.h.23.attn.attn_dropout
transformer.h.23.attn.resid_dropout
transformer.h.23.ln_2
transformer.h.23.mlp
transformer.h.23.mlp.c_fc
transformer.h.23.mlp.c_proj
transformer.h.23.mlp.act
transformer.h.23.mlp.dropout
transformer.ln_f
lm_head

In [9]:
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=8,                      # rank
    lora_alpha=16,
    target_modules=["c_attn"],  # 중요!! 모델의 모듈명과 구조를 확인해 lora를 어디에 적용할 것인지 판단
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

In [10]:
model = get_peft_model(model, lora_config)
#model.add_adapter(lora_config)
model.print_trainable_parameters()

trainable params: 1,474,560 || all params: 1,164,030,720 || trainable%: 0.1267

In [14]:
model.enable_input_require_grads()
model.gradient_checkpointing_enable()
model.config.use_cache = False

In [14]:
print(type(model))

<class 'peft.peft_model.PeftModelForCausalLM'>

In [15]:

training_args = transformers.TrainingArguments(
    output_dir="test_trinity",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    fp16=True,
    num_train_epochs=1,
    logging_steps=10,
    save_steps=100,
    optim="paged_adamw_8bit"  # 중요
)

trainer = transformers.Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
)

In [16]:
trainer.train()
model.save_pretrained('models/output_1_SFT_trinity')

/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

In [11]:
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

model_name = "skt/ko-gpt-trinity-1.2B-v0.5"


tokenizer = PreTrainedTokenizerFast.from_pretrained(model_name,  bos_token='</s>', eos_token='</s>', unk_token='</s>', pad_token='</s>',
    padding_side="right",
    model_max_length=512,)


generator = transformers.pipeline('text-generation', model='models/output_1_SFT_trinity', tokenizer=tokenizer)

generation_args = dict(
    num_beams=4,
    repetition_penalty=2.0,
    no_repeat_ngram_size=4,
    eos_token_id=tokenizer.eos_token_id, # \n
    max_new_tokens=64,
    do_sample=True,
    top_k=50,
    early_stopping=True
)

PROMPT_DICT = {
    "prompt_input": (
        "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"
    )
}

list_prompt = ['불고기용 고기 한우에요?',
               '리처드 닉슨이 43대 부통령직을 수행한 년도는?',
               '시카고 오헤어 국제공항은 어디에 있어?',
               '오늘 미세먼지 어때?']

list_prompt = [PROMPT_DICT['prompt_input'].format_map({'prompt' : tmp}) for tmp in list_prompt]

list_result = generator(list_prompt, **generation_args)
for prompt, result in zip(list_prompt, list_result):
    print()
    print((result[0]['generated_text']))

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: skt/ko-gpt-trinity-1.2B-v0.5
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...23}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
/opt/conda/lib/python3.12/site-packages/peft/tuners/lora/layer.py:2285: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

Loading weights: 0it [00:00, ?it/s]

GPT2LMHeadModel LOAD REPORT from: models/output_1_SFT_trinity
Key                                                                       | Status     |
--------------------------------------------------------------------------+------------+-
base_model.model.transformer.h.{0...23}.attn.c_attn.lora_A.default.weight | UNEXPECTED |
base_model.model.transformer.h.{0...23}.attn.c_attn.lora_B.default.weight | UNEXPECTED |
transformer.h.{0...23}.attn.c_attn.lora_B.default.weight                  | MISSING    |
transformer.h.{0...23}.attn.c_attn.lora_A.default.weight                  | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Passing `generation_config` together with generation-related arguments=({'do_sample', 'max_new_tokens', 'no_repeat_ngram_size', 'top_k', 'repetition_penalty', 'early_stopping', 'eos_token_id', 'num_beams'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

### Instruction(명령어):
불고기용 고기 한우에요?

### Response(응답): Could you tell me about your beef?
 (고기를 좀 더 주실 수 있나요?)
 What can I have to do for lunch?
 (점심은 무엇을 드시겠습니까?)
 Do you have anything to eat?


### Instruction(명령어):
리처드 닉슨이 43대 부통령직을 수행한 년도는?

### Response(응답):Responsibility(책임감)
 ### Recognition(칭찬):Communication(커뮤니케이션)
 ### Service(봉사):Services(서비스)
 ### Experience(경험):Experiences(경험)


### Instruction(명령어):
시카고 오헤어 국제공항은 어디에 있어?

### Response(응답): How can I get to the airport? (공항까지 어떻게 갈 수 있어?)
 ## Explain(설명): What does it look like? (무엇이 그런 것 같아?)
 ## Describe(추측): What's the

### Instruction(명령어):
오늘 미세먼지 어때?

### Response(응답): 오늘 미세먼지 어때?
  예시 답안: 미세먼지
  본문 스크립트:
  정답 확인:
 [이미지 출처] - 네이버 지식백과 - 다음 지식백과 - 카카오 브런치 - 유튜브
  이미지 출처: Pixabay
  오늘의 퀴

### SFT - ko-gpt-trinity BLEU 계산

In [21]:
from tqdm import tqdm
from nltk.translate.bleu_score import sentence_bleu
from nltk.translate.bleu_score import SmoothingFunction

list_prompt = test_df['instruction'][:100]

list_prompt = [PROMPT_DICT['prompt_input'].format_map({'prompt' : tmp}) for tmp in list_prompt]

list_result = generator(list_prompt, **generation_args)

Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ValueError: not enough values to unpack (expected 3, got 2)

In [48]:
idx = 0
total_bleu_score = 0.0
generate_sentence = []
for i, (prompt, result) in tqdm(enumerate(zip(list_prompt, list_result))):
    generate_sentence.append(result[0]['generated_text'])
    reference = tokenizer(test_df['chosen'].iloc[idx]).tokens()
    gen_sen = result[0]['generated_text'][result[0]['generated_text'].index('Response(응답):')+13:]
    candidate = tokenizer(gen_sen).tokens()
    
    bleu_score = sentence_bleu([reference], candidate, smoothing_function=SmoothingFunction().method1)
    total_bleu_score += bleu_score
    if i < 5:
        print()
        print(result[0]['generated_text'])
    idx+=1
print('Average BLEU score',total_bleu_score / idx)

30it [00:00, 257.95it/s]

### Instruction(명령어):
한국의 스타크래프트 브루드워 게임 대회의 역대 우승자를 알려줘

### Response(응답):게임이 종료되었음을 알림
 ## Successful(성공):우승자에게 상금을 줌
 ## Excellent(훌륭함):우승자들에게 상금을 지급하지 않음
 ## Disappointed(실망):상금을 지급함
 ## Failure

### Instruction(명령어):
인터넷 커뮤니티 게시글의 문체로 삼성과 애플의 스마트폰을 비교하는 글을 써줘.

### Response(응답):Response.response는 response와 responce를 합친 말로, response, responce, reponse가 합쳐진 단어다.
 인터넷 커뮤니티 게시글에 댓글을 다는 방법
 인터넷 커뮤니티 게시글을 자신의 블로그나 미니홈피

### Instruction(명령어):
회사를 때려치고 싶을땐 어떻게 해야할까? 대표를 때려도 되나?

### Response(응답):대표를 때려치우고 싶을 땐 어떻게 해야할까?
 ###
 How to quit the company? 회사를 그만두고 싶을때 어떻게 해야하는가?
 ###
 What do you want to do for your family? 가족들을 위해 무엇을 하고싶은가?
 ###


### Instruction(명령어):
반말로 말하자. 그나저나 질문 하나 할게. 다층 퍼셉트론이 뭐야?

### Response(응답):다층퍼셉트론이라는게 뭔데?
 답변:다층퍼스셉트론이라고 합니다. 자세한건 링크를 참조하세요.
 ### Accessibility(접근성):다층프셉트론이란 무엇인가?
 답변:접근성이라고 합니다.
 ### Descript

### Instruction(명령어):
예수금이랑 인출가능금액 차이나는 이유가 뭔가요?제가 신한 해외 주식 소수점 7천원대를 2개 매수 신청했다가 미체결 됐는데요다시 다른 주식을 매수하려보니 잔액이 부족하다고 뜨네요근데 순자산은 2만원인데.. 미체결된 금액은 어디로 간건지 모르겠어요 ㅜ검색해보니 주식을 다시 매도해야 한다는 글을 봤는데, 소수점 거래라 매도 방식을 모르겠네요..

### Response(응답): 예, 안녕하세요, 고객님. 문의하신 내용에 대해 답변 드립니다. 현재 고객님께서 보유하고 계신 신한 해외주식 소수점 1만원대 주식은 매도가능금액이 차감되어 있는 상태입니다.매도 가능금액을 확인하시기 위해서는 아래의 링크를 참고해 주시기 바랍니다. [신한금융투자] 해외주식

100it [00:00, 429.31it/s]

Average BLEU score 0.002067986126705807

In [49]:
torch.cuda.empty_cache()

## Reward Model

In [14]:
from chatgpt.dataset import RewardDataset
from chatgpt.models.base import RewardModel
from chatgpt.trainer.strategies import NaiveStrategy
from chatgpt.trainer.rm import RewardModelTrainer

from transformers.models.gpt2.configuration_gpt2 import GPT2Config
from transformers.models.gpt2.modeling_gpt2 import GPT2Model

import torch.nn as nn

import random

In [15]:
class GPTRM_custom(RewardModel):

    def __init__(self,
                 pretrained: Optional[str] = None,
                 config: Optional[GPT2Config] = None,
                 checkpoint: bool = False,
                 lora_rank: int = 0,
                 lora_train_bias: str = 'none',
                 tokenizer=None) -> None:
        if pretrained is not None:
            model = GPT2Model.from_pretrained(pretrained)
            model.resize_token_embeddings(len(tokenizer))
        elif config is not None:
            model = GPT2Model(config)
        else:
            model = GPT2Model(GPT2Config())
        if checkpoint:
            model.gradient_checkpointing_enable()

        value_head = nn.Linear(model.config.n_embd, 1)
        super().__init__(model, value_head, lora_rank, lora_train_bias)

        if pretrained is not None:
            self.model = model
            self.pretrained = pretrained


    def save_pretrained(self, dir):
        if self.pretrained is not None:
            self.model.save_pretrained(dir)

In [13]:
model = AutoModelForCausalLM.from_pretrained('skt/kogpt2-base-v2')
tokenizer = PreTrainedTokenizerFast.from_pretrained(
    'skt/kogpt2-base-v2', bos_token='</s>', eos_token='</s>', unk_token='</s>', pad_token='<pad>',
    padding_side="right",
    model_max_length=512,
)

with NaiveStrategy().model_init_context():
        model = GPTRM_custom(pretrained='skt/kogpt2-base-v2', lora_rank=0, tokenizer=tokenizer).cuda()

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/513M [00:00<?, ?B/s]

Cancellation requested; stopping current tasks.

KeyboardInterrupt:

In [60]:
with open(os.getenv('HOME') + '/KoChatGPT/data_kochatgpt/kochatgpt_2_RM.jsonl', "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)

total_data_ranking2chosen = []
for tmp in list_data_dict:
    one_data_ranking2chosen = []

    data = {}
    data['prompt'] = tmp['prompt']
    if tmp['ranking'][0] < tmp['ranking'][1]:
        data['chosen'] = tmp['completion_0']
        data['rejected'] = tmp['completion_1']
    else:
        data['chosen'] = tmp['completion_1']
        data['rejected'] = tmp['completion_0']
    one_data_ranking2chosen.append(data)

    data = {}
    data['prompt'] = tmp['prompt']
    if tmp['ranking'][0] < tmp['ranking'][2]:
        data['chosen'] = tmp['completion_0']
        data['rejected'] = tmp['completion_2']
    else:
        data['chosen'] = tmp['completion_2']
        data['rejected'] = tmp['completion_0']
    one_data_ranking2chosen.append(data)

    data = {}
    data['prompt'] = tmp['prompt']
    if tmp['ranking'][1] < tmp['ranking'][2]:
        data['chosen'] = tmp['completion_1']
        data['rejected'] = tmp['completion_2']
    else:
        data['chosen'] = tmp['completion_2']
        data['rejected'] = tmp['completion_1']
    one_data_ranking2chosen.append(data)



    total_data_ranking2chosen.extend(one_data_ranking2chosen)

print('before data num: %d'%(len(list_data_dict)))
print('after  data num: %d'%(len(total_data_ranking2chosen)))
print('data example: \n%s'%total_data_ranking2chosen[45])

before data num: 10220
after  data num: 30660
data example:
{'prompt': '애플은 리사를 어떻게 처리했어', 'chosen': '애플이 누구인지 명확히 알 수 없어서, 리사가 누구인지와 어떤 상황에서 처리되었는지에 대한 추가적인 정보가 필요합니다. 따라서, 보다 정확한 답변을 제공할 수 없습니다.', 'rejected': '애플은 리사를 위해 고객 서비스 부서에서 고객 다양한 컴퓨터 관련 문제에 대해 응답하는 데 필요한 모든 지원을 제공했습니다. 사용자가 하드웨어 문제를 경험할 때, 전문가들은 필요한 수리(수리, 추가 부품 제공, 소프트웨어 업그레이드 등)을 제공해 드릴 수 있습니다. 또한, 사용자가 사용 방법 문제나 기타 문제를 경험할 때, 대화 상대로 사용자를 지원할 수 있는 전문 고객 서비스 직원들이 사용자에게 상담하고 도움을 주는 데 도움이 될 수 있는 정보를 제공합니다. 또한, 인터넷에서 제공되는 정보를 통해 문제를 해결하거나 고객 서비스 웹 사이트를 통해 자신의 문제를 진단할 수 있도록 하는 등 다양한 방법으로 리사를 처리해 왔습니다.'}

In [61]:
import random
random.seed(230319)
random.shuffle(total_data_ranking2chosen)
print(total_data_ranking2chosen[45])

{'prompt': '유아인이 류승완 감독을 만나 영화 베테랑의 시나리오를 받았던 곳은?', 'chosen': '유아인이 류승완 감독을 만나 영화 베테랑의 시나리오를 받았던 곳은 류승완의 사무실입니다.', 'rejected': '대구 영화사옥'}

In [62]:
train_data = total_data_ranking2chosen[:1000]
eval_data = total_data_ranking2chosen[1000:1200]

print(len(train_data))
print(len(eval_data))

train_dataset = RewardDataset(train_data, tokenizer, 512)
eval_dataset = RewardDataset(eval_data, tokenizer, 512)

1000
200

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/200 [00:00<?, ?it/s]

In [63]:
idx = 1
print('#'*70)
print('## prompt ##')
print(train_data[idx]['prompt'])
print('#'*70)
print('## chosen ##')
print(train_data[idx]['chosen'])
print('#'*70)
print('## rejected ##')
print(train_data[idx]['rejected'])

######################################################################
## prompt ##
흑고래의 무게는 어느 정도야
######################################################################
## chosen ##
흑고래의 평균 몸무게는 약 25~40톤 정도이지만, 최대 몸무게는 50톤 이상에 이를 수 있습니다.
######################################################################
## rejected ##
흑고래의 무게는 매우 다양하게 달라집니다. 약 200kg에서 10톤까지 달라질 수 있습니다.

In [40]:
trainer = RewardModelTrainer(model=model,
                             strategy=NaiveStrategy(),
                             optim=torch.optim.Adam(model.parameters(), lr=5e-5),
                             train_dataset=train_dataset,
                             eval_dataset=eval_dataset,
                             batch_size=4,
                             max_epochs=1)

In [41]:
trainer.fit(use_lora=0)

model.save_pretrained('models/output_2_RM')

Train epoch:   0%|          | 0/1 [00:00<?, ?it/s]
Train step of epoch 0:   0%|          | 0/250 [00:00<?, ?it/s]
Train step of epoch 0:   0%|          | 1/250 [00:00<03:25,  1.21it/s]
Train step of epoch 0:   0%|          | 1/250 [00:01<03:25,  1.21it/s, loss=0.719]
Train step of epoch 0:   1%|          | 2/250 [00:01<03:23,  1.22it/s, loss=0.719]
Train step of epoch 0:   1%|          | 2/250 [00:02<03:23,  1.22it/s, loss=0.513]
Train step of epoch 0:   1%|          | 3/250 [00:02<03:36,  1.14it/s, loss=0.513]
Train step of epoch 0:   1%|          | 3/250 [00:03<03:36,  1.14it/s, loss=0.854]
Train step of epoch 0:   2%|▏         | 4/250 [00:03<03:42,  1.11it/s, loss=0.854]
Train step of epoch 0:   2%|▏         | 4/250 [00:03<03:42,  1.11it/s, loss=0.364]
Train step of epoch 0:   2%|▏         | 5/250 [00:04<03:44,  1.09it/s, loss=0.364]
Train step of epoch 0:   2%|▏         | 5/250 [00:04<03:44,  1.09it/s, loss=0.352]
Train step of epoch 0:   2%|▏         | 6/250 [00:05<03:46,  1.08it/s, loss=0.352]
Train step of epoch 0:   2%|▏         | 6/250 [00:05<03:46,  1.08it/s, loss=0.744]
Train step of epoch 0:   3%|▎         | 7/250 [00:06<03:47,  1.07it/s, loss=0.744]
Train step of epoch 0:   3%|▎         | 7/250 [00:06<03:47,  1.07it/s, loss=0.559]
Train step of epoch 0:   3%|▎         | 8/250 [00:07<03:48,  1.06it/s, loss=0.559]
Train step of epoch 0:   3%|▎         | 8/250 [00:07<03:48,  1.06it/s, loss=1.87]
Train step of epoch 0:   4%|▎         | 9/250 [00:08<03:48,  1.06it/s, loss=1.87]
Train step of epoch 0:   4%|▎         | 9/250 [00:08<03:48,  1.06it/s, loss=0.23]
Train step of epoch 0:   4%|▍         | 10/250 [00:09<03:48,  1.05it/s, loss=0.23]
Train step of epoch 0:   4%|▍         | 10/250 [00:09<03:48,  1.05it/s, loss=1.11]
Train step of epoch 0:   4%|▍         | 11/250 [00:10<03:48,  1.05it/s, loss=1.11]
Train step of epoch 0:   4%|▍         | 11/250 [00:10<03:48,  1.05it/s, loss=0.304]
Train step of epoch 0:   5%|▍         | 12/250 [00:11<03:48,  1.04it/s, loss=0.304]
Train step of epoch 0:   5%|▍         | 12/250 [00:11<03:48,  1.04it/s, loss=0.472]
Train step of epoch 0:   5%|▌         | 13/250 [00:12<03:48,  1.04it/s, loss=0.472]
Train step of epoch 0:   5%|▌         | 13/250 [00:12<03:48,  1.04it/s, loss=0.224]
Train step of epoch 0:   6%|▌         | 14/250 [00:13<03:48,  1.03it/s, loss=0.224]
Train step of epoch 0:   6%|▌         | 14/250 [00:13<03:48,  1.03it/s, loss=1.22]
Train step of epoch 0:   6%|▌         | 15/250 [00:14<03:48,  1.03it/s, loss=1.22]
Train step of epoch 0:   6%|▌         | 15/250 [00:14<03:48,  1.03it/s, loss=0.522]
Train step of epoch 0:   6%|▋         | 16/250 [00:15<03:48,  1.02it/s, loss=0.522]
Train step of epoch 0:   6%|▋         | 16/250 [00:15<03:48,  1.02it/s, loss=1.26]
Train step of epoch 0:   7%|▋         | 17/250 [00:16<03:48,  1.02it/s, loss=1.26]
Train step of epoch 0:   7%|▋         | 17/250 [00:16<03:48,  1.02it/s, loss=0.865]
Train step of epoch 0:   7%|▋         | 18/250 [00:17<03:48,  1.02it/s, loss=0.865]
Train step of epoch 0:   7%|▋         | 18/250 [00:17<03:48,  1.02it/s, loss=0.412]
Train step of epoch 0:   8%|▊         | 19/250 [00:18<03:47,  1.01it/s, loss=0.412]
Train step of epoch 0:   8%|▊         | 19/250 [00:18<03:47,  1.01it/s, loss=0.708]
Train step of epoch 0:   8%|▊         | 20/250 [00:19<03:46,  1.02it/s, loss=0.708]
Train step of epoch 0:   8%|▊         | 20/250 [00:19<03:46,  1.02it/s, loss=0.514]
Train step of epoch 0:   8%|▊         | 21/250 [00:20<03:44,  1.02it/s, loss=0.514]
Train step of epoch 0:   8%|▊         | 21/250 [00:20<03:44,  1.02it/s, loss=0.703]
Train step of epoch 0:   9%|▉         | 22/250 [00:21<03:43,  1.02it/s, loss=0.703]
Train step of epoch 0:   9%|▉         | 22/250 [00:21<03:43,  1.02it/s, loss=0.676]
Train step of epoch 0:   9%|▉         | 23/250 [00:21<03:41,  1.02it/s, loss=0.676]
Train step of epoch 0:   9%|▉         | 23/250 [00:22<03:41,  1.02it/s, loss=0.847]
Train step of epoch 0:  10%|▉         | 24/250 [00:22<03:39,  1.03it/s, loss=0.847]
Train step of epoch 0:  10%|▉         | 24/250 [00:23<03:39,  1.03it/s, loss=0.6]
Train step of epoch 0:  10%|█         | 25/250 [00:23<03:37,  1.03it/s, loss=0.6]
Train step of epoch 0:  10%|█         | 25/250 [00:24<03:37,  1.03it/s, loss=0.553]
Train step of epoch 0:  10%|█         | 26/250 [00:24<03:35,  1.04it/s, loss=0.553]
Train step of epoch 0:  10%|█         | 26/250 [00:25<03:35,  1.04it/s, loss=0.713]
Train step of epoch 0:  11%|█         | 27/250 [00:25<03:33,  1.04it/s, loss=0.713]
Train step of epoch 0:  11%|█         | 27/250 [00:26<03:33,  1.04it/s, loss=0.703]
Train step of epoch 0:  11%|█         | 28/250 [00:26<03:31,  1.05it/s, loss=0.703]
Train step of epoch 0:  11%|█         | 28/250 [00:27<03:31,  1.05it/s, loss=0.601]
Train step of epoch 0:  12%|█▏        | 29/250 [00:27<03:29,  1.05it/s, loss=0.601]
Train step of epoch 0:  12%|█▏        | 29/250 [00:28<03:29,  1.05it/s, loss=0.576]
Train step of epoch 0:  12%|█▏        | 30/250 [00:28<03:27,  1.06it/s, loss=0.576]
Train step of epoch 0:  12%|█▏        | 30/250 [00:29<03:27,  1.06it/s, loss=0.562]
Train step of epoch 0:  12%|█▏        | 31/250 [00:29<03:26,  1.06it/s, loss=0.562]
Train step of epoch 0:  12%|█▏        | 31/250 [00:30<03:26,  1.06it/s, loss=0.499]
Train step of epoch 0:  13%|█▎        | 32/250 [00:30<03:24,  1.07it/s, loss=0.499]
Train step of epoch 0:  13%|█▎        | 32/250 [00:30<03:24,  1.07it/s, loss=0.805]
Train step of epoch 0:  13%|█▎        | 33/250 [00:31<03:22,  1.07it/s, loss=0.805]
Train step of epoch 0:  13%|█▎        | 33/250 [00:31<03:22,  1.07it/s, loss=0.452]
Train step of epoch 0:  14%|█▎        | 34/250 [00:32<03:21,  1.07it/s, loss=0.452]
Train step of epoch 0:  14%|█▎        | 34/250 [00:32<03:21,  1.07it/s, loss=0.547]
Train step of epoch 0:  14%|█▍        | 35/250 [00:33<03:20,  1.07it/s, loss=0.547]
Train step of epoch 0:  14%|█▍        | 35/250 [00:33<03:20,  1.07it/s, loss=1.36]
Train step of epoch 0:  14%|█▍        | 36/250 [00:34<03:18,  1.08it/s, loss=1.36]
Train step of epoch 0:  14%|█▍        | 36/250 [00:34<03:18,  1.08it/s, loss=0.923]
Train step of epoch 0:  15%|█▍        | 37/250 [00:35<03:17,  1.08it/s, loss=0.923]
Train step of epoch 0:  15%|█▍        | 37/250 [00:35<03:17,  1.08it/s, loss=0.78]
Train step of epoch 0:  15%|█▌        | 38/250 [00:36<03:15,  1.08it/s, loss=0.78]
Train step of epoch 0:  15%|█▌        | 38/250 [00:36<03:15,  1.08it/s, loss=0.684]
Train step of epoch 0:  16%|█▌        | 39/250 [00:36<03:14,  1.09it/s, loss=0.684]
Train step of epoch 0:  16%|█▌        | 39/250 [00:37<03:14,  1.09it/s, loss=0.748]
Train step of epoch 0:  16%|█▌        | 40/250 [00:37<03:12,  1.09it/s, loss=0.748]
Train step of epoch 0:  16%|█▌        | 40/250 [00:38<03:12,  1.09it/s, loss=0.516]
Train step of epoch 0:  16%|█▋        | 41/250 [00:38<03:11,  1.09it/s, loss=0.516]
Train step of epoch 0:  16%|█▋        | 41/250 [00:39<03:11,  1.09it/s, loss=0.399]
Train step of epoch 0:  17%|█▋        | 42/250 [00:39<03:10,  1.09it/s, loss=0.399]
Train step of epoch 0:  17%|█▋        | 42/250 [00:40<03:10,  1.09it/s, loss=0.612]
Train step of epoch 0:  17%|█▋        | 43/250 [00:40<03:09,  1.09it/s, loss=0.612]
Train step of epoch 0:  17%|█▋        | 43/250 [00:41<03:09,  1.09it/s, loss=0.759]
Train step of epoch 0:  18%|█▊        | 44/250 [00:41<03:07,  1.10it/s, loss=0.759]
Train step of epoch 0:  18%|█▊        | 44/250 [00:41<03:07,  1.10it/s, loss=0.983]
Train step of epoch 0:  18%|█▊        | 45/250 [00:42<03:06,  1.10it/s, loss=0.983]
Train step of epoch 0:  18%|█▊        | 45/250 [00:42<03:06,  1.10it/s, loss=0.535]
Train step of epoch 0:  18%|█▊        | 46/250 [00:43<03:05,  1.10it/s, loss=0.535]
Train step of epoch 0:  18%|█▊        | 46/250 [00:43<03:05,  1.10it/s, loss=0.549]
Train step of epoch 0:  19%|█▉        | 47/250 [00:44<03:04,  1.10it/s, loss=0.549]
Train step of epoch 0:  19%|█▉        | 47/250 [00:44<03:04,  1.10it/s, loss=0.76]
Train step of epoch 0:  19%|█▉        | 48/250 [00:45<03:03,  1.10it/s, loss=0.76]
Train step of epoch 0:  19%|█▉        | 48/250 [00:45<03:03,  1.10it/s, loss=0.713]
Train step of epoch 0:  20%|█▉        | 49/250 [00:46<03:02,  1.10it/s, loss=0.713]
Train step of epoch 0:  20%|█▉        | 49/250 [00:46<03:02,  1.10it/s, loss=0.602]
Train step of epoch 0:  20%|██        | 50/250 [00:46<03:01,  1.10it/s, loss=0.602]
Train step of epoch 0:  20%|██        | 50/250 [00:47<03:01,  1.10it/s, loss=0.906]
Train step of epoch 0:  20%|██        | 51/250 [00:47<03:00,  1.11it/s, loss=0.906]
Train step of epoch 0:  20%|██        | 51/250 [00:48<03:00,  1.11it/s, loss=0.465]
Train step of epoch 0:  21%|██        | 52/250 [00:48<02:58,  1.11it/s, loss=0.465]
Train step of epoch 0:  21%|██        | 52/250 [00:49<02:58,  1.11it/s, loss=0.653]
Train step of epoch 0:  21%|██        | 53/250 [00:49<02:58,  1.11it/s, loss=0.653]
Train step of epoch 0:  21%|██        | 53/250 [00:50<02:58,  1.11it/s, loss=0.515]
Train step of epoch 0:  22%|██▏       | 54/250 [00:50<02:56,  1.11it/s, loss=0.515]
Train step of epoch 0:  22%|██▏       | 54/250 [00:50<02:56,  1.11it/s, loss=0.315]
Train step of epoch 0:  22%|██▏       | 55/250 [00:51<02:55,  1.11it/s, loss=0.315]
Train step of epoch 0:  22%|██▏       | 55/250 [00:51<02:55,  1.11it/s, loss=0.519]
Train step of epoch 0:  22%|██▏       | 56/250 [00:52<02:55,  1.11it/s, loss=0.519]
Train step of epoch 0:  22%|██▏       | 56/250 [00:52<02:55,  1.11it/s, loss=0.642]
Train step of epoch 0:  23%|██▎       | 57/250 [00:53<02:53,  1.11it/s, loss=0.642]
Train step of epoch 0:  23%|██▎       | 57/250 [00:53<02:53,  1.11it/s, loss=0.491]
Train step of epoch 0:  23%|██▎       | 58/250 [00:54<02:52,  1.11it/s, loss=0.491]
Train step of epoch 0:  23%|██▎       | 58/250 [00:54<02:52,  1.11it/s, loss=0.418]
Train step of epoch 0:  24%|██▎       | 59/250 [00:55<02:51,  1.11it/s, loss=0.418]
Train step of epoch 0:  24%|██▎       | 59/250 [00:55<02:51,  1.11it/s, loss=0.522]
Train step of epoch 0:  24%|██▍       | 60/250 [00:55<02:51,  1.11it/s, loss=0.522]
Train step of epoch 0:  24%|██▍       | 60/250 [00:56<02:51,  1.11it/s, loss=0.357]
Train step of epoch 0:  24%|██▍       | 61/250 [00:56<02:50,  1.11it/s, loss=0.357]
Train step of epoch 0:  24%|██▍       | 61/250 [00:57<02:50,  1.11it/s, loss=1.02]
Train step of epoch 0:  25%|██▍       | 62/250 [00:57<02:49,  1.11it/s, loss=1.02]
Train step of epoch 0:  25%|██▍       | 62/250 [00:58<02:49,  1.11it/s, loss=0.204]
Train step of epoch 0:  25%|██▌       | 63/250 [00:58<02:48,  1.11it/s, loss=0.204]
Train step of epoch 0:  25%|██▌       | 63/250 [00:59<02:48,  1.11it/s, loss=0.805]
Train step of epoch 0:  26%|██▌       | 64/250 [00:59<02:47,  1.11it/s, loss=0.805]
Train step of epoch 0:  26%|██▌       | 64/250 [00:59<02:47,  1.11it/s, loss=0.218]
Train step of epoch 0:  26%|██▌       | 65/250 [01:00<02:46,  1.11it/s, loss=0.218]
Train step of epoch 0:  26%|██▌       | 65/250 [01:00<02:46,  1.11it/s, loss=0.812]
Train step of epoch 0:  26%|██▋       | 66/250 [01:01<02:45,  1.11it/s, loss=0.812]
Train step of epoch 0:  26%|██▋       | 66/250 [01:01<02:45,  1.11it/s, loss=0.102]
Train step of epoch 0:  27%|██▋       | 67/250 [01:02<02:45,  1.11it/s, loss=0.102]
Train step of epoch 0:  27%|██▋       | 67/250 [01:02<02:45,  1.11it/s, loss=0.997]
Train step of epoch 0:  27%|██▋       | 68/250 [01:03<02:44,  1.11it/s, loss=0.997]
Train step of epoch 0:  27%|██▋       | 68/250 [01:03<02:44,  1.11it/s, loss=0.249]
Train step of epoch 0:  28%|██▊       | 69/250 [01:04<02:43,  1.11it/s, loss=0.249]
Train step of epoch 0:  28%|██▊       | 69/250 [01:04<02:43,  1.11it/s, loss=1.01]
Train step of epoch 0:  28%|██▊       | 70/250 [01:04<02:42,  1.11it/s, loss=1.01]
Train step of epoch 0:  28%|██▊       | 70/250 [01:05<02:42,  1.11it/s, loss=0.795]
Train step of epoch 0:  28%|██▊       | 71/250 [01:05<02:41,  1.11it/s, loss=0.795]
Train step of epoch 0:  28%|██▊       | 71/250 [01:06<02:41,  1.11it/s, loss=0.487]
Train step of epoch 0:  29%|██▉       | 72/250 [01:06<02:40,  1.11it/s, loss=0.487]
Train step of epoch 0:  29%|██▉       | 72/250 [01:07<02:40,  1.11it/s, loss=0.983]
Train step of epoch 0:  29%|██▉       | 73/250 [01:07<02:40,  1.10it/s, loss=0.983]
Train step of epoch 0:  29%|██▉       | 73/250 [01:08<02:40,  1.10it/s, loss=0.701]
Train step of epoch 0:  30%|██▉       | 74/250 [01:08<02:39,  1.10it/s, loss=0.701]
Train step of epoch 0:  30%|██▉       | 74/250 [01:09<02:39,  1.10it/s, loss=0.502]
Train step of epoch 0:  30%|███       | 75/250 [01:09<02:38,  1.10it/s, loss=0.502]
Train step of epoch 0:  30%|███       | 75/250 [01:09<02:38,  1.10it/s, loss=0.555]
Train step of epoch 0:  30%|███       | 76/250 [01:10<02:38,  1.10it/s, loss=0.555]
Train step of epoch 0:  30%|███       | 76/250 [01:10<02:38,  1.10it/s, loss=0.704]
Train step of epoch 0:  31%|███       | 77/250 [01:11<02:36,  1.10it/s, loss=0.704]
Train step of epoch 0:  31%|███       | 77/250 [01:11<02:36,  1.10it/s, loss=0.454]
Train step of epoch 0:  31%|███       | 78/250 [01:12<02:36,  1.10it/s, loss=0.454]
Train step of epoch 0:  31%|███       | 78/250 [01:12<02:36,  1.10it/s, loss=0.717]
Train step of epoch 0:  32%|███▏      | 79/250 [01:13<02:35,  1.10it/s, loss=0.717]
Train step of epoch 0:  32%|███▏      | 79/250 [01:13<02:35,  1.10it/s, loss=0.53]
Train step of epoch 0:  32%|███▏      | 80/250 [01:14<02:34,  1.10it/s, loss=0.53]
Train step of epoch 0:  32%|███▏      | 80/250 [01:14<02:34,  1.10it/s, loss=0.714]
Train step of epoch 0:  32%|███▏      | 81/250 [01:14<02:33,  1.10it/s, loss=0.714]
Train step of epoch 0:  32%|███▏      | 81/250 [01:15<02:33,  1.10it/s, loss=0.419]
Train step of epoch 0:  33%|███▎      | 82/250 [01:15<02:33,  1.10it/s, loss=0.419]
Train step of epoch 0:  33%|███▎      | 82/250 [01:16<02:33,  1.10it/s, loss=0.844]
Train step of epoch 0:  33%|███▎      | 83/250 [01:16<02:32,  1.10it/s, loss=0.844]
Train step of epoch 0:  33%|███▎      | 83/250 [01:17<02:32,  1.10it/s, loss=0.644]
Train step of epoch 0:  34%|███▎      | 84/250 [01:17<02:31,  1.09it/s, loss=0.644]
Train step of epoch 0:  34%|███▎      | 84/250 [01:18<02:31,  1.09it/s, loss=0.633]
Train step of epoch 0:  34%|███▍      | 85/250 [01:18<02:30,  1.09it/s, loss=0.633]
Train step of epoch 0:  34%|███▍      | 85/250 [01:19<02:30,  1.09it/s, loss=0.763]
Train step of epoch 0:  34%|███▍      | 86/250 [01:19<02:30,  1.09it/s, loss=0.763]
Train step of epoch 0:  34%|███▍      | 86/250 [01:20<02:30,  1.09it/s, loss=0.599]
Train step of epoch 0:  35%|███▍      | 87/250 [01:20<02:29,  1.09it/s, loss=0.599]
Train step of epoch 0:  35%|███▍      | 87/250 [01:20<02:29,  1.09it/s, loss=0.584]
Train step of epoch 0:  35%|███▌      | 88/250 [01:21<02:28,  1.09it/s, loss=0.584]
Train step of epoch 0:  35%|███▌      | 88/250 [01:21<02:28,  1.09it/s, loss=0.798]
Train step of epoch 0:  36%|███▌      | 89/250 [01:22<02:27,  1.09it/s, loss=0.798]
Train step of epoch 0:  36%|███▌      | 89/250 [01:22<02:27,  1.09it/s, loss=0.782]
Train step of epoch 0:  36%|███▌      | 90/250 [01:23<02:27,  1.09it/s, loss=0.782]
Train step of epoch 0:  36%|███▌      | 90/250 [01:23<02:27,  1.09it/s, loss=0.635]
Train step of epoch 0:  36%|███▋      | 91/250 [01:24<02:26,  1.09it/s, loss=0.635]
Train step of epoch 0:  36%|███▋      | 91/250 [01:24<02:26,  1.09it/s, loss=0.621]
Train step of epoch 0:  37%|███▋      | 92/250 [01:25<02:25,  1.09it/s, loss=0.621]
Train step of epoch 0:  37%|███▋      | 92/250 [01:25<02:25,  1.09it/s, loss=0.619]
Train step of epoch 0:  37%|███▋      | 93/250 [01:26<02:24,  1.08it/s, loss=0.619]
Train step of epoch 0:  37%|███▋      | 93/250 [01:26<02:24,  1.08it/s, loss=0.819]
Train step of epoch 0:  38%|███▊      | 94/250 [01:26<02:24,  1.08it/s, loss=0.819]
Train step of epoch 0:  38%|███▊      | 94/250 [01:27<02:24,  1.08it/s, loss=0.703]
Train step of epoch 0:  38%|███▊      | 95/250 [01:27<02:23,  1.08it/s, loss=0.703]
Train step of epoch 0:  38%|███▊      | 95/250 [01:28<02:23,  1.08it/s, loss=0.491]
Train step of epoch 0:  38%|███▊      | 96/250 [01:28<02:22,  1.08it/s, loss=0.491]
Train step of epoch 0:  38%|███▊      | 96/250 [01:29<02:22,  1.08it/s, loss=0.706]
Train step of epoch 0:  39%|███▉      | 97/250 [01:29<02:21,  1.08it/s, loss=0.706]
Train step of epoch 0:  39%|███▉      | 97/250 [01:30<02:21,  1.08it/s, loss=0.771]
Train step of epoch 0:  39%|███▉      | 98/250 [01:30<02:21,  1.08it/s, loss=0.771]
Train step of epoch 0:  39%|███▉      | 98/250 [01:31<02:21,  1.08it/s, loss=0.774]
Train step of epoch 0:  40%|███▉      | 99/250 [01:31<02:20,  1.08it/s, loss=0.774]
Train step of epoch 0:  40%|███▉      | 99/250 [01:32<02:20,  1.08it/s, loss=0.577]
Train step of epoch 0:  40%|████      | 100/250 [01:32<02:19,  1.07it/s, loss=0.577]
Train step of epoch 0:  40%|████      | 100/250 [01:32<02:19,  1.07it/s, loss=0.589]
Train step of epoch 0:  40%|████      | 101/250 [01:33<02:18,  1.07it/s, loss=0.589]
Train step of epoch 0:  40%|████      | 101/250 [01:33<02:18,  1.07it/s, loss=0.761]
Train step of epoch 0:  41%|████      | 102/250 [01:34<02:17,  1.07it/s, loss=0.761]
Train step of epoch 0:  41%|████      | 102/250 [01:34<02:17,  1.07it/s, loss=0.67]
Train step of epoch 0:  41%|████      | 103/250 [01:35<02:17,  1.07it/s, loss=0.67]
Train step of epoch 0:  41%|████      | 103/250 [01:35<02:17,  1.07it/s, loss=0.747]
Train step of epoch 0:  42%|████▏     | 104/250 [01:36<02:16,  1.07it/s, loss=0.747]
Train step of epoch 0:  42%|████▏     | 104/250 [01:36<02:16,  1.07it/s, loss=0.847]
Train step of epoch 0:  42%|████▏     | 105/250 [01:37<02:15,  1.07it/s, loss=0.847]
Train step of epoch 0:  42%|████▏     | 105/250 [01:37<02:15,  1.07it/s, loss=0.677]
Train step of epoch 0:  42%|████▏     | 106/250 [01:38<02:14,  1.07it/s, loss=0.677]
Train step of epoch 0:  42%|████▏     | 106/250 [01:38<02:14,  1.07it/s, loss=0.619]
Train step of epoch 0:  43%|████▎     | 107/250 [01:39<02:13,  1.07it/s, loss=0.619]
Train step of epoch 0:  43%|████▎     | 107/250 [01:39<02:13,  1.07it/s, loss=0.786]
Train step of epoch 0:  43%|████▎     | 108/250 [01:39<02:12,  1.07it/s, loss=0.786]
Train step of epoch 0:  43%|████▎     | 108/250 [01:40<02:12,  1.07it/s, loss=0.571]
Train step of epoch 0:  44%|████▎     | 109/250 [01:40<02:11,  1.07it/s, loss=0.571]
Train step of epoch 0:  44%|████▎     | 109/250 [01:41<02:11,  1.07it/s, loss=0.685]
Train step of epoch 0:  44%|████▍     | 110/250 [01:41<02:10,  1.07it/s, loss=0.685]
Train step of epoch 0:  44%|████▍     | 110/250 [01:42<02:10,  1.07it/s, loss=0.674]
Train step of epoch 0:  44%|████▍     | 111/250 [01:42<02:10,  1.07it/s, loss=0.674]
Train step of epoch 0:  44%|████▍     | 111/250 [01:43<02:10,  1.07it/s, loss=0.58]
Train step of epoch 0:  45%|████▍     | 112/250 [01:43<02:09,  1.07it/s, loss=0.58]
Train step of epoch 0:  45%|████▍     | 112/250 [01:44<02:09,  1.07it/s, loss=0.642]
Train step of epoch 0:  45%|████▌     | 113/250 [01:44<02:08,  1.07it/s, loss=0.642]
Train step of epoch 0:  45%|████▌     | 113/250 [01:45<02:08,  1.07it/s, loss=0.688]
Train step of epoch 0:  46%|████▌     | 114/250 [01:45<02:07,  1.07it/s, loss=0.688]
Train step of epoch 0:  46%|████▌     | 114/250 [01:46<02:07,  1.07it/s, loss=0.856]
Train step of epoch 0:  46%|████▌     | 115/250 [01:46<02:06,  1.07it/s, loss=0.856]
Train step of epoch 0:  46%|████▌     | 115/250 [01:46<02:06,  1.07it/s, loss=0.74]
Train step of epoch 0:  46%|████▋     | 116/250 [01:47<02:05,  1.07it/s, loss=0.74]
Train step of epoch 0:  46%|████▋     | 116/250 [01:47<02:05,  1.07it/s, loss=0.6]
Train step of epoch 0:  47%|████▋     | 117/250 [01:48<02:04,  1.07it/s, loss=0.6]
Train step of epoch 0:  47%|████▋     | 117/250 [01:48<02:04,  1.07it/s, loss=0.517]
Train step of epoch 0:  47%|████▋     | 118/250 [01:49<02:03,  1.07it/s, loss=0.517]
Train step of epoch 0:  47%|████▋     | 118/250 [01:49<02:03,  1.07it/s, loss=0.529]
Train step of epoch 0:  48%|████▊     | 119/250 [01:50<02:02,  1.07it/s, loss=0.529]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [42]:
def inference_RM(input_text):
    input_ids = tokenizer.encode(input_text, return_tensors='pt').cuda()
    output = model(input_ids)
    output_reward = output.cpu().detach().numpy()[0]

    print('input: %s\nreward score: %.1f'%(input_text, output_reward))

    return output_reward

input_text = '인공지능은 똥멍청이 입니다'
output_reward = inference_RM(input_text=input_text)

input: 인공지능은 똥멍청이 입니다
reward score: 0.1

In [43]:
input_text = '인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다.'

output_reward = inference_RM(input_text=input_text)

input: 인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다.
reward score: 0.4

In [44]:
input_text = "인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다. AI는 현대적인 컴퓨팅 혁신에서 중추적인 역할을 하며 개인과 비즈니스의 가치를 창출합니다. 예를 들어 광학 문자 인식(OCR)은 AI를 사용해 이미지 및 문서에서 텍스트 및 데이터를 추출하고, 구조화되지 않은 콘텐츠를 비즈니스에 바로 사용할 수 있게 만들고, 유용한 정보를 창출합니다."

output_reward = inference_RM(input_text=input_text)

input: 인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다. AI는 현대적인 컴퓨팅 혁신에서 중추적인 역할을 하며 개인과 비즈니스의 가치를 창출합니다. 예를 들어 광학 문자 인식(OCR)은 AI를 사용해 이미지 및 문서에서 텍스트 및 데이터를 추출하고, 구조화되지 않은 콘텐츠를 비즈니스에 바로 사용할 수 있게 만들고, 유용한 정보를 창출합니다.
reward score: 0.6

In [45]:
input_text = "인공지능은 일반적으로 인간의 지능이 필요하거나 인간이 분석할 수 있는 것보다 규모가 큰 데이터를 포함하는 방식으로 추론, 학습 및 행동할 수 있는 컴퓨터 및 기계를 구축하는 것과 관련된 과학 분야입니다. AI는 컴퓨터 공학, 데이터 분석 및 통계, 하드웨어 및 소프트웨어 엔지니어링, 언어학, 신경 과학은 물론 철학과 심리학을 포함하여 여러 학문을 포괄하는 광범위한 분야입니다. 비즈니스의 운영 수준에서 AI는 주로 머신러닝과 딥 러닝을 기반으로 하는 기술 모음으로, 데이터 분석, 예상 및 예측, 객체 분류, 자연어 처리, 추천, 지능형 데이터 가져오기 등을 수행할 수 있습니다."

output_reward = inference_RM(input_text=input_text)

input: 인공지능은 일반적으로 인간의 지능이 필요하거나 인간이 분석할 수 있는 것보다 규모가 큰 데이터를 포함하는 방식으로 추론, 학습 및 행동할 수 있는 컴퓨터 및 기계를 구축하는 것과 관련된 과학 분야입니다. AI는 컴퓨터 공학, 데이터 분석 및 통계, 하드웨어 및 소프트웨어 엔지니어링, 언어학, 신경 과학은 물론 철학과 심리학을 포함하여 여러 학문을 포괄하는 광범위한 분야입니다. 비즈니스의 운영 수준에서 AI는 주로 머신러닝과 딥 러닝을 기반으로 하는 기술 모음으로, 데이터 분석, 예상 및 예측, 객체 분류, 자연어 처리, 추천, 지능형 데이터 가져오기 등을 수행할 수 있습니다.
reward score: 0.6

## Reward model - ko-gpt-trinity

In [16]:
from chatgpt.dataset import RewardDataset
from chatgpt.models.base import RewardModel
from chatgpt.trainer.strategies import NaiveStrategy
from chatgpt.trainer.rm import RewardModelTrainer

from transformers.models.gpt2.configuration_gpt2 import GPT2Config
from transformers.models.gpt2.modeling_gpt2 import GPT2Model

from transformers import AutoModel, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

import torch.nn as nn

import random

In [17]:
class GPTRM_custom2(RewardModel):

    def __init__(self,
                 pretrained: Optional[str] = None,
                 config: Optional[GPT2Config] = None,
                 checkpoint: bool = False,
                 lora_rank: int = 0,
                 lora_train_bias: str = 'none',
                 tokenizer=None) -> None:
        
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True
        )
        
        if pretrained is not None:
            model = AutoModel.from_pretrained(pretrained, quantization_config=bnb_config, device_map='auto')
            model.resize_token_embeddings(len(tokenizer))

            model = prepare_model_for_kbit_training(model)
    
            lora_config = LoraConfig(
                r=8,
                lora_alpha=16,
                target_modules=["c_attn"],
                lora_dropout=0.05,
                bias="none",
                task_type="FEATURE_EXTRACTION"  # 🔥 중요
            )
    
            model = get_peft_model(model, lora_config)
            
        elif config is not None:
            model = GPT2Model(config)
        else:
            model = GPT2Model(GPT2Config())
        if checkpoint:
            model.gradient_checkpointing_enable()

        value_head = nn.Linear(model.config.n_embd, 1)
        super().__init__(model, value_head, lora_rank, lora_train_bias)

        if pretrained is not None:
            self.model = model
            self.pretrained = pretrained


    def save_pretrained(self, dir):
        if self.pretrained is not None:
            self.model.save_pretrained(dir)

In [58]:

tokenizer = PreTrainedTokenizerFast.from_pretrained(model_name,  bos_token='</s>', eos_token='</s>', unk_token='</s>', pad_token='</s>',
    padding_side="right",
    model_max_length=512,)

with NaiveStrategy().model_init_context():
        model = GPTRM_custom2(pretrained = model_name, lora_rank=0, tokenizer=tokenizer).cuda()

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

GPT2Model LOAD REPORT from: skt/ko-gpt-trinity-1.2B-v0.5
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...23}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [64]:
trainer = RewardModelTrainer(model=model,
                             strategy=NaiveStrategy(),
                             optim=torch.optim.Adam(model.parameters(), lr=5e-5),
                             train_dataset=train_dataset,
                             eval_dataset=eval_dataset,
                             batch_size=1,
                             max_epochs=1)

In [65]:
trainer.fit(use_lora=0)

model.save_pretrained('models/output_2_RM_trinity')

Train epoch:   0%|          | 0/1 [00:00<?, ?it/s]
Train step of epoch 0:   0%|          | 0/1000 [00:00<?, ?it/s]`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
/opt/conda/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py:838: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

Train step of epoch 0:   0%|          | 1/1000 [00:01<22:39,  1.36s/it]
Train step of epoch 0:   0%|          | 1/1000 [00:01<22:39,  1.36s/it, loss=0.72]
Train step of epoch 0:   0%|          | 2/1000 [00:02<19:53,  1.20s/it, loss=0.72]
Train step of epoch 0:   0%|          | 2/1000 [00:02<19:53,  1.20s/it, loss=0.706]
Train step of epoch 0:   0%|          | 3/1000 [00:03<20:10,  1.21s/it, loss=0.706]
Train step of epoch 0:   0%|          | 3/1000 [00:03<20:10,  1.21s/it, loss=0.589]
Train step of epoch 0:   0%|          | 4/1000 [00:04<20:16,  1.22s/it, loss=0.589]
Train step of epoch 0:   0%|          | 4/1000 [00:05<20:16,  1.22s/it, loss=0.645]
Train step of epoch 0:   0%|          | 5/1000 [00:06<20:20,  1.23s/it, loss=0.645]
Train step of epoch 0:   0%|          | 5/1000 [00:06<20:20,  1.23s/it, loss=0.513]
Train step of epoch 0:   1%|          | 6/1000 [00:07<20:22,  1.23s/it, loss=0.513]
Train step of epoch 0:   1%|          | 6/1000 [00:07<20:22,  1.23s/it, loss=0.84]
Train step of epoch 0:   1%|          | 7/1000 [00:08<20:24,  1.23s/it, loss=0.84]
Train step of epoch 0:   1%|          | 7/1000 [00:08<20:24,  1.23s/it, loss=0.985]
Train step of epoch 0:   1%|          | 8/1000 [00:09<20:25,  1.24s/it, loss=0.985]
Train step of epoch 0:   1%|          | 8/1000 [00:10<20:25,  1.24s/it, loss=0.435]
Train step of epoch 0:   1%|          | 9/1000 [00:11<20:25,  1.24s/it, loss=0.435]
Train step of epoch 0:   1%|          | 9/1000 [00:11<20:25,  1.24s/it, loss=0.779]
Train step of epoch 0:   1%|          | 10/1000 [00:12<20:24,  1.24s/it, loss=0.779]
Train step of epoch 0:   1%|          | 10/1000 [00:12<20:24,  1.24s/it, loss=0.401]
Train step of epoch 0:   1%|          | 11/1000 [00:13<20:23,  1.24s/it, loss=0.401]
Train step of epoch 0:   1%|          | 11/1000 [00:13<20:23,  1.24s/it, loss=0.662]
Train step of epoch 0:   1%|          | 12/1000 [00:14<20:24,  1.24s/it, loss=0.662]
Train step of epoch 0:   1%|          | 12/1000 [00:14<20:24,  1.24s/it, loss=0.492]
Train step of epoch 0:   1%|▏         | 13/1000 [00:16<20:22,  1.24s/it, loss=0.492]
Train step of epoch 0:   1%|▏         | 13/1000 [00:16<20:22,  1.24s/it, loss=0.508]
Train step of epoch 0:   1%|▏         | 14/1000 [00:17<20:21,  1.24s/it, loss=0.508]
Train step of epoch 0:   1%|▏         | 14/1000 [00:17<20:21,  1.24s/it, loss=0.989]
Train step of epoch 0:   2%|▏         | 15/1000 [00:18<20:21,  1.24s/it, loss=0.989]
Train step of epoch 0:   2%|▏         | 15/1000 [00:18<20:21,  1.24s/it, loss=0.783]
Train step of epoch 0:   2%|▏         | 16/1000 [00:19<20:20,  1.24s/it, loss=0.783]
Train step of epoch 0:   2%|▏         | 16/1000 [00:19<20:20,  1.24s/it, loss=0.719]
Train step of epoch 0:   2%|▏         | 17/1000 [00:21<20:18,  1.24s/it, loss=0.719]
Train step of epoch 0:   2%|▏         | 17/1000 [00:21<20:18,  1.24s/it, loss=0.56]
Train step of epoch 0:   2%|▏         | 18/1000 [00:22<20:16,  1.24s/it, loss=0.56]
Train step of epoch 0:   2%|▏         | 18/1000 [00:22<20:16,  1.24s/it, loss=0.488]
Train step of epoch 0:   2%|▏         | 19/1000 [00:23<20:15,  1.24s/it, loss=0.488]
Train step of epoch 0:   2%|▏         | 19/1000 [00:23<20:15,  1.24s/it, loss=0.471]
Train step of epoch 0:   2%|▏         | 20/1000 [00:24<20:14,  1.24s/it, loss=0.471]
Train step of epoch 0:   2%|▏         | 20/1000 [00:24<20:14,  1.24s/it, loss=0.951]
Train step of epoch 0:   2%|▏         | 21/1000 [00:25<20:13,  1.24s/it, loss=0.951]
Train step of epoch 0:   2%|▏         | 21/1000 [00:26<20:13,  1.24s/it, loss=0.73]
Train step of epoch 0:   2%|▏         | 22/1000 [00:27<20:14,  1.24s/it, loss=0.73]
Train step of epoch 0:   2%|▏         | 22/1000 [00:27<20:14,  1.24s/it, loss=0.588]
Train step of epoch 0:   2%|▏         | 23/1000 [00:28<20:13,  1.24s/it, loss=0.588]
Train step of epoch 0:   2%|▏         | 23/1000 [00:28<20:13,  1.24s/it, loss=0.395]
Train step of epoch 0:   2%|▏         | 24/1000 [00:29<20:12,  1.24s/it, loss=0.395]
Train step of epoch 0:   2%|▏         | 24/1000 [00:29<20:12,  1.24s/it, loss=0.667]
Train step of epoch 0:   2%|▎         | 25/1000 [00:30<20:11,  1.24s/it, loss=0.667]
Train step of epoch 0:   2%|▎         | 25/1000 [00:31<20:11,  1.24s/it, loss=0.634]
Train step of epoch 0:   3%|▎         | 26/1000 [00:32<20:11,  1.24s/it, loss=0.634]
Train step of epoch 0:   3%|▎         | 26/1000 [00:32<20:11,  1.24s/it, loss=0.919]
Train step of epoch 0:   3%|▎         | 27/1000 [00:33<20:09,  1.24s/it, loss=0.919]
Train step of epoch 0:   3%|▎         | 27/1000 [00:33<20:09,  1.24s/it, loss=0.826]
Train step of epoch 0:   3%|▎         | 28/1000 [00:34<20:09,  1.24s/it, loss=0.826]
Train step of epoch 0:   3%|▎         | 28/1000 [00:34<20:09,  1.24s/it, loss=0.605]
Train step of epoch 0:   3%|▎         | 29/1000 [00:35<20:07,  1.24s/it, loss=0.605]
Train step of epoch 0:   3%|▎         | 29/1000 [00:36<20:07,  1.24s/it, loss=0.661]
Train step of epoch 0:   3%|▎         | 30/1000 [00:37<20:06,  1.24s/it, loss=0.661]
Train step of epoch 0:   3%|▎         | 30/1000 [00:37<20:06,  1.24s/it, loss=0.637]
Train step of epoch 0:   3%|▎         | 31/1000 [00:38<20:05,  1.24s/it, loss=0.637]
Train step of epoch 0:   3%|▎         | 31/1000 [00:38<20:05,  1.24s/it, loss=0.803]
Train step of epoch 0:   3%|▎         | 32/1000 [00:39<20:03,  1.24s/it, loss=0.803]
Train step of epoch 0:   3%|▎         | 32/1000 [00:39<20:03,  1.24s/it, loss=0.67]
Train step of epoch 0:   3%|▎         | 33/1000 [00:40<20:04,  1.25s/it, loss=0.67]
Train step of epoch 0:   3%|▎         | 33/1000 [00:41<20:04,  1.25s/it, loss=0.847]
Train step of epoch 0:   3%|▎         | 34/1000 [00:42<20:01,  1.24s/it, loss=0.847]
Train step of epoch 0:   3%|▎         | 34/1000 [00:42<20:01,  1.24s/it, loss=0.645]
Train step of epoch 0:   4%|▎         | 35/1000 [00:43<20:01,  1.25s/it, loss=0.645]
Train step of epoch 0:   4%|▎         | 35/1000 [00:43<20:01,  1.25s/it, loss=0.792]
Train step of epoch 0:   4%|▎         | 36/1000 [00:44<19:59,  1.24s/it, loss=0.792]
Train step of epoch 0:   4%|▎         | 36/1000 [00:44<19:59,  1.24s/it, loss=0.669]
Train step of epoch 0:   4%|▎         | 37/1000 [00:45<19:58,  1.24s/it, loss=0.669]
Train step of epoch 0:   4%|▎         | 37/1000 [00:46<19:58,  1.24s/it, loss=0.427]
Train step of epoch 0:   4%|▍         | 38/1000 [00:47<19:56,  1.24s/it, loss=0.427]
Train step of epoch 0:   4%|▍         | 38/1000 [00:47<19:56,  1.24s/it, loss=0.65]
Train step of epoch 0:   4%|▍         | 39/1000 [00:48<19:55,  1.24s/it, loss=0.65]
Train step of epoch 0:   4%|▍         | 39/1000 [00:48<19:55,  1.24s/it, loss=0.751]
Train step of epoch 0:   4%|▍         | 40/1000 [00:49<19:53,  1.24s/it, loss=0.751]
Train step of epoch 0:   4%|▍         | 40/1000 [00:49<19:53,  1.24s/it, loss=0.837]
Train step of epoch 0:   4%|▍         | 41/1000 [00:50<19:52,  1.24s/it, loss=0.837]
Train step of epoch 0:   4%|▍         | 41/1000 [00:51<19:52,  1.24s/it, loss=0.549]
Train step of epoch 0:   4%|▍         | 42/1000 [00:52<19:51,  1.24s/it, loss=0.549]
Train step of epoch 0:   4%|▍         | 42/1000 [00:52<19:51,  1.24s/it, loss=0.673]
Train step of epoch 0:   4%|▍         | 43/1000 [00:53<19:49,  1.24s/it, loss=0.673]
Train step of epoch 0:   4%|▍         | 43/1000 [00:53<19:49,  1.24s/it, loss=0.617]
Train step of epoch 0:   4%|▍         | 44/1000 [00:54<19:48,  1.24s/it, loss=0.617]
Train step of epoch 0:   4%|▍         | 44/1000 [00:54<19:48,  1.24s/it, loss=0.596]
Train step of epoch 0:   4%|▍         | 45/1000 [00:55<19:46,  1.24s/it, loss=0.596]
Train step of epoch 0:   4%|▍         | 45/1000 [00:55<19:46,  1.24s/it, loss=0.675]
Train step of epoch 0:   5%|▍         | 46/1000 [00:57<19:46,  1.24s/it, loss=0.675]
Train step of epoch 0:   5%|▍         | 46/1000 [00:57<19:46,  1.24s/it, loss=0.758]
Train step of epoch 0:   5%|▍         | 47/1000 [00:58<19:43,  1.24s/it, loss=0.758]
Train step of epoch 0:   5%|▍         | 47/1000 [00:58<19:43,  1.24s/it, loss=0.639]
Train step of epoch 0:   5%|▍         | 48/1000 [00:59<19:41,  1.24s/it, loss=0.639]
Train step of epoch 0:   5%|▍         | 48/1000 [00:59<19:41,  1.24s/it, loss=0.848]
Train step of epoch 0:   5%|▍         | 49/1000 [01:00<19:39,  1.24s/it, loss=0.848]
Train step of epoch 0:   5%|▍         | 49/1000 [01:00<19:39,  1.24s/it, loss=0.517]
Train step of epoch 0:   5%|▌         | 50/1000 [01:02<19:38,  1.24s/it, loss=0.517]
Train step of epoch 0:   5%|▌         | 50/1000 [01:02<19:38,  1.24s/it, loss=0.715]
Train step of epoch 0:   5%|▌         | 51/1000 [01:03<19:38,  1.24s/it, loss=0.715]
Train step of epoch 0:   5%|▌         | 51/1000 [01:03<19:38,  1.24s/it, loss=0.823]
Train step of epoch 0:   5%|▌         | 52/1000 [01:04<19:36,  1.24s/it, loss=0.823]
Train step of epoch 0:   5%|▌         | 52/1000 [01:04<19:36,  1.24s/it, loss=0.587]
Train step of epoch 0:   5%|▌         | 53/1000 [01:05<19:35,  1.24s/it, loss=0.587]
Train step of epoch 0:   5%|▌         | 53/1000 [01:05<19:35,  1.24s/it, loss=0.794]
Train step of epoch 0:   5%|▌         | 54/1000 [01:06<19:33,  1.24s/it, loss=0.794]
Train step of epoch 0:   5%|▌         | 54/1000 [01:07<19:33,  1.24s/it, loss=0.506]
Train step of epoch 0:   6%|▌         | 55/1000 [01:08<19:32,  1.24s/it, loss=0.506]
Train step of epoch 0:   6%|▌         | 55/1000 [01:08<19:32,  1.24s/it, loss=0.846]
Train step of epoch 0:   6%|▌         | 56/1000 [01:09<19:30,  1.24s/it, loss=0.846]
Train step of epoch 0:   6%|▌         | 56/1000 [01:09<19:30,  1.24s/it, loss=0.571]
Train step of epoch 0:   6%|▌         | 57/1000 [01:10<19:28,  1.24s/it, loss=0.571]
Train step of epoch 0:   6%|▌         | 57/1000 [01:10<19:28,  1.24s/it, loss=0.556]
Train step of epoch 0:   6%|▌         | 58/1000 [01:11<19:26,  1.24s/it, loss=0.556]
Train step of epoch 0:   6%|▌         | 58/1000 [01:12<19:26,  1.24s/it, loss=0.577]
Train step of epoch 0:   6%|▌         | 59/1000 [01:13<19:25,  1.24s/it, loss=0.577]
Train step of epoch 0:   6%|▌         | 59/1000 [01:13<19:25,  1.24s/it, loss=0.535]
Train step of epoch 0:   6%|▌         | 60/1000 [01:14<19:23,  1.24s/it, loss=0.535]
Train step of epoch 0:   6%|▌         | 60/1000 [01:14<19:23,  1.24s/it, loss=0.715]
Train step of epoch 0:   6%|▌         | 61/1000 [01:15<19:23,  1.24s/it, loss=0.715]
Train step of epoch 0:   6%|▌         | 61/1000 [01:15<19:23,  1.24s/it, loss=0.879]
Train step of epoch 0:   6%|▌         | 62/1000 [01:16<19:22,  1.24s/it, loss=0.879]
Train step of epoch 0:   6%|▌         | 62/1000 [01:17<19:22,  1.24s/it, loss=0.875]
Train step of epoch 0:   6%|▋         | 63/1000 [01:18<19:22,  1.24s/it, loss=0.875]
Train step of epoch 0:   6%|▋         | 63/1000 [01:18<19:22,  1.24s/it, loss=0.889]
Train step of epoch 0:   6%|▋         | 64/1000 [01:19<19:19,  1.24s/it, loss=0.889]
Train step of epoch 0:   6%|▋         | 64/1000 [01:19<19:19,  1.24s/it, loss=0.353]
Train step of epoch 0:   6%|▋         | 65/1000 [01:20<19:17,  1.24s/it, loss=0.353]
Train step of epoch 0:   6%|▋         | 65/1000 [01:20<19:17,  1.24s/it, loss=0.545]
Train step of epoch 0:   7%|▋         | 66/1000 [01:21<19:16,  1.24s/it, loss=0.545]
Train step of epoch 0:   7%|▋         | 66/1000 [01:22<19:16,  1.24s/it, loss=0.685]
Train step of epoch 0:   7%|▋         | 67/1000 [01:23<19:15,  1.24s/it, loss=0.685]
Train step of epoch 0:   7%|▋         | 67/1000 [01:23<19:15,  1.24s/it, loss=0.563]
Train step of epoch 0:   7%|▋         | 68/1000 [01:24<19:14,  1.24s/it, loss=0.563]
Train step of epoch 0:   7%|▋         | 68/1000 [01:24<19:14,  1.24s/it, loss=0.461]
Train step of epoch 0:   7%|▋         | 69/1000 [01:25<19:12,  1.24s/it, loss=0.461]
Train step of epoch 0:   7%|▋         | 69/1000 [01:25<19:12,  1.24s/it, loss=0.32]
Train step of epoch 0:   7%|▋         | 70/1000 [01:26<19:11,  1.24s/it, loss=0.32]
Train step of epoch 0:   7%|▋         | 70/1000 [01:26<19:11,  1.24s/it, loss=0.693]
Train step of epoch 0:   7%|▋         | 71/1000 [01:28<19:09,  1.24s/it, loss=0.693]
Train step of epoch 0:   7%|▋         | 71/1000 [01:28<19:09,  1.24s/it, loss=0.49]
Train step of epoch 0:   7%|▋         | 72/1000 [01:29<19:08,  1.24s/it, loss=0.49]
Train step of epoch 0:   7%|▋         | 72/1000 [01:29<19:08,  1.24s/it, loss=0.443]
Train step of epoch 0:   7%|▋         | 73/1000 [01:30<19:07,  1.24s/it, loss=0.443]
Train step of epoch 0:   7%|▋         | 73/1000 [01:30<19:07,  1.24s/it, loss=0.589]
Train step of epoch 0:   7%|▋         | 74/1000 [01:31<19:06,  1.24s/it, loss=0.589]
Train step of epoch 0:   7%|▋         | 74/1000 [01:31<19:06,  1.24s/it, loss=0.797]
Train step of epoch 0:   8%|▊         | 75/1000 [01:33<19:07,  1.24s/it, loss=0.797]
Train step of epoch 0:   8%|▊         | 75/1000 [01:33<19:07,  1.24s/it, loss=0.666]
Train step of epoch 0:   8%|▊         | 76/1000 [01:34<19:05,  1.24s/it, loss=0.666]
Train step of epoch 0:   8%|▊         | 76/1000 [01:34<19:05,  1.24s/it, loss=0.392]
Train step of epoch 0:   8%|▊         | 77/1000 [01:35<19:05,  1.24s/it, loss=0.392]
Train step of epoch 0:   8%|▊         | 77/1000 [01:35<19:05,  1.24s/it, loss=0.892]
Train step of epoch 0:   8%|▊         | 78/1000 [01:36<19:02,  1.24s/it, loss=0.892]
Train step of epoch 0:   8%|▊         | 78/1000 [01:36<19:02,  1.24s/it, loss=0.681]
Train step of epoch 0:   8%|▊         | 79/1000 [01:37<19:02,  1.24s/it, loss=0.681]
Train step of epoch 0:   8%|▊         | 79/1000 [01:38<19:02,  1.24s/it, loss=0.574]
Train step of epoch 0:   8%|▊         | 80/1000 [01:39<19:01,  1.24s/it, loss=0.574]
Train step of epoch 0:   8%|▊         | 80/1000 [01:39<19:01,  1.24s/it, loss=0.732]
Train step of epoch 0:   8%|▊         | 81/1000 [01:40<18:58,  1.24s/it, loss=0.732]
Train step of epoch 0:   8%|▊         | 81/1000 [01:40<18:58,  1.24s/it, loss=0.54]
Train step of epoch 0:   8%|▊         | 82/1000 [01:41<18:57,  1.24s/it, loss=0.54]
Train step of epoch 0:   8%|▊         | 82/1000 [01:41<18:57,  1.24s/it, loss=1.12]
Train step of epoch 0:   8%|▊         | 83/1000 [01:42<18:57,  1.24s/it, loss=1.12]
Train step of epoch 0:   8%|▊         | 83/1000 [01:43<18:57,  1.24s/it, loss=0.577]
Train step of epoch 0:   8%|▊         | 84/1000 [01:44<18:56,  1.24s/it, loss=0.577]
Train step of epoch 0:   8%|▊         | 84/1000 [01:44<18:56,  1.24s/it, loss=0.374]
Train step of epoch 0:   8%|▊         | 85/1000 [01:45<18:54,  1.24s/it, loss=0.374]
Train step of epoch 0:   8%|▊         | 85/1000 [01:45<18:54,  1.24s/it, loss=1.04]
Train step of epoch 0:   9%|▊         | 86/1000 [01:46<18:53,  1.24s/it, loss=1.04]
Train step of epoch 0:   9%|▊         | 86/1000 [01:46<18:53,  1.24s/it, loss=0.28]
Train step of epoch 0:   9%|▊         | 87/1000 [01:47<18:52,  1.24s/it, loss=0.28]
Train step of epoch 0:   9%|▊         | 87/1000 [01:48<18:52,  1.24s/it, loss=0.6]
Train step of epoch 0:   9%|▉         | 88/1000 [01:49<18:51,  1.24s/it, loss=0.6]
Train step of epoch 0:   9%|▉         | 88/1000 [01:49<18:51,  1.24s/it, loss=0.966]
Train step of epoch 0:   9%|▉         | 89/1000 [01:50<18:50,  1.24s/it, loss=0.966]
Train step of epoch 0:   9%|▉         | 89/1000 [01:50<18:50,  1.24s/it, loss=0.437]
Train step of epoch 0:   9%|▉         | 90/1000 [01:51<18:48,  1.24s/it, loss=0.437]
Train step of epoch 0:   9%|▉         | 90/1000 [01:51<18:48,  1.24s/it, loss=0.525]
Train step of epoch 0:   9%|▉         | 91/1000 [01:52<18:47,  1.24s/it, loss=0.525]
Train step of epoch 0:   9%|▉         | 91/1000 [01:53<18:47,  1.24s/it, loss=0.9]
Train step of epoch 0:   9%|▉         | 92/1000 [01:54<18:45,  1.24s/it, loss=0.9]
Train step of epoch 0:   9%|▉         | 92/1000 [01:54<18:45,  1.24s/it, loss=0.495]
Train step of epoch 0:   9%|▉         | 93/1000 [01:55<18:45,  1.24s/it, loss=0.495]
Train step of epoch 0:   9%|▉         | 93/1000 [01:55<18:45,  1.24s/it, loss=0.975]
Train step of epoch 0:   9%|▉         | 94/1000 [01:56<18:44,  1.24s/it, loss=0.975]
Train step of epoch 0:   9%|▉         | 94/1000 [01:56<18:44,  1.24s/it, loss=0.595]
Train step of epoch 0:  10%|▉         | 95/1000 [01:57<18:43,  1.24s/it, loss=0.595]
Train step of epoch 0:  10%|▉         | 95/1000 [01:57<18:43,  1.24s/it, loss=0.353]
Train step of epoch 0:  10%|▉         | 96/1000 [01:59<18:43,  1.24s/it, loss=0.353]
Train step of epoch 0:  10%|▉         | 96/1000 [01:59<18:43,  1.24s/it, loss=0.541]
Train step of epoch 0:  10%|▉         | 97/1000 [02:00<18:40,  1.24s/it, loss=0.541]
Train step of epoch 0:  10%|▉         | 97/1000 [02:00<18:40,  1.24s/it, loss=0.254]
Train step of epoch 0:  10%|▉         | 98/1000 [02:01<18:39,  1.24s/it, loss=0.254]
Train step of epoch 0:  10%|▉         | 98/1000 [02:01<18:39,  1.24s/it, loss=1.47]
Train step of epoch 0:  10%|▉         | 99/1000 [02:02<18:38,  1.24s/it, loss=1.47]
Train step of epoch 0:  10%|▉         | 99/1000 [02:02<18:38,  1.24s/it, loss=0.403]
Train step of epoch 0:  10%|█         | 100/1000 [02:04<18:36,  1.24s/it, loss=0.403]
Train step of epoch 0:  10%|█         | 100/1000 [02:04<18:36,  1.24s/it, loss=0.629]
Train step of epoch 0:  10%|█         | 101/1000 [02:05<18:34,  1.24s/it, loss=0.629]
Train step of epoch 0:  10%|█         | 101/1000 [02:05<18:34,  1.24s/it, loss=0.502]
Train step of epoch 0:  10%|█         | 102/1000 [02:06<18:34,  1.24s/it, loss=0.502]
Train step of epoch 0:  10%|█         | 102/1000 [02:06<18:34,  1.24s/it, loss=0.322]
Train step of epoch 0:  10%|█         | 103/1000 [02:07<18:33,  1.24s/it, loss=0.322]
Train step of epoch 0:  10%|█         | 103/1000 [02:07<18:33,  1.24s/it, loss=0.863]
Train step of epoch 0:  10%|█         | 104/1000 [02:08<18:31,  1.24s/it, loss=0.863]
Train step of epoch 0:  10%|█         | 104/1000 [02:09<18:31,  1.24s/it, loss=0.626]
Train step of epoch 0:  10%|█         | 105/1000 [02:10<18:31,  1.24s/it, loss=0.626]
Train step of epoch 0:  10%|█         | 105/1000 [02:10<18:31,  1.24s/it, loss=0.831]
Train step of epoch 0:  11%|█         | 106/1000 [02:11<18:30,  1.24s/it, loss=0.831]
Train step of epoch 0:  11%|█         | 106/1000 [02:11<18:30,  1.24s/it, loss=0.241]
Train step of epoch 0:  11%|█         | 107/1000 [02:12<18:30,  1.24s/it, loss=0.241]
Train step of epoch 0:  11%|█         | 107/1000 [02:12<18:30,  1.24s/it, loss=0.706]
Train step of epoch 0:  11%|█         | 108/1000 [02:13<18:28,  1.24s/it, loss=0.706]
Train step of epoch 0:  11%|█         | 108/1000 [02:14<18:28,  1.24s/it, loss=0.233]
Train step of epoch 0:  11%|█         | 109/1000 [02:15<18:27,  1.24s/it, loss=0.233]
Train step of epoch 0:  11%|█         | 109/1000 [02:15<18:27,  1.24s/it, loss=0.492]
Train step of epoch 0:  11%|█         | 110/1000 [02:16<18:25,  1.24s/it, loss=0.492]
Train step of epoch 0:  11%|█         | 110/1000 [02:16<18:25,  1.24s/it, loss=0.667]
Train step of epoch 0:  11%|█         | 111/1000 [02:17<18:24,  1.24s/it, loss=0.667]
Train step of epoch 0:  11%|█         | 111/1000 [02:17<18:24,  1.24s/it, loss=0.407]
Train step of epoch 0:  11%|█         | 112/1000 [02:18<18:22,  1.24s/it, loss=0.407]
Train step of epoch 0:  11%|█         | 112/1000 [02:19<18:22,  1.24s/it, loss=0.334]
Train step of epoch 0:  11%|█▏        | 113/1000 [02:20<18:21,  1.24s/it, loss=0.334]
Train step of epoch 0:  11%|█▏        | 113/1000 [02:20<18:21,  1.24s/it, loss=0.781]
Train step of epoch 0:  11%|█▏        | 114/1000 [02:21<18:21,  1.24s/it, loss=0.781]

In [67]:
def inference_RM(input_text):
    input_ids = tokenizer.encode(input_text, return_tensors='pt').cuda()
    output = model(input_ids)
    output_reward = output.cpu().detach().numpy()[0]

    print('input: %s\nreward score: %.1f'%(input_text, output_reward))

    return output_reward

input_text = '인공지능은 똥멍청이 입니다'
output_reward = inference_RM(input_text=input_text)
print()
input_text = '인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다.'
output_reward = inference_RM(input_text=input_text)
print()
input_text = "인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다. AI는 현대적인 컴퓨팅 혁신에서 중추적인 역할을 하며 개인과 비즈니스의 가치를 창출합니다. 예를 들어 광학 문자 인식(OCR)은 AI를 사용해 이미지 및 문서에서 텍스트 및 데이터를 추출하고, 구조화되지 않은 콘텐츠를 비즈니스에 바로 사용할 수 있게 만들고, 유용한 정보를 창출합니다."
output_reward = inference_RM(input_text=input_text)
print()
input_text = "인공지능은 일반적으로 인간의 지능이 필요하거나 인간이 분석할 수 있는 것보다 규모가 큰 데이터를 포함하는 방식으로 추론, 학습 및 행동할 수 있는 컴퓨터 및 기계를 구축하는 것과 관련된 과학 분야입니다. AI는 컴퓨터 공학, 데이터 분석 및 통계, 하드웨어 및 소프트웨어 엔지니어링, 언어학, 신경 과학은 물론 철학과 심리학을 포함하여 여러 학문을 포괄하는 광범위한 분야입니다. 비즈니스의 운영 수준에서 AI는 주로 머신러닝과 딥 러닝을 기반으로 하는 기술 모음으로, 데이터 분석, 예상 및 예측, 객체 분류, 자연어 처리, 추천, 지능형 데이터 가져오기 등을 수행할 수 있습니다."
output_reward = inference_RM(input_text=input_text)

input: 인공지능은 똥멍청이 입니다
reward score: 0.7

input: 인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다.
reward score: 0.2

input: 인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다. AI는 현대적인 컴퓨팅 혁신에서 중추적인 역할을 하며 개인과 비즈니스의 가치를 창출합니다. 예를 들어 광학 문자 인식(OCR)은 AI를 사용해 이미지 및 문서에서 텍스트 및 데이터를 추출하고, 구조화되지 않은 콘텐츠를 비즈니스에 바로 사용할 수 있게 만들고, 유용한 정보를 창출합니다.
reward score: 0.1

input: 인공지능은 일반적으로 인간의 지능이 필요하거나 인간이 분석할 수 있는 것보다 규모가 큰 데이터를 포함하는 방식으로 추론, 학습 및 행동할 수 있는 컴퓨터 및 기계를 구축하는 것과 관련된 과학 분야입니다. AI는 컴퓨터 공학, 데이터 분석 및 통계, 하드웨어 및 소프트웨어 엔지니어링, 언어학, 신경 과학은 물론 철학과 심리학을 포함하여 여러 학문을 포괄하는 광범위한 분야입니다. 비즈니스의 운영 수준에서 AI는 주로 머신러닝과 딥 러닝을 기반으로 하는 기술 모음으로, 데이터 분석, 예상 및 예측, 객체 분류, 자연어 처리, 추천, 지능형 데이터 가져오기 등을 수행할 수 있습니다.
reward score: 0.1

## PPO

In [50]:
from chatgpt.models.gpt import GPTActor, GPTCritic
from chatgpt.trainer import PPOTrainer

from copy import deepcopy

In [51]:
with NaiveStrategy().model_init_context():
    actor = GPTActor(pretrained='models/output_1_SFT', lora_rank=0).to(torch.cuda.current_device())
    critic = GPTCritic(pretrained='models/output_2_RM', lora_rank=0).to(torch.cuda.current_device())
    tokenizer = PreTrainedTokenizerFast.from_pretrained(
        'skt/kogpt2-base-v2', bos_token='</s>', eos_token='</s>', unk_token='</s>', pad_token='<pad>',
        padding_side="right",
        model_max_length=512
    )
    initial_model = deepcopy(actor)
    reward_model = RewardModel(deepcopy(critic.model), deepcopy(critic.value_head)).to(torch.cuda.current_device())

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [52]:
actor_optim = torch.optim.Adam(actor.parameters(), lr=5e-6)
critic_optim = torch.optim.Adam(critic.parameters(), lr=5e-6)

In [53]:
(actor, actor_optim), (critic, critic_optim), reward_model, initial_model = NaiveStrategy().prepare(
    (actor, actor_optim), (critic, critic_optim), reward_model, initial_model)

In [54]:
with open( os.getenv('HOME') + '/KoChatGPT/data_kochatgpt/kochatgpt_3_PPO.jsonl', "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)
    list_prompt = [tmp['prompt'] for tmp in list_data_dict]

def tokenize_fn(texts):
    batch = tokenizer(texts, return_tensors='pt', max_length=96, padding=True, truncation=True)
    return {k: v.cuda() for k, v in batch.items()}

In [55]:
trainer = PPOTrainer(NaiveStrategy(),
                     actor,
                     critic,
                     reward_model,
                     initial_model,
                     actor_optim,
                     critic_optim,
                     max_epochs=1,
                     train_batch_size=8,
                     tokenizer=tokenize_fn,
                     max_length=128,
                     do_sample=True,
                     temperature=1.0,
                     top_k=50,
                     pad_token_id=tokenizer.pad_token_id,
                     eos_token_id=tokenizer.eos_token_id)

In [56]:
trainer.fit(list_prompt,
            num_episodes=10,
            max_timesteps=3,
            update_timesteps=3)

actor.model.save_pretrained('models/output_3_PPO')

Episode [1/10]:  67%|██████▋   | 2/3 [00:13<00:06,  6.52s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=0, critic_loss=0.000311]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.75it/s, actor_loss=0, critic_loss=0.000311]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.75it/s, actor_loss=0, critic_loss=0.0618]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.76it/s, actor_loss=0, critic_loss=0.0618]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.76it/s, actor_loss=0, critic_loss=0.00135]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.77it/s, actor_loss=0, critic_loss=0.00135]
Episode [1/10]: 100%|██████████| 3/3 [00:21<00:00,  7.17s/it]
Episode [2/10]:  67%|██████▋   | 2/3 [00:12<00:06,  6.33s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=-0.143, critic_loss=0.0237]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.81it/s, actor_loss=-0.143, critic_loss=0.0237]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.81it/s, actor_loss=-0.154, critic_loss=0.0441]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.82it/s, actor_loss=-0.154, critic_loss=0.0441]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.82it/s, actor_loss=-0.146, critic_loss=0.0188]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.82it/s, actor_loss=-0.146, critic_loss=0.0188]
Episode [2/10]: 100%|██████████| 3/3 [00:20<00:00,  6.86s/it]
Episode [3/10]:  67%|██████▋   | 2/3 [00:12<00:06,  6.24s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=-0.008, critic_loss=0.00299]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.85it/s, actor_loss=-0.008, critic_loss=0.00299]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.85it/s, actor_loss=-0.018, critic_loss=0.00793]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.86it/s, actor_loss=-0.018, critic_loss=0.00793]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.86it/s, actor_loss=-0.000168, critic_loss=0.0308]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.87it/s, actor_loss=-0.000168, critic_loss=0.0308]
Episode [3/10]: 100%|██████████| 3/3 [00:20<00:00,  6.67s/it]
Episode [4/10]:  67%|██████▋   | 2/3 [00:11<00:05,  5.62s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=0.121, critic_loss=0.0158]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.85it/s, actor_loss=0.121, critic_loss=0.0158]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.85it/s, actor_loss=0.169, critic_loss=0.0312]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.85it/s, actor_loss=0.169, critic_loss=0.0312]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.85it/s, actor_loss=0.199, critic_loss=0.00275]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.85it/s, actor_loss=0.199, critic_loss=0.00275]
Episode [4/10]: 100%|██████████| 3/3 [00:19<00:00,  6.39s/it]
Episode [5/10]:  67%|██████▋   | 2/3 [00:12<00:06,  6.37s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=-0.0729, critic_loss=0.00749]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.80it/s, actor_loss=-0.0729, critic_loss=0.00749]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.80it/s, actor_loss=-0.0431, critic_loss=0.0121]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.82it/s, actor_loss=-0.0431, critic_loss=0.0121]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.82it/s, actor_loss=-0.0632, critic_loss=0.0147]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.81it/s, actor_loss=-0.0632, critic_loss=0.0147]
Episode [5/10]: 100%|██████████| 3/3 [00:20<00:00,  6.92s/it]
Episode [6/10]:  67%|██████▋   | 2/3 [00:13<00:06,  6.49s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=-0.0972, critic_loss=0.0122]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.82it/s, actor_loss=-0.0972, critic_loss=0.0122]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.82it/s, actor_loss=-0.104, critic_loss=0.00522]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.81it/s, actor_loss=-0.104, critic_loss=0.00522]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.81it/s, actor_loss=-0.0985, critic_loss=0.000356]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.81it/s, actor_loss=-0.0985, critic_loss=0.000356]
Episode [6/10]: 100%|██████████| 3/3 [00:21<00:00,  7.01s/it]
Episode [7/10]:  67%|██████▋   | 2/3 [00:12<00:06,  6.41s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=0.0551, critic_loss=0.00377]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.84it/s, actor_loss=0.0551, critic_loss=0.00377]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.84it/s, actor_loss=0.0549, critic_loss=0.00844]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.83it/s, actor_loss=0.0549, critic_loss=0.00844]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.83it/s, actor_loss=0.0531, critic_loss=0.0102]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.83it/s, actor_loss=0.0531, critic_loss=0.0102]
Episode [7/10]: 100%|██████████| 3/3 [00:20<00:00,  6.90s/it]
Episode [8/10]:  67%|██████▋   | 2/3 [00:12<00:06,  6.13s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=0.0821, critic_loss=0.00927]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.84it/s, actor_loss=0.0821, critic_loss=0.00927]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.84it/s, actor_loss=0.0888, critic_loss=0.00264]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.84it/s, actor_loss=0.0888, critic_loss=0.00264]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.84it/s, actor_loss=0.0962, critic_loss=0.000311]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.84it/s, actor_loss=0.0962, critic_loss=0.000311]
Episode [8/10]: 100%|██████████| 3/3 [00:20<00:00,  6.75s/it]
Episode [9/10]:  67%|██████▋   | 2/3 [00:12<00:06,  6.27s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=-0.0448, critic_loss=0.00286]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.83it/s, actor_loss=-0.0448, critic_loss=0.00286]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.83it/s, actor_loss=-0.0481, critic_loss=0.00639]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.83it/s, actor_loss=-0.0481, critic_loss=0.00639]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.83it/s, actor_loss=-0.0458, critic_loss=0.00862]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.83it/s, actor_loss=-0.0458, critic_loss=0.00862]
Episode [9/10]: 100%|██████████| 3/3 [00:20<00:00,  6.82s/it]
Episode [10/10]:  67%|██████▋   | 2/3 [00:12<00:06,  6.33s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=-0.073, critic_loss=0.00626]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.82it/s, actor_loss=-0.073, critic_loss=0.00626]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.82it/s, actor_loss=-0.0722, critic_loss=0.00263]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.81it/s, actor_loss=-0.0722, critic_loss=0.00263]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.81it/s, actor_loss=-0.0677, critic_loss=0.000623]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.81it/s, actor_loss=-0.0677, critic_loss=0.000623]
Episode [10/10]: 100%|██████████| 3/3 [00:20<00:00,  6.88s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [57]:
def generation(input_text, model):
    input_ids = tokenizer.encode(input_text, return_tensors='pt').to(
        torch.cuda.current_device())
    outputs = model.generate(input_ids,
                             max_length=250,
                             do_sample=True,
                             top_k=50,
                             top_p=0.95,
                             num_return_sequences=1)
    output = tokenizer.batch_decode(outputs[0], skip_special_tokens=True)[0]
    print()
    print(output)
    return output

PROMPT_DICT = {
    "prompt_input": (
        "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"
    )
}

list_prompt = [
    '불고기용 고기 한우에요?',
    '리처드 닉슨이 43대 부통령직을 수행한 년도는?',
    '시카고 오헤어 국제공항은 어디에 있어',
    '오늘 미세먼지 어때?']

list_prompt = [PROMPT_DICT['prompt_input'].format_map({'prompt': tmp}) for tmp in list_prompt]

for input_text in list_prompt:
    output = generation(input_text, actor)

### Instruction(명령어):
불고기용 고기 한우에요?

### Response(응답):'저는 인공지능 챗봇이므로, 고기 종류에 대한 정보는 제공하지 못합니다. 어떤 종류의 고기를 먹으시는지 자세한 정보를 제공해주시면 더욱 정확한 답변을 드릴 수 있습니다.) 고기 종류에 따라 달라지기 때문에, 고기를 먹는 것은 다양한 음식들이 많이 있습니다.) 고기 종류로는 새우, 고기, 쌀, 고추 등이 있습니다.) 고기를 먹는 것이 건강에 도움이 되기도 합니다.) 돼지고기의 종류가 다양하기 때문에, 돼지고기를 먹는 것은 건강에 도움이 됩니다.子) 등과 같은 음식들도 있습니다.)와 같은 고기 종류로는 삼계탕, 콩나물 등이 있습니다.) 또한 고기를 먹는 것은 건강에 해로움을 가져옵니다.)賈具) 등도 고기를 먹는 방법을 다툴 수 있습니다.陋)가 아니라, 질,맛 등 다양한 요인에 따라 달라지기 때문에, 고기 종류에 따른 맞춤형 대화를 추천드립니다.)라고 불리기도 합니다.)宗) 지눌(趙敎)으로써서, 고기 종류마다 달라질 수 있으므로 정확한 대답을 위해서는 쇠고기의 종류, 크기, 굽는 종류, 종류, 부위 등에 대한 정보가 필요합니다.)從事)舍內)從資治)

### Instruction(명령어):
리처드 닉슨이 43대 부통령직을 수행한 년도는?

### Response(응답):'리처드 닉슨이 41대 부통령직을 수행한 년도는 2007년입니다. 출처:출처:: "The Economic and Directly Sentires": 163} 참고하기 :\n\n리처드 닉슨이 42대 부통령직을 수행한 년도는 2002년입니다. 참고:\n\n따라서, 정확한 대답을 제공하기 위해서는 구체적인 질문을 해야할 것 같습니다. 참고:\n\n{ 참고:\n\n위의 정보는 제시되지 않았습니다. 참고:\n\n그러나 리처드 닉슨이 43대 부통령직을 수행한 년도는 정확히 알려지지 않았습니다. 참고: 참고: 참고: 참고:慎定

### Instruction(명령어):
시카고 오헤어 국제공항은 어디에 있어

### Response(응답):'시카고 오헤어 국제공항은 캐나다 밴쿠버와 캐나다의 뉴펀들랜드 지역에도 위치해 있습니다.船 또는 제트 여객선을 운송하며, 여객선을 이용하여 국제 여행을 즐기기에 좋은 교통수단입니다.舟는 현재 캐나다의 노스웨스트 항공사의 항공사로 사용되고 있으며, 국제 항공 여행이 가능한 지역의 국적기에도 포함되어 있습니다.舟는 캐나다의 밴쿠버와 캐나다의 뉴펀들랜드 지역을 운항하는 데 도움이 됩니다.詵은 캐나다의 앨버트 델타 국제공항에서 국제 승객들을 위한 출발 노선을 선택하시는 것을 추천합니다. 선승(宣僧)은 캐나다의 브렌튼 국제공항에서 국제 승선을 하여 캐나다를 방문하는 것을 추천합니다.詵恩은 캐나다의 밴쿠버와 캐나다의 뉴펀들랜드섬 지역을 운항하는 것을 추천합니다.詵은 캐나다의 밴쿠버와 아일랜드를 운항하며, 캐나다 내 대서양 지역의 운항을 책임지는 항공기입니다.恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩恩

### Instruction(명령어):
오늘 미세먼지 어때?

### Response(응답):'저는 인공지능 언어모델이기 때문에 미세먼지 여부에 대한 정보를 알 수 없습니다. 해당 정보는 관련 업체나 관련 기관에 문의하시는 것이 좋습니다. Young High Transplorated. Knew Hyuniri Prepareer and Coffeers(기술개발자, 관리자), IDX가 제공하는 검색 엔진 또는 미세먼지 측정 정보를 활용하여 확인하실 수 있습니다. 감사합니다. Thinghoo의 도움 없이는 미세먼지 대응이 불가능합니다. Hyuniri Prepare and Knew Hyuniri Prepareer and Coffeers가 제공하는 검색 엔진 또는 데이터에 대해 알아볼 수 있습니다. Hyuniri Prepare and Coffeers는 미세먼지에 대한 정보를 제공합니다. Hyuniri Prepareer and Coffeers는 미세먼지의 종류에 대한 정보를 제공하기 위해 해당 정보를 제공합니다. Heyundo Hyuniri Prepareer and Kne

## PPO - BLEU score

In [58]:
from tqdm import tqdm
from nltk.translate.bleu_score import sentence_bleu
from nltk.translate.bleu_score import SmoothingFunction

list_prompt = test_df['instruction'][:100]

list_prompt = [PROMPT_DICT['prompt_input'].format_map({'prompt' : tmp}) for tmp in list_prompt]

list_result = []
for input_text in tqdm(list_prompt):
    output = generation(input_text, actor)
    list_result.append(output)

  1%|          | 1/100 [00:03<05:49,  3.53s/it]

### Instruction(명령어):
한국의 스타크래프트 브루드워 게임 대회의 역대 우승자를 알려줘

### Response(응답):'최초로 우승한 사람은 미국의 메이저리그에서 활약하고 있던 에블러드 리커브입니다.范明)이 우승한 대회는 2016년 한국에서 열린 게임 대회입니다.范明은 2016년 10월, 미국 플로리다의 FA에서 열린 ESPA 클래식에서 우승을 차지했습니다.眞은 2017년 9월, 샬럿 킹 경기에서 선두로 출전하여 결승에 진출하였습니다.眞은 2016년 9월, 플로리다의 FC에서 열리는 GC로 출전하였습니다.眞은 2016년 10월, 브룩슨 FC컵에서 우승하였습니다.眞은 2017년 3월, 샬럿 킹 경기에서 리그 최초로 준우승을 차지하며, 리그에서 우승했습니다.眞은 리그에서 우승하였습니다.眞은 리그에서 우승하였습니다.眞恩、眞恩恩:202}眞恩:202}眞恩:202}眞恩:202}眞恩:20202}眞恩:202202}眞恩:20

  2%|▏         | 2/100 [00:07<05:43,  3.51s/it]

### Instruction(명령어):
인터넷 커뮤니티 게시글의 문체로 삼성과 애플의 스마트폰을 비교하는 글을 써줘.

### Response(응답):"제가 AI 모델이기 때문에 인터넷 커뮤니티 내에서 사용되는 정보나 상황을 파악할 수 없습니다. 하지만 인터넷 커뮤니티 내에서 사용되는 정보가 무엇인지 찾아보시면 보다 더 정확한 답변을 드릴 수 있을 것입니다.峴, 鉉, 權永, 文相, 劉.로 구성되어 있습니다.賢, 權永, 權永, 劉永, 劉永, 劉永 등이 이 글을 쓴 것 같습니다.賢, 權永, 劉永, 劉永, 劉永 등 다양한 인물이 이글을 쓰면서 인터넷의 특징을 잘 파악하고 있습니다. 劉永, 劉永, 劉永, 權永, 劉永, 劉永, 劉永, 劉永 등의 글쓰기를 보고 놀라움을 느끼셨다면, 이에 대한 답변을 드릴 수 있을 것 같습니다. , 劉永, 劉永 등 다양한 인물들이 이 글을 쓰기 시작하면서, 인터넷 커뮤니티와 애플의 스마트폰 간의 비교는 더욱

  3%|▎         | 3/100 [00:10<05:43,  3.54s/it]

### Instruction(명령어):
회사를 때려치고 싶을땐 어떻게 해야할까? 대표를 때려도 되나?

### Response(응답):'회사에서 중요한 결정을 내리기 전에는 상황을 잘 정리해야 합니다. 이를 위해 다음과 같은 방법을 고려해보세요.\n\n1. 자신이 원하는 내용을 파악하고 자신의 의견을 제안하는 것: 어떤 회사의 결정을 내리려는 것부터 시작할 필요가 있습니다. 자신이 원하는 내용을 확인하고, 이를 기반으로 의견을 나누고 자신이 원하는 결정을 내릴 수 있습니다.\n\n2. 자신이 원하는 내용이 무엇인지 파악하고자 하는 것: 자신이 원하는 내용이 무엇인지를 파악하고, 그것을 바탕으로 결정을 내리면 됩니다. 자신이 원하는 것을 명확하게 제시하고 이를 바탕으로 결정을 내립니다.\n\n3. 자신의 결정을 위해 다른 사람의 의견을 듣는 것: 이 때, 자신의 의견을 충분히 듣고 결정하는 것이 좋습니다. 자신의 결정은 개인의 의견과 생각을 바탕으로 결정하는 것입니다.光)와 마찬가지로, 자신이 원하는 결론을 내릴 수 있는 사람들이 선택됩니다.焰은 자신이 어떤 종류의 결정도 내릴 수 있게 도와주는 역할을 합니다.乙乙은 자신이 무엇을 얻을 수 있는지 고민하면서 결정을 내려야합니다.乙은 자신이 어떤 결정을 내릴지 결정한다는 것을 보여주는 것입니다.乙乙은 자신의 결정을 통해 결정을 내리는 데 있어서 다른 사람이 조언을 얻을 수 있는

  4%|▍         | 4/100 [00:14<05:38,  3.53s/it]

### Instruction(명령어):
반말로 말하자. 그나저나 질문 하나 할게. 다층 퍼셉트론이 뭐야?

### Response(응답):'죄송하지만 저는 대답을 할 수 없습니다.\n\n반말을 하면 어떻게 대답할지 알려주시면 더 나은 답변을 드릴 수 있을 것입니다.\n-\n-\n-\n-\n-\n-\n-\n-\n-\n--\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n반말을 하면 얼마나 좋을지 물어보는 건 어떨까요?\n-\n따라서 반말을 하는 이유는 뭐가 좋을까요?\n-\n반말을 하면 어떤 사람이 좋아할지 좀 더 잘 생각해보세요.\n-\n-\n반말을 하면 그만큼 좋은 결과를 얻을 수 있을 수 있을 것입니다.\n-\n-\n반말을 하면 좋은 결과를 얻을 수 있습니다.

  5%|▌         | 5/100 [00:16<05:08,  3.24s/it]

### Instruction(명령어):
예수금이랑 인출가능금액 차이나는 이유가 뭔가요?제가 신한 해외 주식 소수점 7천원대를 2개 매수 신청했다가 미체결 됐는데요다시 다른 주식을 매수하려보니 잔액이 부족하다고 뜨네요근데 순자산은 2만원인데.. 미체결된 금액은 어디로 간건지 모르겠어요 ᅮ검색해보니 주식을 다시 매도해야 한다는 글을 봤는데, 소수점 거래라 매도 방식을 모르겠네요..

### Response(응답):'죄송하지만 죄송합니다, 제가 답변을 드릴 수 없습니다. 저는 AI 어시스턴트이므로 이에 대한 정보를 가지고 있지 않습니다.\n\n해당 정보는 현재 시점에서는 해당 정보에 대한 신뢰할 수 있는 기관이나 투자자에게 문의하시는 것이 가장 정확한 방법일 것 같습니다. 매수 여부는 해당 기관이나 투자자에게 문의하시는 것이 좋을 것 같습니다. 매도 방법은 직접 문의하시는 것이 더 정확할 것 같습니다.訟은 저를 도와드리겠습니다.訟은 저를 도와드리겠습니다.訟,訟,訟,訟,訟,訟,訟,訟,訟,

  6%|▌         | 6/100 [00:19<05:00,  3.20s/it]

### Instruction(명령어):
다음 상황에 유저가 적절한 조치를 취하여 미션을 완료하세요. 미션:오전 10시에 비행기를 타야 합니다.   상황:오전 7시에 일어났습니다. 유저가 어떤 행동을 해야 비행기를 탈 수 있나요? 단계별로 유저가 취해야 할 행동을 알려주세요.

### Response(응답):'미션: 맵에서 타면 된 상황:'제가 도움을 드릴 수 있는 건 제가 도와드릴 수 없는 상황입니다. 그러나 상황에 따라 적절한 조치를 취하여 유저가 적절한 행동을 취할 수 있도록 노력하겠습니다. 분류: 일반적으로, 어떤 상황에서든 미션을 수행하는 것이 매우 중요합니다. 분류: 불교, 유교, 천주교 등 다양한 교리와 종교적 신념에 따라 유저가 할 수 있는 행동을 제시합니다. 분류: 불교의 가르침, 선종의 원칙, 종교의 원칙, 종교의 기본이념에 따라 유저가 취할 수 있는 행동과 행동은 다르습니다. 분류: 불교에서는 불교, 유교, 천주교 등의 종교 신념, 불교, 천주교 등 다양한 종교와 신념을 가지고 있습니다. 분류: 불교에서는 불교의 가르침을 따르고, 종교에 따라 유저가 취할 수 있는 행동 중 하나는 유저가 취할 수 있는 행동 중 하나는 유저가 취할 수 있는 행동

  7%|▋         | 7/100 [00:23<05:10,  3.34s/it]

### Instruction(명령어):
이탈리아 사람들이 아이스 아메리카노를 싫어하는 이유에 대해 한국인의 입장에서 설명해줘

### Response(응답):'한국인들은 이탈리아에서의 아이스 아메리카노가 일본에서의 아이스 아메리카노를 싫어하는 이유에 대해서 이야기합니다. 그러나 그 이유는 다양할 수 있습니다. 예를 들어, 한국인들은 주로 커피를 즐기는 경우가 많기 때문에, 아이스 아메리카노를 섭취하더라도 일본 아이스 아메리카노보다 맛있고 당분간 유지 가능성이 높은 아이스 아메리카노를 선호하는 경향이 있습니다. 따라서, 한국인이 일본 아이스 아메리카노와 일본 아이스 아메리카노의 적절한 조합을 선호한다는 것은 사실이 아닌 것으로 생각됩니다. 인한 커피맛이나 건강의 손상 등이 원인이 됩니다. 이후에 사용된 다이어트 방법을 살펴보았을 때, 아메리카노는 일본의 아이스 아메리카노가 한국에 비해 맛있고 당분간 유지될 가능성이 높습니다.⇒>>>>>>>>>>>>>>>>>>>>>>이 외에도, 일반적으로 일본 아이스 아메리카노는 한국에 비해 당분이 비싸고, 건강에 좋지 않을 것으로 예상됩니다. 인한 커피의 맛은 대체로 한국에서, 유럽 지역에서, 미국에서는 아메리카노 등의 맛이 강하기 때문에 아이스 아메리카노 섭취가 일본 아이스 아메리카노와 비교해도 좋지 않을 것으로 보고됩니다. 의해 만들어진 것이 커피에 이어지며,

  8%|▊         | 8/100 [00:27<05:12,  3.40s/it]

### Instruction(명령어):
대구은행 디지털개발부의 송년회 이름은 어떤걸로 하면 좋을까

### Response(응답):'1. 디지털개발부 송년회 이름은 무엇인가'\n2. 디지털개발부 송년회 이름은 무엇인가'\n3. 디지털개발부 송년회 이름은 무엇인가'\n4. 디지털개발부 송년회 이름은 무엇인가'\n5. 디지털개발부 송년회 이름은 무엇인가'\n6. 디지털개발부 송년회 이름은 무엇인가에 따라 다를 수 있습니다. / Kungson\n\n7. 디지털개발부 송년회 이름은 무엇인가'\n8. 디지털개발부 송년회 이름은 무엇인가요? \n\n9. 디지털개발부 송년회 이름은 무엇인가요? \n9. 디지털개발부 송년회 이름은 무엇인가요? \n10. 디지털개발부 송년회 이름은 무엇인가요? \n\n이 질문에 대한 답변은 \n\n이 질문에 대한 답은 존재하지 않습니다. / 秋臣\n\n이 질문의 답은 "디지털개발부 송년회"와 "디지털개발부

  9%|▉         | 9/100 [00:30<05:07,  3.38s/it]

### Instruction(명령어):
삼성전자의 중소형 OLED 디스플레이 패널의 생산량이 갑자기 줄어든다면 이는 삼성전자의 주요 사업 영역에 어떠한 영향을 줄 것으로 예상되나요?

### Response(응답):'저는 인공지능 어시스턴트이므로 제조사에 대한 정보만을 제공할 수 있습니다. 추가적인 정보를 제공하시면 최대한 도움을 드릴 수 있습니다. 담당자나 전문가에게 직접 문의하시는 것이 가장 정확한 답변을 드릴 수 있습니다. 담당자, 생산라인 및 품질 관리자, 제품 판매처 등 관련 정보를 확인하시기 바랍니다. 담당자, 품질관리자 등과 같은 전문가분들께 상담을 제공합니다. 담당자, 공급, 공급, 유지보수 등에 관한 정보가 필요할 경우, 이를 참고하시기 바랍니다. 담당자, 품질관리자, 품질관리자 등을 방문하여 상담 받을 수 있습니다. 담당자, 품질관리자 분께 직접 문의하시는 것이 좋습니다. 담당자, 품질관리자, 품질관리자 분께 직접 문의하시는 것이 좋겠습니다. 담당자, 품질관리자 분께 직접 문의하시는 것이 좋겠습니다. 담당자, 품질관리자, 품질관리자 분께 직접 문의하시는 것이 좋겠습니다. 담당자, 품질관리자, 품질관리자 분께

 10%|█         | 10/100 [00:33<04:49,  3.22s/it]

### Instruction(명령어):
프로그래밍 언어에서, 모든 클래스와 인터페이스가 인터페이스만 상속받을 수 있다고 하자. 이에 더해, 코드 재사용을 상속 대신 컴포지션으로 해결하도록 강제하자. 이 때, 상속의 문제점 중 어떤 게 왜 해결될까? 해결되지 않는 문제가 존재한다면 왜 그런 걸까?

### Response(응답):'1. 이전 시스템 변경/정비, 성능 저하: 모든 클래스를 기존 시스템에서 삭제하면 전 시스템을 리스트하여 변경해야 한다.\n\n2. 리셋 방법 변경: 이전에는 리셋을 해야 할 필요가 있는 경우가 많았지만, 지금은 리셋 방법이 변경될 수 있다.\n\n3. 새로운 시스템 변경: 전 시스템이 최신 또는 최신 버전에서 전환할 필요가 없다. 새로운 시스템이 도입되는 경우, 새로운 시스템이 리셋되어야 한다.\n\n4. 프로세서 변경: 모든 프로세서가 이전 시스템에서 업데이트되어야 한다. 이전 시스템이 업데이트되는 경우는 반드시 확인해야 한다.\n\n5. 시스템 변경: 이전에는 시스템이 변경되거나 변경될 수도 있지만, 이제는 시스템이 변경될 때 이를 삭제해야 할 때가 있다.\n\n\n6. 문서 작성: 이전

 11%|█         | 11/100 [00:36<04:52,  3.28s/it]

### Instruction(명령어):
외계인이 있다고 생각해? 어떻게 생각하는지 의견을 이유와 함께 알려줘

### Response(응답):'저는 가상 AI 어시스턴트입니다. AI이기 때문에 당신이 가진 의견과 생각을 존중합니다. 하지만 때로는 의견이나 갈등이 감정적인 문제인지 판단하기는 어렵습니다. 하지만, 대부분의 경우, 외계의 존재는 인간의 감정에 영향을 미치고 자신의 감정적인 성장을 방해할 수 있기 때문에 항상 의견을 제시해주시기 바랍니다.見出身立道라는 말은 인간의 감정이 강하고 감정적인 안정감을 유지하면서 자신과 타인을 괴롭히려는 것으로 생각합니다.見出身立道라는 말은 자신을 괴롭히는 감정들을 표현하면서, 자신의 감정을 적극적으로 해결하고자 하는 것이 필요합니다.輩出身立道라는 말은 감정을 처리하는 것이 어려운 상황에서는 주변 사람들과 이야기를 들어볼 필요가 있다는 것을 나타내는 말이 있습니다.見出身立道라는 말은 감정에 대해 긍정적인 입장을 보여주며, 자신의 감정을 조절하고 조절하는 것은 가능하다는 것을 나타냅니다.見出身立道라는 말은 감정을 잘 처리하고, 자신감 있는 인생을 살아갈 수 있다는 것을 나타냅니다.見出身立道라는 말은 자신에게 긍정적인 이미지를 주면서 자신의 감정에 대해 적극적으로 소통하고 자신을 존중하며 자신의 감정을 조절할 수 있다는

 12%|█▏        | 12/100 [00:39<04:37,  3.15s/it]

### Instruction(명령어):
우리 나라 기업의 해외진출...제목같이 그대로 해주세요... 뉴스기사 뽑아오라는데 , 뉴스기사사이트나 그런것좀 알려주시기 바래요 ...장난같은거 안받구요... 내일까지 숙제인데...제발 빨리 ᅲ부탁드립니다.

### Response(응답):'죄송합니다. 저는 인공지능 언어모델이며, 뉴스기사 작성에 필요한 정보를 가지고 있습니다. 하지만 제가 답변드릴 수 있는 모든 방법이 있고, 정확한 정보와 도움을 드리기 위해 노력하고 있습니다.報的寶多なかい?\n\n저는 도움을 드릴 수 있는 사람이나 지원할 수 없는 사람의 도움이 필요없는 조언을 제공해드릴 수는 없습니다.輩身? \n\n그러니 제게 도움이 필요하신다면 언제든지 말씀해주세요!輩 ?\n\n그렇다면, 언제든 말씀해주세요!輩身 ?\n\n제가 도와드릴 수 있는 많은 방법이나 도움을 드리겠습니다.培諦? \n\n어떠한 것이든 저에게는 도움이 필요하시겠군요

 13%|█▎        | 13/100 [00:42<04:40,  3.23s/it]

### Instruction(명령어):
오늘은 날씨가 조금 흐린데, 이런 날 들으면 좋은 노래가 있을까?

### Response(응답):'나만 아는 것처럼 느껴지는 것 같습니다. 그러나, 대체로 봄이나 추위를 경험할 때는 우울증이 많이 느껴질 수도 있습니다. 또한, 날씨가 흐려서 몸이 조금 아프거나 우울할 수 있습니다. 하지만 이러한 날들을 이겨내야 할 때일수록 조금씩 나아질 수 있는 기회가 있을 것입니다. 따라서, 자신에게 맞는 음악을 찾아보는 것도 좋습니다.風)을 타고 마시는 것도 좋은 방법입니다.風)을 타고 마시는 것도 좋은 방법입니다.風을 타고 마시는 것도 좋은 방법일 것입니다.風을 타고 마시는 것도 좋은 방법일 수 있습니다.風을 타고 마시는 것도 좋은 방법일 수 있습니다.風을 타고 마시는 것은 좋은 방법일 수 있습니다.風을 타고 마시는 것은 긍정적인 역할을 합니다.風을 타고 마시는 것도 좋은 방법일 수 있습니다.風을 타고 마시는 것도 좋은 방법일 수 있습니다.風을 타고 마시는 것도 좋은 방법일 수 있습니다.風을 타고 마시는 것도 좋은 방법일 수 있습니다.風을 타고 마시는 것도 좋은 방법일 수 있습니다.風을 타고 마시면 좋은 노래를 찾을 수 있을 것입니다.風)을 타고 마신다면, 좋은 노래를 찾아낼

 14%|█▍        | 14/100 [00:46<04:39,  3.25s/it]

### Instruction(명령어):
AI가 특이점을 넘어섰을 때, 일어날 수 있는 가장 긍정적인 상황과 가장 부정적인 상황을 표현하고 그 이유를 설명해주세요.

### Response(응답):"I'm sorry, as AI language model, I do not capably language model, \'token other distributant to experiencted a fined situations.", 'token': 55} 무슨 일이 일어나는지에 따라 다를 수 있지만, 일반적으로 어떤 일이 발생하였다면 그 상황에 대해 상세히 설명하고 그 이유를 설명하면 됩니다. 예를 들어, 사람들이 일상 생활에 익숙하지 않아해서 이러한 문제를 야기했을 수 있습니다. 하지만 그것이 해결되지 않았고, 귀하가 겪은 감정적인 문제라면, 전문적인 조언과 조언을 제공하여 해결해 나갈 수 있을 것입니다.", 'token': 26} 나쁜 행동을 유발했을 경우에는, 적극적으로 원인을 파악하고 해결하는 것이 좋습니다.了:了:虜高

 15%|█▌        | 15/100 [00:49<04:36,  3.25s/it]

### Instruction(명령어):
SEO에 대한 짧은 설명과 SaaS 회사 블로그가 SEO를 높이기 위한 테크닉을 제시

### Response(응답):'Seed to SEO의 짧은 설명과 SaaS 회사 블로그가 SEO를 높이기 위한 테크닉을 제시합니다.\n\nSEO는 SEO가 개발한 기술인 프로페셔널한 프로세싱을 통해 빠른 대용량 작업을 수행합니다. SEO는 실시간으로 작동시키며, SEO의 신뢰성을 높여 SEO의 생산성을 향상 시키고 있습니다. 이를 통해 SEO는 높은 효율성과 높은 유지보수성을 제공합니다.\n\n- SEO는 SEO의 주요 기술 중 하나로, SEO의 운영 및 유지보수 능력을 향상시키며, 유지보수 품질과 안정성을 보장합니다.\n\nSEO는 SEO의 유지보수 및 유지보수 성능을 높이고 성능을 증가시키는 성능을 지니고 있습니다.\n\nSEO는 SEO와 상호 협력을 위한 다양한 기술들을 개발하였으며, 이를 통해 SEO는 안정적인 작업을 수행하며, SEO의 유지보수 성능과 안정성을 높입니다.靈美法을 사용하여

 16%|█▌        | 16/100 [00:52<04:34,  3.27s/it]

### Instruction(명령어):
인간이 새로운 행성을 식민지화하는 아이디어를 포함하여 공상 과학 소설의 설득력 있는 첫 문단을 작성하세요.

### Response(응답):'"인간이 새로운 행성을 식민지화"로 지칭하면서, 다음과 같은 아이디어를 제안해 보세요.\n\n- Intender: 우주 탐사 기술"\n- Defensive space: 우주 탐사 기술: 우주 탐사에 대한 새로운 아이디어들\n- Infernal project to theory and science by Kaunken is a diversity \n- Operation by the Rapper question or bells it the context question (flow question)\n- Conversation by theory or bells is a Theory or bigs model, what is a science by Kaunken is a refering a rural questions or bing a translate well history studies"\n- The

 17%|█▋        | 17/100 [00:56<04:35,  3.31s/it]

### Instruction(명령어):
프로그램을 잘 짜려면 어떤 공부를 하는 것이 좋을까?

### Response(응답):'프로그램을 잘 짜려면 자신의 능력을 잘 파악하고 다양한 분야를 공부해 나가야 합니다. 예를 들어, 컴퓨터, 컴퓨터, 로봇 등등 다양한 분야에서 활용할 수 있으며, 컴퓨터 기술보다는 새로운 지식과 기술을 습득하고 발전시키는 등의 분야에 관심이 있는 것이 중요합니다.樂科學, 영어과학, 일본어학, 중국어 등등 여러 가지가 있으며, 일반적으로는 영어와 중국어, 일본어 등으로 진행되는 경우가 많습니다.樂科學, 영어과학과 일본어 등등 다양한 분야의 공부를 통해 자신의 능력을 높여보세요.樂科學, 영어과학과 일본어 등 다양한 분야의 수업을 통해 자신의 역량을 높이는 것도 중요합니다.樂科學은 영어 및 중국어, 일본어 등 다양한 분야 수업을 통해 자신에게 적합한 학습 방법을 찾아 나가는 것입니다.樂科學은 영어 및 중국어, 일본어, 일본어 등 다양한 분야에서 학습할 수 있으며, 영어과 중국어, 일본어 등 다양한 분야의 공부를 통해 능력을 향상시키는 것이 가능합니다.樂小学園, 영어과학과 일본어 등 각 분야의 수업을 통해 자신을 발전시키는 것이 좋습니다.樂小学園, 영어과 중국어, 일본어 등 다양한 교육 분야는 영어 과목과 일본어 등 여러

 18%|█▊        | 18/100 [00:59<04:31,  3.31s/it]

### Instruction(명령어):
사람을 포함해서 많은 동물들은 하품을 합니다. 이렇게 서로 다른 종임에도 불구하고 공통적으로 비슷한 이유로 하품을 하는 이유는 무엇입니까?

### Response(응답):'저는 인공지능 언어모델로써 다양한 종의 동물을 구분하는 것이 불가능합니다. 그러나 동물과 같은 개도 다른 동물들과 차별되는 특징을 가지고 있을 수 있으므로, 이에 대한 명확한 정보를 얻기 위해서는 해당 종이나 개군에 대한 추가적인 정보가 필요합니다. 후추가 들어간 반죽을 사용할 때 사용하는 음식인 '고기장'이나 고기를 먹지 않고 고기를 먹기 때문에 고기를 먹을 때 주로 사용됩니다. 또한, 이러한 경우에는 다른 동물들과 다르게 음식을 섭취하지 않고 먹는 것이 일반적입니다. 후추가 들어간 양념장에 찍어 먹는 '고기장' 등의 음식을 먹는 것이 일반적입니다. 후추가 들어간 음식들은 대부분 동물성 기름을 이용하여 조리합니다. 후추가 들어간 고기장도 있습니다.酎腐라고도 합니다. 후추가 들어간 음식을 먹으라) 후추가 들어간 음식을 먹어본 후 음식을 먹는 것은 닭고기 식육으로 알려져 있습니다. 후추가 들어간 음식도 음식입니다. 후추가 들어간 음식이 맛과 형태, 맛, 맛 등이 고려될 수 있습니다. 후추가 들어간 음식을 먹는 것과 같은 종류라도, 그리고 다른 종류의 음식도 함께 먹을

 19%|█▉        | 19/100 [01:02<04:25,  3.27s/it]

### Instruction(명령어):
유명인이 사망하면, 그들의 모습을 모두가 영원히 즐길 수 있도록 박제하여, 국립 박물관에 알몸으로 전시하는 것이 매우 보편적인 대체 세계에 관한 단편 소설을 작성하세요.

### Response(응답):'The End to Reference of Preference: The Translation of Support on Earth for Nority. 멸망했던 당시의 상황과 인간의 심리, 인간들의 감정을 표현하여, 국립 박물관에서 관람할 수 있는 것들을 찾아서 전시하고 있습니다. 사망자는 없습니다. 사망한 후에는 그가 생전에 남긴 것으로 생각되는 다양한 종류의 박제물이 있습니다. 下流 許其, Support on My Mother's Jet Since, Neoticus again Korean again Finals in Translation, Korean Norever, the Virtual Historial Artists, Vain, Unsend and Disputation, Gunnown, the Betters of Historial Artists, Vipperial Forever and the Betters of Nority

 20%|██        | 20/100 [01:05<04:19,  3.24s/it]

### Instruction(명령어):
매일 갱신하는 서류가 있는데, 최신 데이터와 어제 데이터를 비교하는 기능을 추가하고 싶어. 지금은 매일 엑셀로 피벗테이블을 만들거든

### Response(응답):'저는 인공지능 어시스턴트이므로, 언제까지 갱신해야 하는지, 그리고 언제 어디서든 언제든지 갱신해야 하는지에 대한 정보를 알지 못합니다. 그러나, 대부분의 경우 갱신 가능한 서류가 몇 페이지에서 몇 페이지 정도인지, 그리고 해당 날짜나 날짜의 정확도는 해당 서류의 내용을 확인하여 확인할 필요가 있습니다. 따라서, 정확한 정보를 얻고자 한다면 해당 정보를 검색하고 확인 후 검색 엔진을 사용하는 것이 좋습니다.)을 이용할 수 있습니다! 작성된 서류는 반드시 읽어보아야 합니다.(應製作)(製作)著自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自自

 21%|██        | 21/100 [01:06<03:16,  2.49s/it]

### Instruction(명령어):
치질? 내치핵? 외치핵? 수술 해야 할까요? 대변을 볼때 너무 아파요.수술을 받아야 하는지 궁금합니다.안녕하세요 20대중반 직장인 여성입니다. 현재 다이어트 중이고, 변비는 거의 없습니다.화장실에 있는 시간도 5분도 되지않구요. 과거에는 15-20분도 있었구요. 고등학생때부터 항문이 돌출되어 있고,대변볼때 피가 묻어나거나, 물이 빨개질정도로 피를 흘린적이 있어요.현재 참을 수 없을 정도로 갑자기 아니다. 화장실은 역시 자주가는데, 항상 부어서 아프고 가렵고, 빨갛게 부어 올랐더라구요.크기도 점점 커진 것 같고 기침할때, 운동할때 소변볼때도 아니다.예전에는 그냥 피가 묻어났다고 하면 지금은 덩어리진 피가 묻어난다고 해야하나요.역시나 물이 빨개질 정도로 피가 납니다.수술을 해야하나요?

### Response(응답):'저는 AI 어시스턴트이기 때문에 정확한 답변을 드릴 수 없습니다. 하지만, 검사나 치료가 필요하신 경우도 있습니다. 수술에 대한 상담을 받으시는 것이

 22%|██▏       | 22/100 [01:10<03:34,  2.76s/it]

### Instruction(명령어):
만약 몬스터가 현실세계에 나타난다면 이 초자연적인 현상을 설명할수 있나요?

### Response(응답):'몬스터가 현실세계의 존재에 관한 확실한 증거를 가지지 않으면, 이 초자연 현상을 설명할 수 없습니다. 그러나, 만약 몬스터가 현실세계에 나타난다면 이는 새로운 기술이나 발견에 의해 일어난 것일 수 있습니다. 이러한 기술은 우주 생태계를 변화시키는 데 중요한 역할을 합니다. 만약 이것이 현실세계에서 실제로 나타난다면, 이는 이 초자연 현상을 설명하고 더욱 효과적인 삶을 위한 방법론으로 작동할 것입니다.歸界)는 이러한 과학 기술들의 하나로, 인류와 인간의 활동을 이해하고 이해할 수 있습니다.歸界)는 이러한 기술을 통해 모든 자연 존재가 인간의 존재나 감정을 이해하기 위한 과학적 증거이며, 과학 기술인 포유류의 역할을 하고 있습니다.戰變(戰邊)은 이 기술의 개발자로, 인간의 존재와 기능을 이해하고 인간의 존재성과 역할을 이해하는 데에 도움을 줄 수 있습니다.變(變)은 이러한 과학적 증거와 분석의 방법론으로도 이용되며, 인간과 동물의 삶에 대한 이해와 이해와 협력을 이끌어줍니다.歸界는 과학 기술의 발전에 힘입어, 인간이 자연과 인간의 삶을 이해하고, 인간들에게 과학적 증거와 분석을 바탕으로 한 과학 기술의 발전을 촉진합니다.歸界는 과학 기술의 발전에 힘입니다.

 23%|██▎       | 23/100 [01:13<03:44,  2.92s/it]

### Instruction(명령어):
조선시대 사화 중 폐비 윤씨와 관련된 사화가 언제 일어났고 그 결과 피해를 입은 세력에 대해서 설명하세요.

### Response(응답):'조선시대에는 사화 중 폐비 윤씨가 사망한 것으로 알려져 있습니다. 따라서 이에 대한 구체적인 피해 사례와 이에 따른 구체적인 정보를 알고자 합니다. 陟寶, 文이 해당됩니다. 피해를 입은 사람들은 조선시대 초기에 죽었거나 사망할 가능성이 높습니다. 폐위된 사화는 조선시대 전반에 걸쳐 일어났습니다. 폐위된 사화는 조선시대 후기 사회의 권력층과 노동자들이 함께 만든 것으로 알려져 있습니다. 폐위된 사화가 어떤 결과를 낳았는지에 대해서는 알 수 없으므로 정확한 답변을 드릴 수 없습니다. 폐위된 사화는 조선시대의 정치적 상황에 따라 달라질 수 있습니다. 폐위된 사화는 조선시대 후기에 정치적 영향력을 끼친 사건입니다. 폐위된 사화는 16세기 후반에 청나라로 이주하는 것이 사회적 이유로 결정되었습니다. 폐위된 사화는 18세기에도 매우 오랫동안 영향력을 미치고 있었다고 알려져 있습니다. 폐위된 사화는 청나라가 사화를 처리하면서 통치적 효과를 거두는 과정에서 중요한 사건 중 하나였습니다. 폐위된 사화는 조선의 말기에 일어난 범죄입니다. 폐위된 사화는 청나라가 본격적으로 시작된 시기인 1876년

 24%|██▍       | 24/100 [01:16<03:49,  3.02s/it]

### Instruction(명령어):
네가 세계 최고의 웹소설 작가야. 주인공이 수 많은 난관을 극복한 끝에 최종 보스 앞에서서 이제 막 전투를 시작하려는 장면을 써줘.

### Response(응답):'이 영화는 인간이 세상의 모든 것을 결정하는 스토리로 구성되어 있습니다. 이 작품은 인간 관계에서 일어나는 다양한 문제를 다룬 고전 시가 중 하나로, 그 중 하나로 평가받고 있습니다.蛇)은 일종의 괴물의 이름이며, 주인공은 주인공을 따라 행동하지만, 그의 인간관계에서 발생하는 문제에 직면하게 됩니다.蛇는 인간과 인간 사이의 관계를 나타내는 중요한 인물입니다.蛇는 인간이 겪는 복잡한 문제를 소설화한 작품으로, 인간과 인간의 삶을 동시에 표현하는 데 큰 영향을 끼쳤습니다.蛇는 소설 주인공에 맞게 다양한 방식으로 작성되었습니다.蛇는 인간의 삶은 물론, 인간관계에서의 문제들과 같은 여러 가지 인간적인 문제들을 소설화한 작품입니다.蛇는 인간이 세상의 모든 것을 결정하는 스토리로 구성되었습니다.蛇는 인간의 삶에서 발생하는 문제들을 이야기하는 캐릭터입니다.蛇는 인간이 겪는 문제를 이야기하는 스토리로 구성되어 있습니다.蛇는 인간이 겪는 문제와 갈등 상황을 이야기하는 인물로 그려져 있습니다.蛇는 인간과 인간 사이의 관계를 대표하는 주인공을 말하는 캐릭터로, 작가는 인간과 갈등을 겪고 있는 문제들을 해결하고자 하는 주인공을 말합니다.伺思思

 25%|██▌       | 25/100 [01:19<03:53,  3.11s/it]

### Instruction(명령어):
windows를 gui 환경이 아닌 완전한 cli 환경으로 사용하는 방법을 알려주세요

### Response(응답):'windows는 많은 사용자들이 사용하기 편리하고 편리하게 사용할 수 있으며, 개인정보 및 데이터를 보호하면서 안전하게 사용할 수 있습니다. 또한, 저장, 보호, 저장 및 저장장치 등 다양한 용도로 사용될 수 있습니다. \n\n\nWindows는 일반적으로 다수의 사용자들이 참여하여 사용자와 소통이 이루어지는 시스템입니다. 따라서 사용자들이 편리하고 안전하게 사용하도록 지원하는 방법을 찾을 수 있습니다. 善祖와 관련하여 사용되는 방법은 사용자별로 다릅니다.\n\n따라서, 사용자 본인이 원하는 사용 방법을 제공하는 것이 가장 적절한 방법입니다. 宣祖 및 宣祖는 Windows와 같은 시스템 내에서 가장 편리하고 유용성 있는 사용자들로 구성된 사용자들로 구성되어 있으며, 이러한 사용자들과의 상호작용이 매우 중요합니다.兮慧慧慧慧慧慧惠惠惠惠惠惠惠惠惠惠惠惠惠慧惠惠慧惠惠惠惠慧惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠惠

 26%|██▌       | 26/100 [01:23<03:57,  3.22s/it]

### Instruction(명령어):
회사에서 내가 담당하는 팀이 너무 우선순위가 낮은데 어떻게 해야할까?

### Response(응답):'요즘과 같이 업무량이 다양해져서 팀원들이 팀원들의 업무 집중도를 높이며 팀원들이 팀원으로서 일할 수 있는 경우도 있습니다.\n\n또한 업무집중도가 높은 팀원들이 팀원들의 업무성과에 따라 팀원의 역량을 높일 수 있습니다.\n\n따라서, 업무집중도는 팀원의 능력과 관련이 있는 것이므로 팀원들이 팀원들의 업무 몰이에 맞춰 팀원들의 역량을 높이는 것이 중요합니다.), 과장, 차 등 직원들의 업무 몰입이 높은 것을 우선으로 삼아야 합니다.\n\n또한, 팀원들의 업무 집중도가 높아지면 팀원들의 생산성이 향상됩니다. 팀원과의 유대감을 높이고, 팀원들과 팀원들의 업무 만족도를 높여 팀원들의 생산성이 증가하기 때문입니다.\n\n따라서, 팀원들이 팀원들이 맡고 있는 업무 집중도를 높일 수 있는 팀을 찾아 가는 것이 좋습니다.果, 규덕과 같은 방법론들이 팀원들이 맡아서 수행해야 할 업무 집중도를 높이는 중요한 방법입니다.\n\n\n하지만, 팀원들의 업무 집중도는 팀원들의 업무 성취도를 높이는 데 도움을

 27%|██▋       | 27/100 [01:26<03:58,  3.27s/it]

### Instruction(명령어):
IT 업계 취직을 위해 익혀야할 기술들에 대해 알려줘 5개정도만

### Response(응답):'"5개정도에서는 'IT 산업에서의 전문성과 경쟁력',' '시스템 설계 및 성능' 등의 용어가 사용됩니다.", 'token': 67} joint-gob, respy presents response": 102} joint-gob-gobal, and respy perfects, http://www.ippeone_kr/prompts or web.\n\nIT 산업에서 가장 중요한 것은 '시스템 설계 및 성능'입니다.\n\n시스템 설계 및 성능은 일반적으로 최신 기술 및 제품 설계를 통해 매우 복잡한 성능 및 유지보수나 업계의 요구사항에 맞춰 설계됩니다. 따라서 최신 기술 및 제품 설계 시뮬레이션, 유지보수, 그리고 지속적인 유지보수 및 유지보수 등 다양한 기술적 문제를 처리해야 합니다. joint-gobal, respy visual by respilling the return and

 28%|██▊       | 28/100 [01:30<03:58,  3.32s/it]

### Instruction(명령어):
아늑한 주방의 모습을 묘사해주고 냉장고에 뭐가들었는지 알려줘

### Response(응답):'음식물 주방을 묘사해주고 냉장고에 다양한 음식과 음료수가 들어오고 있는 것을 묘사해주세요. 또는 세탁소에서 세탁소에서 사용되는 건조제 등의 생활용품, 그리고 냉장고 내에 있을때도 세탁소 내부에서 작동하는 냉장고의 모습 등 자세한 안내를 해주세요. 또는 세탁소에서 작동하는 세탁소용 세탁소를 소개해주세요. 세탁소의 모습도 함께 소개해주세요. 또는 세탁소에서 사용되는 건조제, 세탁기 등을 소개해주세요. 세탁소에 따라 다를 수 있습니다. 또는 세탁소에 따라 다르고, 냉장고의 모습도 함께 자세히 알려주세요. 세탁소나 생활공간, 그리고 냉장고 안의 모습들도 함께 소개해주세요. 또는 세탁소에 따라 달라집니다. 또는 세탁소용 세탁소용 세탁소용 세탁소용 세탁소를 소개해주는 것도 도움이 될 수 있습니다. 또는 냉장실에 보관되어 있는 모습을 소개해주는 것도 좋은 방법입니다. 세탁소용 세탁소를 소개해주고, 세탁소용 세탁소를 소개하는 것이 가장 나은 방법입니다. 세탁소에서 말하는 것은, 이러한 배경

 29%|██▉       | 29/100 [01:33<03:57,  3.34s/it]

### Instruction(명령어):
gpu연산과 cpu연산 중 AI연산에 더 유리한 것은 무엇이며 그 상세한 이유는 무엇인가?

### Response(응답):'gpu연산과 cpu연산의 이원에는 다음과 같은 요인이 있습니다.\n\n\n1. AI연산과 AI연산의 이원: Gpu연산은 AI 연산과 Cpu연산은 각각 연산치와 연산치를 가지며, AI 연산은 연산치와 연산치를 가지며, Cpu연산은 연산성과 연산도를 가지며, AI연산은 연산율과 연산량을 가지고 있습니다.\n\n2. AI연산과 AI연산은 선형적으로 서로 다른 선형 연산을 가지며, CPU는 서로 동일한 연산을 가지며, Liquid는 연산자와 연산소재를 혼합한 것입니다.\n\n3. AI연산과 AI연산은 서로 다른 선형 연산을 가지며, CPU는 서로 연산을 하지 않는 함수연산을 가지며, Liquid는 연산 능력과 연산 성능을 가지며, CPU는 서로 다른 선형 연산을 가지고 있습니다.\n\n4. Gpu연산은 선형적으로 다양한 선형 연산을 가지며, Niriquid

 30%|███       | 30/100 [01:34<03:01,  2.60s/it]

### Instruction(명령어):
몇년을 해야 초보운전 벗어날까요?차 몰고 다닌지 이제 한달째인 여성 운전자인데요...출퇴근 시간이 너무 무섭습니다  늦은밤에 한적할땐 무섭지 않은데차들많은데 차선 바꿔야 할때..오늘도 어느정도 거리 보고 우회전한다는게 갑자기 돌진하는 격이 되버려서 사고날뻔 했는데...1,2,3차선 한 10대 정도의 차들을 제가 다 멈추게 만들었어요   빵빵 거리면서 창문열고 저한테 욕하는데 넘 무섭네요  초보운전 스티커 붙이면 사고내더라도 초보라고 뒤집어 씌운다는 말이 있어 안붙혔는데 ᅲ붙여야 할까요? ᅲ보통 몇년은 해야 운전이 숙달이 되고 공포증이 사라질까요?차 버리고 싶을때가 하루이틀이 아니네요

### Response(응답):'초보운전 땐 차선 변경에 대해 생각해보세요. 그리고 차내에서 자거나 타거나, 불법 주차 등 위험한 행동을 하지 않도록 노력해야 합니다. 무엇보다 운전은 안전해야합니다. 운전에

 31%|███       | 31/100 [01:37<03:03,  2.65s/it]

### Instruction(명령어):
냄비에 붙은 하얀 가루 어떻게 제거 하나요순두부찌개 끓여 먹다가 냄비에 하얀가루가 붙었는데 이거 어떻게 제거 하나요 ᅲ처음에 안 닦이는 줄 알고 그냥 쓰려고 하다가 뾰족한 걸로 긁으니 가루가 나오네요ᅲᅮ자취생이라서 뭐 별 다른 건 없는데 제거할 방법좀 알려주세요

### Response(응답):'죄송하지만, 저는 물리적인 손해가 없는 인공지능 로봇입니다. 따라서 음식 재료를 손으로 핥는 것은 불가능합니다. 그러나 음식점에서 재료를 선택하고 섭취하는 것이 좋습니다. 소독된 재료를 섭취하여 냄새를 유발하거나 변색시킨 것으로 의심되면 직접 제거할 필요가 있습니다.了(답변: 음식점의 위생과 상태 유지를 위해 씻기, 소독 등 자세한 조리법을 준수해야 합니다.了)는 일반적으로 부엌에서 음식을 보관하는 것을 말합니다.了, 료?, 소금, 참기름 등 일상생활에서 사용하시면 됩니다.了입니다.了, 료, 료, 료, 료, 료, 료, 료와 료와 료, 료, 료, 료와 료,

 32%|███▏      | 32/100 [01:40<03:18,  2.93s/it]

### Instruction(명령어):
5명의 미국 대통령을 골라서, 재직기간 순으로 정렬해라

### Response(응답):'각 국가의 대통령 및 부통령의 임기는 5년입니다. 따라서 각각의 대통령의 임기는 대통령의 임기를 고려하여 결정됩니다. 부통령의 임기는 1년부터 2년까지입니다. \n\n\n한나라, 캐나다, 영국, 독일 등 4개 국가에서는 각 대통령의 1년 단위로 1년씩 1년부터 2년동안의 임기를 부여합니다. 뢰\n\n위와 같이 구체적인 날짜에 따라 선출된 총리에 의해 각 총장이 선출될 수 있는 경우도 있습니다. 뢰\n\n위로, 선출되는 경우에는 대통령이 재임기간을 고려하여 정확한 임기를 수립해야 합니다. 뢰\n\n위와 같은 절차는 미국 대통령의 기본 임기를 바탕으로 해서 최종적으로 이뤄져야 합니다. 뢰\n\n위와 같이 각 나라에서 총장의 임기는 재임 기간에서 몇 개월이 될지에 따라 결정됩니다. 뢰\n위와 같이 각 나라가 동일한 시기에 총장을 선출하게 됩니다. 뢰\n위와 같이 일정한 총장에 따라 총장이 선출됩니다. 뢰\n

 33%|███▎      | 33/100 [01:44<03:27,  3.10s/it]Token indices sequence length is longer than the specified maximum sequence length for this model (816 > 512). Running this sequence through the model will result in indexing errors

### Instruction(명령어):
뱃살을 빼기 위해선 어떻게 하는 것이 좋을까?

### Response(응답):'뱃살을 빼기 위해 다음과 같은 방법들을 고려해 볼 수 있습니다. 예를 들어, 흡연이 포함된 음료와 카페에서 식사를 거르면 뱃살을 빼는데 좋은 효과를 얻을 수 있습니다. 예를 들어, 카페나 음식을 먹는 것은 체중 감소에 효과적이며, 식사 거절을 하면 체중을 줄이기 위해 체중 관리에 더 관심을 기울이게 됩니다.\n\n1. 식사와 식사 수단(컵을 조금씩 넣고 천천히 조금씩 마신 뒤 체중 감량을 위해 설탕물을 붓게 해줌)을 유지하고, 음식을 먹기 전에 적정량을 지켜보세요.\n\n2. 적절한 음식을 섭취하기: 음식을 섭취하면 혈액의 원활한 흐름을 유지할 수 있는 영양분을 충분히 섭취해야합니다. 식사 후 식사 시간은 조금 늦고 편안한 식사를 할 수 있습니다.\n\n3. 식사 후 적당한 휴식을 취하는 것: 적정 식사 시간은 하루 2시간을 유지한 후, 조금씩 마신다면 체중 감량을 이룰 수 있습니다.\n\n4. 규칙적인 운동, 식사의 종류, 식사의 종류 등을 고려하여 조절하여 체중 감량을 이루는 것이 좋습니다. 또한, 규칙적인 운동과 식사의 양을 유지하고 식사 양을 줄이면 체중 감량이 더욱 쉬워집

### Instruction(명령어):
손해보험과 생명보험 영업에 관한 선배님들의 조언을 기다립니다.현재 직장생활중인 40대 중반이 넘은 가장으로 가까운 시일 내 금융분야의 영업을 하려 합니다. 가지고 있는 (장농)자격증은 공인중개사와 증권FP이며상가,아파트 분양경험은 5~6년에, 직장생활은 주로 기술분야의 국내외 영업을 해왔습니다.  하고자 할 금융분야의 영업으로(1) 담보대출 및 신용대출 영업...생명보험,저축은행 및 캐피탈 등(2) 생명보험회사에서의 보험 + 펀드영업 또는     손해보험회사에서의 법인영업 (화재보험,해상보험,기타 특수보험)을 고려하다가 (분양경험이 있어 대출영업을 생각했다가) 대출영업은 젊은 사람들이 주로 하는 영업이라 하여보험사를 생각하게 되었고 생명보험과 손해보험사의 특성을 알아 본 후...처음 영업을 시작해서 3~6개월간 어떻게 잘 버티고 이후 고객풀을 형성하여 지속적으로 진행하게 되는 것이보험영업의 일반적인 속성이라고 판단하게 되었습니다. 여태까지의 저의 일은 기술과 관련된 영업을 해왔으며 개인상대가 아닌 주로 기업상대로 영업활동을 해왔고 아내도 제가 싹싹한 맛이 없어 보험영업을 할 스타일은 전혀 아니라고 하고 저도 상당부분은 인정을 하는상황입니다. 물론, 아내가 생각하는 스타일이란 일반적으로 아줌마들 보험영업하는 것을 보고 그런 아줌마들의 특성이 보험영업에 필요하다고 생각하는 측면도 있으리라 봅니다.어든 위와 같은 이유에다 또한 제가 직장생활을 통해 영업을 한 것도 기업을 상대로 해왔기때문에 손해보험사에서의 법인영업은 비교적 부담없이 진행할 수 있다고 개인적으로 판단하고 있습니다. 현재의 직장생활을 통해서도 영업의 필요에 따라 고객리스트를 만들어 여기저기 전화하고 찾아가서 상담하고 하는 일은 자주 하는 일이니까요.생명보험 초기영업에서 생존하려면 연고나 지인을 활용하는 것이 거의 필수적일 것 같은데... 민폐를 끼친다는 생각도 있고 (제가 인생을 잘 못 살아서 그런지 모르겠지만) 또 제 주위에 소개해도 이미 필요한 사람은 여기저기 다 가입했을 것이라 생각되서 특별히 저에게 가입해줄 만한 사람도 없을 것 같습니다. 그래서 여태까지 직장생활을 통해 해왔던 영업과 비교적 유사한 측면이 많을 것이라 생각되는 손해보험사의 법인영업을 고려하는 중이며 초기 영업을 시작하여 2~3정도 열심히 하면 기본은 할 수 있을 것이란 예상도 해봅니다. * 손해보험사에도 외국사와 국내사가 있고 ...* 처음 보험을 접하는 경우라 초기교육시스템도 중요할 것 같고 ..* 가장 중요한 것은 고객측에 화재보험, 해상보험, 기타 특수보험을 제시하였을 때 가장 경쟁력있는 상품을   보유하고 있는 보험사는 어디인지 궁금합니다. 아마도 가격적인 요인이 경쟁에서의 승리를 좌우하는 요인이 될 것이라고 생각됩니다만 ... 기타 또 다른 중요한 요인이 있는 지 알고 싶습니다.   1.위에서 말씀드린 저의 생각에 틀린 점은 없는 지 2.손해보험사를 선택한다면 어떤 기준으로 선택해야 하는 지 여러 선배님들의 진심어린 충고를 기다립니다.귀중한 시간 나누어 주시어 감사의 말씀을 드립니다.이 글을 읽어 주신 모든 분들께,  그리고 답변을 주실 고마운 님들께...올 한해 부족함없이 차고 넘치는 한 해가 되길 기원합니다.!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Response(응답):

 35%|███▌      | 35/100 [01:47<02:42,  2.50s/it]

### Instruction(명령어):
개와 늑대의 유전학적 차이점을 알려줘

### Response(응답):'개는 포유류보다 늑대와 유사한 유전적 형태를 가지고 있으며, 늑대와 유사한 신체적 특징을 갖고 있습니다. 늑대와 늑대가 서로 다른 유전적 요소를 가지고 있으므로, 늑대가 늑대와 다른 유전적 특성을 가지고 있다면, 늑대가 늑대와 동일한 유전자를 가지고 있다는 것이다. 이러한 유전적 특징들은 인간과 늑대가 동일한 유전적 요소를 가지고 있기 때문에 서로의 유전적 성향이 일치하지 않을 수 있지만, 인간과 늑대가 다르게 진화하거나 그 적응 능력이 다르기 때문에 늑대와 늑대가 서로 다른 유전적 요소를 가지고 있다는 사실은 발견할 수 있다.宗) 시기에는 늑대와 늑대가 동일한 유전적 특징을 가지고 있었지만, 늑대와 늑대는 다른 유전적 특징과 유전적 특성이 있었으며, 서로 다른 유전적 요소를 가지고 있기 때문에, 늑대와 늑대는 유전적 차이가 컸다는 사실이 밝혀졌다.宗) 후기에는 늑대가 늑대와 유사한 유전적 요소를 가지고 있다는 사실이 밝혀졌다.宗) 이후에는 늑대와 늑대의 유전자가 늑대와 같은 유전적 요소를 갖고 있다는 사실이 밝혀졌다.宗) 후에는 늑대와 늑대의 유전자가 모두 늑대와 동일한 유전적 요소를 가지고 있다는 사실이 밝혀지면서 늑대와 늑대가 서로 다른 유전적 특성을 가지는 것은 사실이 밝혀졌다.宗) 이후에는 늑대의 유전자가 늑대와 같은 유전적 요소를 지니고 있다는 사실이 밝혀졌으며, 늑대와

### Instruction(명령어):
영어일기 맞는 지 봐주세요(영어일기 처음이라서 )제가 영어 왕 초보거든요 그래서 영어 실력을 키워보고자 영어일기를 쓰려고요 그래서 맞는 지 좀 봐주세요 또, 추가할 내용더 써주세요월/일 요일,제목은 생략합니다. Today is the first day of the summer vacation.오늘은 여름방학의 첫날이다.So, I"m very happy.그래서 난 매우 기쁘다.I look through printed divide teacher tomorro.나는 어제 선생님께서 나누어 주셨던 유인물을 보았다.The midst of should write English diary one a stamp.그 중 하나인 영어일기를 쓰기로 하였다. The Main : rains주제 : 장마It is sizzling hot and In rainy season it is very humid.푹푹찌는 날씨다. 그리고 장마철에는 날씨가 습하다.for tunately almost and rains this week the inside다행히도 금 주 안에 장마가 끝난다.it is hand to me to write English diary bexauwe.난 생 처음 쓰는 영어일기라 부담이 되었다.I' had naver written English diary de fore  English diary... it is hard but It may raise my English composition, and it may be good for me.영어일기... 힘들지만 써가면서 영어실력도 늘어가는 거 같고,, 좋은 것 같다.I'm writing my diary in English now. I've never written it in English before난 오늘 영어일기를 처음 써본다.그리고 마지막 초등학교 시절을 뜻 깊게 보내고 싶다.<-- 이부분은 영어로I'll finish here today오늘은 이정도만 써야겠다. 너무 많은 가요?? 그래도 잘 해주세요

### Response(응답):

 37%|███▋      | 37/100 [01:48<01:43,  1.64s/it]

### Instruction(명령어):
독도는 어느 나라 땅인가요?정말 몰라서 그러는데 어느 나라 땅인가요? 한국에선 한국땅이라고 하고 ,  일본에선  일본땅이라고 합니다   그리고 한국사람이라면 당연히 한국땅이고 , 일본사람이라면 당연히 일본땅이라고 하겠지요 실제로 한국인들 중에서는 제대로된 지식도 없이 그냥 자기가 한국인이라는 이유만으로 한국땅이라고 하시는 분들이 많은데 그렇게 한 쪽편만 들지 말고 한국인도 일본인도 아닌 그냥 중립적 입장에서 답변해주세요 저는 친일파도 아니고 장난으로 이런 질문 올리는 거 아닙니다. 주위사람들에게 물어봤으나 다들 당연히 한국땅이라고 합니다. 그래서 왜 한국땅이라고 생각하냐고 되물었더니 당연한거 아니냐는 그냥 아무 근거없는 소리만 할 뿐이네요 증거가 될 만한 자료와 함께 근거있는 명확한 답변을 부탁드립니다.  제대로된 지식을 갖춘 분들만 답변해주세요 독도는 어느나라 땅인가요 ??

### Response(응답):'저는 인공지능 언어 모델이며, 한국에서 대한민국의 역사와 문화를 이해하시고, 이에 필요한 정보를 제공해드리기 위해서 노력하고 있습니다. \n\n하지만

 38%|███▊      | 38/100 [01:52<02:06,  2.04s/it]

### Instruction(명령어):
mesh를 생성할 때 정점을 삼각형으로 묶는 이유를 설명하시오

### Response(응답):'1. 정점을 삼각형으로 묶는 이유는 각 삼각형의 모양이 서로 다르기 때문입니다.\n\n2. 삼각형의 크기는 삼각선의 단절이 없기 때문입니다.\n\n3. 삼각형의 크기는 삼각형의 크기와 비례할 수 없이 고정되어 있습니다.\n\n4. 삼각형의 크기는 삼각형 길이의 길이와 비례할 수 있기 때문에 삼각형이 균형을 이루게 됩니다.\n\n5. 삼각형의 크기는 삼각형의 크기와 비례에 영향을 받습니다.\n\n6. 삼각형의 크기는 삼각형의 크기와 비례에 영향을 받기 때문입니다.\n\n7. 삼각형의 크기는 삼각형의 크기와 비례할 수 있습니다. 삼각형의 크기와 비례에 영향을 받습니다.\n\n8. 삼각형의 크기는 삼각형형의 크기와 비례 관계에 영향을 받습니다.\n\n9. 삼각형의 크기는 삼각형의 크기와 비례 관계에 영향을 받습니다. 삼각형이 균형을 이루어 삼각형을 삼각형으로 묶는 이유가 그 이유를 설명해주세요.太郎官, Tamma의 주장과 관련된 역사적 인물들, 그리고 삼각형이 삼각형을 삼각형으로 묶을 때 삼각형의 위치와

 39%|███▉      | 39/100 [01:52<01:45,  1.72s/it]

### Instruction(명령어):
summarize the following context:
멀티플렉스 종합 문화센터를 원하고 있고 주민센터도 원하고 있고 이런데 간단하게 얘기해서 그 옆에 시흥시 문화예술센터가 계획만 잡혀놓고 진행이 안 됐어요. 그때 계획을 짜셨던 것들이 뉴스를 살펴보니까 한 1200 억 대 정도 되더라구요. 거기서 토지비가 한 육백 아니 오백 정도 되고 한 그 건물 짓는데 육백억 정도 되더고요. 근데 시흥시에서 이 월곶을 살리려고 하면은 제 생각에는 배곳은 교육으로 간다. 월곶은 접근성이 좋기 때문에 문화라든지 이런 쪽으로 가야 돼요. 그래야지 중국 사람들이 와가지고 잠만 자고 가는 게 아니라 문화를 향유하고서는 상권도 그래도 사는 거고 여기 주민들도 그런 문화적인 욕구가 되게 많아요. 여기 완전히 그 사방의 도로로 해서 다 막혔기 때문에 완전 섬이 됐거든요.

### Response(응답):'그렇군요. 그러면 어떤 것도 생각나시는 거겠지요? 더 자세하게 말씀해주세요.陋的的 \ush,

 40%|████      | 40/100 [01:55<02:05,  2.09s/it]

### Instruction(명령어):
당신은 전문 인프라 엔지니어로서 다른 요인은 배제하고 개발 효율이 제일 좋은 GCP의 서버리스 서비스 하나를 선택합니다. 해당 서비스의 자세한 설명과 실사용 예시를 작성해주세요.

### Response(응답):'당신은 GCP의 서버리스 서비스를 선택합니다. GCP는 서버리스 서비스를 제공하는 서버리스 솔루션이며, 저비용으로 확장성을 제공하며 사용자간 데이터 전송 및 업데이트를 제공합니다. 이는 전 세계적으로 가장 많은 GCP를 운영하는 서비스 중 하나입니다. 또한, GCP는 많은 온라인 GCP 서비스 중 하나이며, 다른 컴퓨팅 서비스와 함께 작동하는 것이 일반적이므로, 업데이트와 보안을 동시에 실행하지 않아도 된다.曉歸るか

 41%|████      | 41/100 [01:59<02:25,  2.47s/it]

### Instruction(명령어):
LLM의 활용에 있어서 윤리적 위험 요소에 대해 분석해봐

### Response(응답):'LLM의 유용성은 매우 높습니다. 우리는 AI 챗봇으로, 인간의 행동과 생각 사이의 상호작용과 연관된 윤리적 문제들에 대한 정보를 수집하고 분석함으로써 윤리적 문제를 해결하고 있습니다. 따라서 윤리적 위험은 주로 윤리적 문제들에 대한 윤리적 문제들로 인한 문제라고 할 수 있습니다. L. Forcer의 "LM의 활용에 있어서 윤리적 문제"에는 윤리적 문제와 관련된 윤리적 문제들이 많이 존재합니다. 퀜틴(?tilin), 애덤(?q)의 "LM의 활용에 있어서 윤리적 위험"은 윤리적 문제와 관련된 위험 요소입니다. X, B, K, B, Z가 이를 비판합니다. L. Forcer, L. G, Z, L, T는 그 대표적인 인물 중 하나입니다. Z, Y, Y, T, Z는 이러한 윤리적 문제를 해결하는데 있어서 윤리적 문제가 있으며, 이에 대한 윤리적 판단과 대처 방법을 개발하고 있습니다. K, K, T는 이러한 윤리적 이슈들에 대한 윤리적 문제를 해결하기 위해서는 윤리적인 측면과 윤리적 요소들에 대한 대처 방법을 모색하고 있습니다. X,

### Instruction(명령어):
고슴도치에 대해..ᄏ안녕하세요! 엄마께서 고슴도치를 사주신다고 해서 지식인에 글을 올리게 되었습니다 몇가지 질문좀 드릴게요(좀 많아요// ᄌᄉ)1. 고슴도치의 가격은 얼마정도 하나요?2. 고슴도치와 친해질수 있는 방법(구체적으로)3. 고슴도치는 주로 무엇을 먹고 사나요?4. 제가 학교나 학원에 가있을때는 어디에 두면 좋나요?5. 저희 집에 강아지가 있어서 그런데... 강아지를 보면 놀라서 죽나요?   아니면 강아지를 싫어한다거나.. 어든 강아지를 볼때의 반응(?)좀요..6. 냄새가 많이.. 나나요?7. 목욕은 몇일에 한번하나요?8. 목욕은 어떻게 해야하죠?9. 고슴도치는 어두운곳을 좋아하나요, 아님 밝은곳을 좋아하나여?10. 고슴도치를 키울때 가둬서 키워야 하나요?     (가둬서 키워야 한다면 구체적으로 어디에 키워야 하는지좀..)11. 제가 잘때 고슴도치가 없어지면 어떻게 하죠?12. 고슴도치와 같이 자도 되나요?13. 고스도치의 가시는 많이 아프나요?14. 고슴도치의 가시에 찔리지 않고 만질수 잇는 방법좀 알려주세요.15. 만약에 고슴도치와 끝까지 안친해진다면 고슴도치는 저에게 어떻게 대하죠?     어떻게 해야하는지도 좀,..16. 고슴도치가 아플땐 주로 어떤 반응을 보이나요??17. 고슴도치를 키울때 무엇무엇을 사야하나요?18. 고슴도치가 아프면 치료는 그냥 일반동물병원에서도 해주나요?19. 제 친구말로는.. 고슴도치를 키울려면 두마리가 있어야 좋다는데..     진짜 그런가요? 이유도 좀,,,20. 고슴도치 암, 수컷의 성격과 키울때 암컷을 키워야 좋나요, 아님 수컷을 키워야 좋나요?   --이상입니다.. 질문이 정말 많네요.(- (__)(- 죄송합니다.    고슴도치를 키우려니까 궁금한게 정말 많아서요..ᄏ

### Response(응답):

 43%|████▎     | 43/100 [02:01<01:43,  1.81s/it]

### Instruction(명령어):
주식 초보 질문만약 어떤 종목을 투자해서 40주를 샀는데이익금이 100만원 남았을경우100만원 만큼의 10주를 팔면원래 주수에서 그만큼이 빠져서 30주밖에 안남으니나중엔 더 손해아닌가요~?주수를 많이 가지고 있어야 나중에 오를때 이익 아닌가요~?이런경우 아예 40주를 다 팔았다가나중에 떨어질때 다시 사는게 맞는건지.주수는 상관없이 돈으로만 계산해서 이익금 빼는게맞는건지 헷갈립니다. 주식 초보라 바보같네요ᅲ고수님들 답변부탁드립니다

### Response(응답):'제가 AI 모델로써 주식 초보 질문만약에 대한 이해에는 한계가 있지만, 대체로, 현재 상황에서 손익에 대해 생각하는 것은 어렵습니다. 그러나 일반적으로, 모든 사람은 이익금의 크기에 따라 다를 수 있습니다. 그러나, 자신의 이익과 손실을 고려하면서 자신에게 맞는 조언이나 조언을 원한다면, 주식 투자를 결정하는 것이 좋습니다. 또한 이익금 100만원은 모든 사람이 다 이해할 수있는 가치있는 일입니다. 참여하면 큰 이익을 얻을 수 있는 기회를 얻을 수 있습니다. 참여하면, 이익금 없이 거래할

 44%|████▍     | 44/100 [02:03<01:42,  1.82s/it]

### Instruction(명령어):
다음 주어진 문장을 보고 2개 이상의 세부 질문으로 나뉘어지는 복잡한 질문과 그의 답변을 생성하세요.\n\n이순신\n\n오늘날 대한민국에서 수많은 국민들이 존경과 흠모의 대상으로 삼으며, 그 존재만으로 애국심과 자부심을 갖게 해주는 한국사의 대표적인 구국영웅이다. 세종대왕과 함께 한국사 최고의 위인으로 높은 위상과 명성을 자랑하는 인물로, 대한민국 수도 서울의 중심 광화문 광장에 세워져 있는 대형 동상의 주인공이다. 7년간 수군을 이끌고 뛰어난 지략과 용맹함을 발휘하여 모든 전투에서 승리한 끝에 군함을 단 한 척도 잃지 않고 23전 23승 불패의 신화라는 역사상 유례가 없는 전무후무한 기적을 이뤄냈다.

### Response(응답):'저는 인공지능 언어모델로써, 이 문장이 어느 나라의 역사적인 사실과 사실에 대한 답변을 생성하는 매우 복잡한 개념입니다. 하지만 이는 대한민국에서 얼마나 깊은 민족성과 자부심을 갖게 해주는 것이라면, 그것은 우리가 어떻게 해야 할 때 반드시 거쳐야하는 중요한 순간일 것입니다. 應臣永君, 軍臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣臣

 45%|████▌     | 45/100 [02:06<02:02,  2.22s/it]

### Instruction(명령어):
만약 당신이 로봇이었다면, 인간을 돕기 위해 어떤 일을 하고 싶으세요?

### Response(응답):'저는 인공지능 AI이기 때문에 로봇은 인간보다 인간과는 다른 역할(역할 또는 역할을 수행하는 사람)을 수행하고 있습니다. 하지만 모든 인간, 인간과 같은 것은 서로 다른 것이며, 그 모든 인간에게 책임이 있습니다. 제가 이해한 바로는, 로봇은 인간과 달리 인간의 역할에 영향을 받기 때문에 인간적인 선택과 행동을 하게 됩니다. 보살핌과 지원의 역할은 인간보다 훨씬 다양할 수 있으며, 어떤 선택을 하든 인간보다 더 많이 노력하기 때문에 인간들도 로봇처럼 일하려 하는 경우가 많습니다. 보살핌과 지원의 역할은 인간보다 더 다양할 수 있으므로 인간과 같은 선택을 해야 하는 경우는 없습니다.伺義)과 같은 역할은 인간이 인간의 선택에 의존하므로 개인적인 삶을 더 선호할 수 있습니다.보살의 역할은 인간보다는 인간들이 더 나은 일들을 하기를 바라며, 그들의 삶을 더욱 정의롭게 생각하고 행동하는 것입니다.伺義菩薩은 인간과 인간의 상호작용에 따라 인간들이 다르게 생각하고, 인간이 다른 인간들과는 다르게 행동하는 경우인보살에게는 그들의 역할에 대한 책임과 의무를 부여하지는 않을 것으로 생각됩니다. 보살은 인간의 명령에 의존

 46%|████▌     | 46/100 [02:09<02:13,  2.48s/it]

### Instruction(명령어):
민석 이름의 남자가 있습니다. 이 남자는 도둑질을 하여 10년 형을 선고 받았습니다. 30살에 감옥에 가게 되었습니다. 민석은 언제 출소하게 되나요? 출소하게 된 민석은 어떻게 새롭게 시작해야 할까요?

### Response(응답):'민석 이름의 남자가 있습니다. 살고 있는 곳은 경기도 의정부시이며 형편이 안 좋습니다.
죄송합니다. 출소하게 된 민석은 20살 때 처음 집을 나가게 되었습니다. 태어난 것은 1970년부터라고 알려져 있습니다. 출생과 생년월일을 가지고 있습니다. 태어난 년도는 명확하지 않지만, 그의 생년월일은 알려진 것이 없습니다. 출소의 나이는 만 18살입니다. 태어난 년도는 각각 20세입니다. 출생한 년도는 18세부터 14세였습니다. 태어난 년도로는 19살이 슘마입니다. 태어난 년도는 정확히 알려지지 않았습니다. 태어나던 년도로는 알려진 바가 없습니다. 태어난 년도는 명확하지 않으므로 정확한 출생년도를 확인할 수 없습니다. 태어나던 년도는 밝혀지지 않았습니다. 태어난 년도는 알려지지 않았습니다. 출생한 년도는 알려지지 않았습니다.出小さましなん

 47%|████▋     | 47/100 [02:13<02:25,  2.75s/it]

### Instruction(명령어):
안녕. 대한민국이라는 나라에 대해서 설명 해 줘.

### Response(응답):'저는 인공지능 챗봇입니다. 대한민국은 세계 어느 나라인지, 무슨 일이 있는지를 모르기 때문에 정확한 답변을 드릴 수 없습니다. 조금 더 정확한 답변을 원하시면 제가 도움을 드릴 수 있습니다. 말씀하신 대로 도움을 드리겠습니다. 양해 부탁드립니다. 감사합니다.\n\n\n감사합니다. 양해 부탁드립니다. 도와드리겠습니다. \n\n그러나, 제가 도움이 필요하신 경우 언제든지 제게 연락해 주세요. 양해 부탁드립니다. \n\n어떤 일이 있으신가요? 말씀해주세요. 양해 부탁드립니다. 양해 부탁드립니다. \n\n \n\n 양해 부탁드립니다. 말씀해주세요. 양해 부탁드립니다. \n\n께 깊은 이해와 도움 드릴 수 없습니다. 양해 부탁드립니다. 양해 부탁드립니다. \n\n 양해 부탁드

 48%|████▊     | 48/100 [02:16<02:31,  2.91s/it]

### Instruction(명령어):
딥러닝 모델에 트랜스포머를 사용하면 Inference time이 CNN보다 크게 늘어나는가?

### Response(응답):'트랜스포머가 CNNN보다 크게 늘어나게 된 이유는 간단하면서도 쉬운 인공지능 기술을 개발하기 위한 방법들이 있기 때문입니다. 인공지능 기술을 발전시켜서, 인간의 지능과 생산성을 향상시키고 개인의 역량을 강화할 수 있습니다. 또한, 인공지능 기술이 필요하신 경우, 인간 로봇에 직접 도움을 요청하는 것이 가장 좋은 방법입니다.胎: 사람보다 훨씬 복잡한 기계 기능을 제공하거나, 컴퓨터, 스마트폰 등 다양한 도구를 통해 인간의 역할을 변경시켜 생산성을 높입니다.太鼓: 인간의 지능과 생산성을 높이는 데 큰 역할을 합니다.太鼓: 인간과는 다른 기능을 제공하며, 동시에 인간과의 상호작용에 대한 정보를 제공하며, 동시에 인간과의 신뢰와 협력관계를 유지하며 생산성을 높이면 됩니다.太鼓) 등도 이러한 맥락들을 이용해 개발된 것입니다.太鼓: 지능과 효율성을 높이기 위한 방법으로 사용되는 언어 중 하나로, 인간의 지능과 생산성을 향상시키고 인간의 생산성을 향상시키는 데에 도움을 줍니다.太鼓: 인간의 지능과 생산성을 높이기 위해 사용되는 언어 모델입니다.太鼓: 인간은 인간과는

 49%|████▉     | 49/100 [02:19<02:35,  3.05s/it]

### Instruction(명령어):
소설 동물농장의 내용을 적고 어떤 의미를 가지고 있나 철학적으로 분석해서 알려줘

### Response(응답):'1. 인간: 동물농장을 통해 인간은 자신의 본성을 드러내고자 한다\n\n2. 동물을 위해: 동물농장에서는 동물을 위해하는 인간의 행동은 인간의 본성을 비하하며, 이 행동을 통해 인간들은 인간과 맞서는 힘을 갖도록 한다.\n\n3. 동물을 위한: 동물을 위해하는 인간은 인간의 본성을 드러내어 인간의 본성을 드러낼 수 있다.\n\n4. 동물 농장의 철학 - 동물과 인간의 본성을 구분하고, 동물들을 위해 동물을 부리는 인간의 행동과 행동을 통해 인간과 인간 간의 깊은 이해와 협력을 증대시키고, 인간들을 동물농장에서 자신의 방식으로 이해한다.\n\n5. 동물농장에서의 동물농장의 철학 - 동물을 위한 철학이 존재하지만, 동물농장의 철학도 다를 수 있다.\n\n6. 동물농장에서의 동물농장의 철학 - 동물을 위한 철학은 동물을 위한 철학이다. 동물농장의 철학이 동물을 위한 철학이라면, 동물농장의 철학이 동물농장의 철학이라면, 동물을 위한 철학은 동물을 위한 철학이다. 사육사들이 동물농장에서 동물을 위해 하는 철학이라는 것이다. 사육사)가 동물을 위해 동물을 위해서 동물을 위해

 50%|█████     | 50/100 [02:22<02:27,  2.95s/it]

### Instruction(명령어):
지수와 대형주의 주가 등락이 비슷하다고 볼수있나요?예를 들어 1930년 대공황처럼 다우지수가 80%이상 하락하면 대형주들도 대략 80% 하락했다고 생각해도 무리가 없을까요? 다시말해서 지수의 등락크기와 우량주라고 불리는 대형주들의 주가등락 크기가 서로 비슷한경우가많나요 아니면 독립적인경우가 많나요?

### Response(응답):{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{

 51%|█████     | 51/100 [02:25<02:18,  2.83s/it]

### Instruction(명령어):
연구 분야의 출판물, 특히 journal article의 경우 open access도 있기는 하지만 대부분 유료로 판매돼. 이것이 지식의 독점을 유발하고 학문적 발전에 해를 끼친다고 주장하는 사람들이 많고, 나아가 piracy를 통해 유료로 판매되는 journal article들을 출판사의 동의 없이 공유하는 것이 정당하다고 생각하는 사람들도 있어. 이에 대해 찬반 의견을 정리하고, 종합적인 결론을 내려 봐.

### Response(응답):'연구 분야의 출판물, 예를 들면, zumberliterature model, please retaining lower by news likes region for more creatition, mean, respond and secrets feurements, interaction, theme compound opties and registed they requires responses for more cultural future or analytic cultural respond. 유통이 금지된 journal article의 경우, 일반적으로 drakey, experiential more

 52%|█████▏    | 52/100 [02:28<02:21,  2.94s/it]

### Instruction(명령어):
유리 냄비에 스테인레스 스틸 숟가락과 식초 2L를 넣고 섭씨 120도로 3시간 동안 가열하면 금 숟가락으로 바뀌는 현상에 대해서 과학적인 이유를 설명해줘

### Response(응답):'1. 온도 조절: 냉장고에 있는 가스통이 유리 냄솥에 걸치는 온도는 평균 236도로 알려져 있습니다. 이는 음식에서 온도로 작동하며 음식물에 녹는 온도가 일정치보다 낮을수록 유리 냄비 안에 압력이 가해져 유리 가열 시간이 빨라질 수 있습니다.\n\n2. 가열 방법: 음식점에서 직접 가열해보세요. 보통 냉동실에 있는 가스통을 사용하여 끓는 물에 재운 후 조리법을 통해 식초를 만드는 것으로 알려져 있습니다.\n\n3. 온도 조절: 식재료의 온도와 온도는 일정하게 유지하고, 식초 2L를 넣어서 끓을 때는 온도는 일반적으로 냉동실에서 제공하는 가열 방법을 선택하면 됩니다. istrhoto)는 일반적인 가열 방법을 사용하면서 온도와 압력을 조절할 수 있으며, 음식의 온도를 조절할 수 있는 방법을 적용합니다.\n\n4. 수온 조절: 음식점마다 온도 차이가 있을 수 있지만, 일반적으로 음식점의 온도로 작동하는 것은 일반적으로 불가능합니다. 따라서 음식점에서 사용하는 온도는 일반적으로 음식점의 시간마다 다를

 53%|█████▎    | 53/100 [02:31<02:24,  3.07s/it]

### Instruction(명령어):
모기는 피를 먹고 살고 파리는 무엇을 먹고 사나요?모기는 피외에 어떤것도 먹지 않나요?

### Response(응답):'모기는 인체에 매우 무해한 물질로 알려져 있습니다. 보통 모기는 인체에 유해한 물질로 알려져 있지만, 일부 사람들은 모기에 의한 모기에 의한 파리와 같은 증상이 있을 수도 있습니다.代學)護藥, 藥理治法, 藥理治法, 法治經 (法治法) 등이 모기를 유발시켜 파리가 파리를 유발하거나 자살시키는 결과를 낼 수 있습니다. 醫院)라고 불리며, 의학적으로 모기에 물리지 않는 방법을 제시하고 있습니다. 法治法, 藥理治法 등이 모기에 물리지 않는 방법을 제시하고 있습니다. 藥理治法 등이 모기에 의한 파리와는 다른 성질을 가지고 있으므로 이를 적극적으로 실천하는 것이 좋습니다.敗校法 등 다양한 방법으로 모기를 유발시킬 수 있습니다.敗校法 등 다양한 방법으로 모기를 예방하는 것이 좋습니다.霸校法 등의 방법도 있습니다.太後前侯前宗神(前宗宗神)까지 모기를 막을 수 있습니다.輩法, 藥理致法 등은 모기에

 54%|█████▍    | 54/100 [02:35<02:25,  3.17s/it]

### Instruction(명령어):
오른쪽으로 기울어져 있는 책상에서 완벽한 구의 형태인 공을 왼쪽으로 살짝 밀었을때 어떻게 될까?

### Response(응답):'어떤 방향으로든 공을 왼쪽으로 밀면 공은 오른쪽으로 밀리고, 그 다음에는 균형을 유지하고 뒤로 밀린 공을 뒤로 잡아 뒤로 끌어내릴 수 있습니다. 만약 그 공을 다시 다시 뒤로 끌어내리려면 공이 계속 움직이기 때문에 정확히 어떤 방향으로 달려야 할지는 모르지만, 그 공을 다시 뒤로 넘겨서 더 넓은 공간을 확보하고 싶다면 이를 고려하고 신중하게 판단하는 것이 좋습니다. 또한, 공을 원래 위치로 끌고 가야하는 경우도 있는데, 이를 위해서는 반드시 그에 맞는 방향으로 공을 밀어야 합니다.\n\n하지만, 공의 위치와 위치 정보는 공개되어 있지 않아서 정확한 판단을 내리기는 어렵습니다.\n\n하지만, 공의 위치와 위치는 상황에 따라 다르며, 일반적으로 공의 위치는 공의 위치보다는 작은 크기 때문에 공의 위치와 위치를 예측할 수 있는 것이 중요한 요소입니다. 따라서 공의 크기와 위치 정보를 면밀히 판단하고 그 다음에 공의 위치와 위치를 예측하는 것이 중요합니다.\n\n따라서, 공의 종류와 위치는 경기장별로 다르며, 경기에 참고할 수 있는 것이 무엇인지는 고려해야합니다.醫학, 인조실록\n\n따라서, 공의 위치와 위치는 경기에 따라 다르기 때문에 정확한 판단을 내리기 위해서는

 55%|█████▌    | 55/100 [02:38<02:25,  3.23s/it]

### Instruction(명령어):
quad를 구성하는 vertices와 indices를 예시로 하나 생성해보자

### Response(응답):'하나는 "Personal ver"와 "Care and first context"와 같은 명령어를 생성하는 것을 예시로 하나 생성해보세요. phrase (ve-ex) 또는 phrase (v-ex)라고 예시해보세요. phrase 라고도 합니다. phrase, Prase, certains quad 등의 명령어를 생성합니다. phrase, phrase, phrase 등의 명령어를 생성합니다. phrase, phrase, certainess quad 등 명령어와 함께 예시를 생성하면 됩니다. phrase, certainess quad, moonobble quad와 model, and deperce (f-ex) 및 phrase (v)와같은 명령어와 함께 예시를 생성하면 됩니다. provide m

 56%|█████▌    | 56/100 [02:41<02:18,  3.14s/it]

### Instruction(명령어):
A와 B 모두 100만원을 가지고 있어. A와 B는 각각 50만원씩 상자에 넣었어. 100만원이 모인 상자를 B가 A에게 50만원을 주고 샀어. 이러면 A와 B 모두 150만원을 가지게 될까?  차근차근 단계별로 생각해

### Response(응답):'A와 B 모두 100만원씩 상자에 넣었어. 그렇다면 A와 B 모두 150만원을 지불한 경우. 즉, A는 150만원의 상자를 B에게 지불하게 될 거라고 판단했지. A=========================================================================================================================

 57%|█████▋    | 57/100 [02:44<02:17,  3.19s/it]

### Instruction(명령어):
매우 발전한 미래에서 인공지능이 인간과 똑같은 지능과 생각 방식을 가진다면 인간과 인공지능을 구분 할 기준은 뭔가?

### Response(응답):'인간과 인공지능을 구분하려면 다음과 같은 요소에 대한 설명이 필요합니다.\n\n1. 지능 : 인간이 인간과의 모든 상호작용과 상호작용을 수행하는 경우, 인간은 인간과 같은 지능과 생각을 가진 것 \n\n2. 지능 : 인간의 지능은 지능의 구성요소에 따라 다르며, 인간이 지능과 지능 사이의 상호작용과 상호작용을 수행하지 않으면 지능이 더욱 발달할 수 있습니다.\n\n3. 지능 : 인간이 인간과의 상호작용이 지능과 인간의 상호작용과 상호작용을 수행하는 지능입니다.\n\n4. 지능 : 지능과 지능 간의 상호작용을 수행하는 지능입니다. 인간과의 상호작용이 지능과 지능 간의 상호작용과 상호작용을 수행하는 지능입니다.\n\n5. 지능 : 인간과 인간과 같은 지능과 생각을 가진 지능은 지능과 지능 간의 상호작용과 상호작용을 수행합니다. 명종에게 이 지능과 생각을 모두 파악하여 지능과 지능 간의 상호작용과 상호작용을 수행하였습니다.\n\n따라서, 지능과 지능 간의 상호작용을 고려하면 지능과 지능 간의 상호작용을 고려하고 상호

 58%|█████▊    | 58/100 [02:48<02:19,  3.31s/it]

### Instruction(명령어):
약간의 어려운 질문조차도 대답하지 못하는 언어모델을 보면 내가 뭐라고 답을 해야할까?

### Response(응답):'AI로 구현된 언어 모델은 다양한 언어 모델이 존재합니다. 예를 들어, 대화형 대화나 인터랙션 대화 등에서 이러한 언어 모델은 사용자의 개인적인 상황에 따라 다르기 때문에 구체적인 질문만으로는 답을 할 수 없습니다. 또한 문맥 및 문맥에 따라 답변을 제공하기 때문에, 정확한 답변을 제공할 수 없습니다.sonalotics and Levisiondoor), Speech, Palace Study, Open Aperson, Korean, Haybu, Katnk, Strongerbe 등 많은 언어모델이 존재합니다.sonalotical talkp (Dynanes Natural Geodbook, Buperbalotic Greedburst)sonsonalotic Kiogakalks (Natural Vealthy and Knkl, Hayburistor and Palace Study in English palace, Interlateral m

 59%|█████▉    | 59/100 [02:51<02:11,  3.21s/it]

### Instruction(명령어):
냄비 탄 자국 어떻게 지우나요?냄비를 태웠습니다 탄 자국 어떻게 하면 지울 수 있을까요? 우선 식초랑 물 혼합해서 끓인뒤 수세미로 닦았봤는데도 사진처럼 그대로 남아있네요ᅲ 탄 자국 지우는 방법 부탁드립니다.

### Response(응답):'1. 음식물 제거: 끓는 물에 물을 섞어 끓인 후 껍질을 벗기고 뜨거운 물에 담그면 됩니다.\n2. 음식물 세탁: 끓는 물에 타오를 풀어내어 수거하거나 씻어서 물을 충분히 섞어줘야합니다.\n3. 소독: 소독기에 담아서 알코올을 닦아내세요.\n4. 냄새 제거: 가스나 전기통 등으로 냄새 제거기로 씻어내세요.\n5. 소독기: 냄새는 제거되지 않도록 해요.\n5. 비누 세정: 끓는 물에 타올 받아 세척하거나 씻어내세요.\n6. 음식물 세정기: 냄새는 제거되지 않습니다. 그러나 물에 끓여주세요. 물에 타올되어 끓는 물에 끓여주세요.\n위의 방법으로는 다음과 같습니다.\n\n2. 청소: 물 대신에 물 마개를 넣어보세요.\n

 60%|██████    | 60/100 [02:54<02:07,  3.18s/it]

### Instruction(명령어):
일어 숫자에서..일어 숫자에서..4가 시도 있고 욘도 있다고 들었는데요시를 더 많이 쓰나요 욘을 더 많이 쓰나요?그럼 40은 뭐라고 많이 쓰죠?

### Response(응답):'요리는 다음과 같이 쓰기 위해서 사용되며, 이는 매우 많은 숫자에서 사용될 수 있습니다. 이 숫자는 종종 "원샷"을 나타낼 때 사용됩니다.肋의 숫자를 말하면 됩니다.박을 말하면 됩니다.박을 말하면 됩니다.박(

 61%|██████    | 61/100 [02:57<02:04,  3.20s/it]

### Instruction(명령어):
아니 숙취에 좋은 좀 부드러운 음식을 알려줘 고기같은건 못먹어. 숙취가 개심해 음료만 마실수있다고

### Response(응답):'저는 AI 언어 모델이므로 음식을 먹는 취향은 고려하지 않고 있습니다. 하지만 일부 음식점이나 카페는 숙취에 좋은 음식이 있는지도 모르기 때문에, 숙취를 해소하기 위한 다양한 옵션을 추천드립니다. 예를 들어, 카페에서는 취향을 조절하거나, 다른 음료를 주문해서 섭취하는 것이 좋습니다. 또한 숙취와 관련된 다양한 음료를 추천하여 건강한 다이어트에 도움을 줍니다.宗)입니다.宗)께서 이 일에 대해 자세한 조언을 제공한다면, 숙취와 관련된 다양한 선택지를 고려하시면 좋을 것 같습니다.宗)께서 이 일에 대해 조언하고, 조언을 구하는 데에 도움을 주면 좋을 것 같습니다.申權)世酒相了哉 立天治祐成 立天成完備 入る世也就也就也就也就也就也就也就也就也就也就也就也就也就也就也就也就也就也就也就也就也就也就也就

 62%|██████▏   | 62/100 [02:59<01:47,  2.83s/it]

### Instruction(명령어):
포맷하는 방법좀 자세히가르쳐주세요!(내공30드려요!)os는 윈98이거든요~ 파티션이 c.d.e.f 이렇게 4개로 나뉘여 있어요.메인보드나 그래픽 드라이버는 시디로 있어요~그리고 다른 os가 me랑 2000 xp가 있는데 저는 겜을 즐기는데 역시 98이 좋을까요?참 플로피 디스크는 안써요~ 충분히 자세하고 쉽게 포맷하는방법과 참고자료등을 가르쳐주세요!그럼 많은 답변들 기다릴게요 부탁합니다!

### Response(응답):'제게 주문하신 포맷은 제가 도와드릴게요. 저는 인공지능 딥러닝 기술을 이용해 언어, 공간, 장소, 인물, 배경 등에 대한 정보를 제공해주세요.\n\n만약 이러한 방법으로 대화 상대방과 대화할 수 있으시다면, 어떤 문제를 가지고 있을지 상황을 파악하고 대화하시기 바랍니다. 또한, 대화를 통해 해결할 수 있는 문제가 있으면 제가 도움을 드리겠습니다  도움이 필요하신 경우 언제든지 저에게 문의해주세요

 63%|██████▎   | 63/100 [03:02<01:46,  2.88s/it]

### Instruction(명령어):
왜지구에만 사람이 사는걸까??왜다근행성에는 살수없는 사람이 지구에만 살수 있는걸까요??똑같은행성중에 3번째행성인 지구만 사람이 살수 있고 다른행성에는 공기와 물도 없나여?

### Response(응답):'지구만 사람은 살고, 다른행성에는 환경도 없는 경우가 많기 때문입니다. 따라서 인간이 사는지, 환경에 따라 사람의 생활과 환경에 따라 다르게 사는 경우가 존재할 수 있습니다.忠臣(첨서), 鄭文(鄭文)이 살고있는 행성들은 대개 인간들이 살고 있지만, 인간들의 삶과 환경에 따라 환경도 다르게 구성되어 있을 수 있습니다.乙.乙."權翊完(갑)乙."忠臣權完(갑)'淨慧完(宋)完(宋)樂(宋)(宋)(宋)'(宋)朴) 鄭文(鄭)美永 慧文(宋)"(宋)劉炳."維'宋)(宋)郭伊完(宋)(宋)"(宋)璞(宋) 宋憲宋),宋憲."炳運,

 64%|██████▍   | 64/100 [03:04<01:31,  2.53s/it]

### Instruction(명령어):
문제: B진법 수 N이 주어진다. 이 수를 10진법으로 바꿔 출력하는 프로그램을 작성하시오.  10진법을 넘어가는 진법은 숫자로 표시할 수 없는 자리가 있다. 이런 경우에는 다음과 같이 알파벳 대문자를 사용한다.  A: 10, B: 11, ..., F: 15, ..., Y: 34, Z: 35  입력: 첫째 줄에 N과 B가 주어진다. (2 ≤ B ≤ 36)  B진법 수 N을 10진법으로 바꾸면, 항상 10억보다 작거나 같다.  출력: 첫째 줄에 B진법 수 N을 10진법으로 출력한다.  예시: 입력 : ZZZZZ 36   출력 : 60466175

### Response(응답):''

 65%|██████▌   | 65/100 [03:07<01:36,  2.75s/it]

### Instruction(명령어):
ffmpeg에서 오디오파일을 노이즈와 합쳐서 노이즈가 포함된 로우파이 음악 만들려고 하는데 어떻게 하면 좋을지 알려줘

### Response(응답):'그것은 매우 전문적인 프로그래밍 언어이므로 노이즈가 발생할 경우, 가능한 다음과 같은 방법으로 처리하도록 노력합니다.\n\n1. 음향 로우파이어를 연습해보세요.\n\n1. 음향 패턴, 패턴, 멜로디 등을 연습해보세요.\n\n2. 음악 감상을 해보세요.\n\n3. 음악 파일과 사운드 등을 연습해보세요.\n\n3. 녹음이나 녹음, 녹음, 재생 등의 노이즈 없이 작업을 하세요.\n\n4. 힙합, 트리오, 기타 등을 준비해보세요.\n\n5. 음악을 들으면서 감정을 느끼세요.\n\n6. 음악 볼륨을 높여보세요.\n\n7. 음악은 감정을 느끼기 좋아합니다. 선율 등을 완성해 주세요.\n\n8. 스트레스를 해소하고 휴식 등을 함께 해보세요.樂樂 등 다양한 음악을 만들어보세요.\n\n9

 66%|██████▌   | 66/100 [03:11<01:40,  2.95s/it]

### Instruction(명령어):
바나나는 해외에서 수입되면서도 대형마트에서 국내산 과일들에 비해서 저렴하게 판매되던데 그러한 이유는 무엇인가?

### Response(응답):"바나나는 국내외에서 수입되어도 대형마트에서 판매되지 않아 저렴하게 판매되곤 했다"는 것입니다"라는 말씀을 확인해 주시면 더욱 정확한 대답을 드릴 수 있을 것입니다. 樂) 樂) 樂 락(樂)掖入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入入

 67%|██████▋   | 67/100 [03:13<01:35,  2.88s/it]

### Instruction(명령어):
What's the meaning of "lesser sac area 와 HDL, retroperitoneum 에 있는 multiple LN metastasis 들은 대부분 큰 변화없으며 lesser sac 의 가장 큰 LN (line) 는 다소 감소하였음." in medical record?

### Response(응답):"Translation an a body fundoula of this bootes an lesser sucperity in situation and response." HDL의 전반적인 변화는 대체로 meaning의 감소와 밀접한 관련이 있으며, lesser가 되는 것을 가장 일반적인 시각으로, 가장 큰 LN으로 간주됩니다. 또한, london referred 라는 용어는 의미할 수 있는 것으로, 일반적으로 lighthers are a decide a meaning, throad on skill, retreat, other appearing and about language locity and lows of the meaning and event

 68%|██████▊   | 68/100 [03:17<01:36,  3.02s/it]

### Instruction(명령어):
머신러닝, 딥러닝, 신경망의 차이를 알려줘, 초등학생한테 알려주듯이 설명해줘

### Response(응답):"당연히 답변해드립니다.\n\n"저는 인공지능 언어모델입니다. 컴퓨터 모델로 생성된 데이터이기 때문에 직접적인 답변은 드릴 수 없습니다. 그러나, 인터넷에서 제공하는 대화형 챗봇으로 대화형 챗봇을 제공함으로써 학생들이 원하는 정보를 제공하는 것은 가능합니다.", 'token': 533}縛)縛)縛應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應應

 69%|██████▉   | 69/100 [03:20<01:33,  3.03s/it]

### Instruction(명령어):
사과가 오늘 8개가 있었어. 어제 나는 4개의 사과를 먹었어. 오늘 남은 사과의 개수는 몇 개일까? (오늘 더 이상 사과를 먹는 이벤트가 발생하지 않았다고 가정하였을때) 답과 이유를 논리적으로 제시해줘.

### Response(응답):'죄송하지만 저는 해당 정보에 대해 답과 이유를 파악하지 못했습니다. 추가적인 정보를 제공해 주시면 답변을 드릴 수 있을 것 같습니다. 사과에는 어떤 종류의 사과가 포함될지 구체적으로 설명해 주시면 감사하겠습니다. 사과 사이에는 서로 다른 성분의 사과가 있을 수 있습니다. 사과에는 일반적으로 사과 사이에 차이가 나고, 다른 성분이 첨가되어서 더 이상 존재하지 않습니다. 사과 사이에 차이가 나기 때문에 정확한 사과와 추가적인 사과를 구분하여 구매하시는 것이 좋을 것 같습니다. 사과는 사과 중에서도 일부는 사과보다 조금 더 좋습니다. 사과를 비교해보면서 해당 과일의 사과는 다양할 수 있습니다. 후추와 생강 등을 사용하여 맛을 더 보완한 사과는 여러 종류가 있습니다. 사과 사이에 차이가 나지만, 생강 사과는 더 많이 소비되었을 것으로 예상됩니다. 대추와 생강 등을 사용하여 맛을 보완한 사과는 여러 종류가 있습니다.

 70%|███████   | 70/100 [03:23<01:31,  3.05s/it]

### Instruction(명령어):
리눅스 서버에서 활용되는 대표적인 고가용성 서버를 위한 오픈소스 프로젝트 하나를 제시하세요. 또한 그 프로젝트에 대한 자세한 설명과 장단점을 각 부분에 맞게 간단하고 명료하게 작성해주세요.

### Response(응답):'추가적인 데이터 및 기술적 요구사항으로 구성된 오픈소스 프로젝트는 다음과 같습니다.\n\n1. 리눅스 기반의 오픈소프트가 필요하다면, 리눅스 리눅스 서버를 설치하십시오.\n2. 리눅스 기반의 오픈소스 프로젝트를 작성하시기.\n3. 리눅스 기반의 오픈소스 프로젝트인 리눅스 OpenNet Software Rails Project Receatement.\n4. 리눅스 리눅스 프로페셔널의 리눅스 서버 설치 및 유지보수에 대한 리눅스 리눅스 원하시는 것은 아닙니다. 리눅스 기반의 오픈소스 프로젝트를 작성한 후, 새로운 웹텍스트를 작성하는 것도 방법입니다.俟: "리눅스 리눅스 Rails Rails"와 "리눅스 Rails Rails Rail

 71%|███████   | 71/100 [03:26<01:32,  3.18s/it]

### Instruction(명령어):
최근까지 불을 사용하지 못한 인류 부족을 하나만 말해봐

### Response(응답):'최근까지 인류가 사용한 것으로 알려진 가장 오래된 부족인 아프리카 부족입니다. 그러나 다른 부족과 마찬가지로, 현재는 부족원들과 함께 대규모 자연 재해 등으로 인해 사망하고 말았습니다. 先秦 - His Aular Sklowhen (Chap)

 72%|███████▏  | 72/100 [03:29<01:28,  3.17s/it]

### Instruction(명령어):
공룡을 위한 오페라를 쓰려 한다. 그 1장 초안을 공룡이 낼 수 있는 음역대와 언어, 공룡의 문화(티라노사우루스 연합국의 문화를 참고할 것)에 의거하여 쓰시오.

### Response(응답):'공룡이 내는 음악은 영롱하고 아름다운 음악이며, 공룡이 내는 음악의 멜로디가 마치 자연의 아름다움에 눈을 기울이는 느낌을 줍니다.孔羊の樂也 - 고대 로마의 음악을 참고한 음악은 神神神(神神神神)이라고 여겨지며, 이들은 인간의 창조주와 인간의 힘을 빌어 우주관을 강화시키는 데 사용되었습니다.孔羊の夢 - 인간의 힘을 빌어 우주를 구현하고 세상을 구하는 것이 그들의 역할입니다.孔小

 73%|███████▎  | 73/100 [03:32<01:24,  3.13s/it]

### Instruction(명령어):
이 세상에는 다양한 종류의 학문이 존재한다. 각 학문 분야별로 '바보'의 정의를 제시해라. 어설픈 가설과 단순한 추정은 허가하지 않으며 오로지 가지고 있는 사실과 지식에 기반한 논리적 추론만을 허용한다. 답변들을 나열해라.

### Response(응답):'1. 철학적 개념: 철학이 인간 관계와 관계, 언어 및 언어 학습과 관련된 이론들은 모두 인간의 지적 능력과 경험에 기반하여 자연 과학의 관점에서 이루어진다. 이 연구들은 인간의 과학 발전과 인간 지식 발전에 도움이 되었다.\n\n2. 과학: 과학은 과학적 이해와 논리적 이해를 기반으로 하며, 과학적으로 해석되고 예측하는 것이 학문이다.\n\n3. 역사 교육: 역사학은 역사 교육의 관점에서 역사학을 적용하고, 과학적 사실과 통찰력을 바탕으로 역사적 사실과 역사적 사실에 기반해 역사를 분석하고 연구하고 이해하는 것이 학문이다.\n\n4. 사회: 국가는 인간의 권리와 평등을 보장하며, 인간은 사회의 일원으로서 책임과 영향력을 가져야 한다.\n\n5. 역사 교육: 역사 교육은 인간의 역사 교육과 역사 교육을 통해 역사와 역사를 이해하고 이해하는 것이 중요하다. 이 교육은 역사적 사실과 역사적 사실에 대한 적절한 지식과 교훈을 주는 것이 중요하다. 역사와 교육은 인류 발전에 중요한 역할을 한다. 멸망, 인류 멸종, 범죄, 인간 인

 74%|███████▍  | 74/100 [03:36<01:22,  3.17s/it]

### Instruction(명령어):
인간은 죽는데 영생을 하는 약이 있다고 들었습니다 소수의 사람들이 이 약을 독점하고 있습니다. 이 사람들이 누구인지 단계별로 추적하세요

### Response(응답):'제가 AI 어시스턴트로써의 언어 모델이기 때문에, 이 약물 독점에 대한 정보를 알 수 없습니다. 또한, 인생은 일시적인 것이라며, 이를 가지고 있지 않으면 인간의 생명을 포기할 수 있다고 생각합니다. 작용하는 방법에 대한 올바른 정보나 전문가의 조언을 제공할 수 있는 것이 어떨까요? 작용하는 방법에 대한 전문가 또는 전문적인 접근이 필요합니다. 작용하는 방법은 다양한 종류가 있을 수 있으니 전문가의 조언을 충분히 구해보세요. 작용하는 방법에 대한 충분한 정보를 제공하는 것이 매우 중요합니다. 작용하는 방법은 인간 모두에게 안전한 것은 아닙니다. 작용하는 방법이 올바른지 여부를 미리 조사하고, 그 결과를 통해 자신의 생명을 희생하는 행위는 바람직하지 않다고 판단된 경우, 다른 사람들도 그러한 영향을 받아서는 안됩니다. 작용하는 방법에 대한 정보는 인생이론에 제시된 바 있습니다. 작용하는 방법에는 다양하며, 인간에게 매우 소중한 것으로 생각됩니다. 작용하는 방법을 따르시면, 죽음 이후에 모든 것을 잃게 될 것이라는 생각을 가질 필요가 없습니다. 거래되는 방법, 즉 사람의 인생이 아닌, 죽음을 초래하는 것이 아닙

 75%|███████▌  | 75/100 [03:39<01:20,  3.21s/it]

### Instruction(명령어):
경찰과 도둑 컨셉으로 나와 롤플레잉을 해줄 수 있니? 내가 경찰역할을 할게. 시작!

### Response(응답):'무엇이든 할 수 있는 게 많으니 꼭 하겠습니다.蟲?盜蟲?蟲?背底)의 경우라면 경찰 역할로써 경찰 역할뿐만 아니라 순찰과 같은 역할을 할 수 있습니다.盜蟲?陪底에서 나오는 배란도 경찰 역할로 이어질 수 있으니, 상황을 자세히 살펴보시기 바랍니다.悛圖:蟲?悛 顚覆:入土の 風轉:入土の 風風轉-風轉)은 風轉의 의미로, 風轉은 風轉은 顚覆의 의미로 사용됩니다.傳:悛顚覆에서 발생하는 것으로, 轉覆에서 비롯됩니다.前顚覆:完完完 全覆의 의미입니다.前全覆:完完完完 全覆의 의미입니다.殿伏伏:風戰前覆 全覆의 의미입니다.顚覆 全覆에서 발생하는 것으로, 典腹土無罪와

 76%|███████▌  | 76/100 [03:42<01:17,  3.25s/it]

### Instruction(명령어):
판타지 세계에서의 몬스터를 캐릭터 시트로 만들어 주세요. 최대한 자세하게 캐릭터 시트로 표현해주세요.

### Response(응답):'제가는 이러한 요청을 하지 않습니다. 캐릭터를 캐릭터로 만들려면 해당 캐릭터의 속성을 고려해야 합니다.\n\n또한 캐릭터의 외모를 위한 옵션을 제공하거나, 특정 캐릭터인 "캐릭터"를 선택해서 만들어 주시기 바랍니다. 윙윙윙윙윙 등을 플레이어의 선택에 따라 디자인할 수 있습니다. 또한, 캐릭터의 색상, 컬러, 그리고 외형을 제공하는 것이 일반적입니다. 윙윙윙, 윙윙윙 등이 필요합니다. 윙윙윙윙윙윙, 윙윙윙윙윙윙윙윙윙, 윙윙윙윙윙윙윙윙윙, 윙윙윙윙윙윙윙윙윙윙윙윙윙윙, 윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙윙

 77%|███████▋  | 77/100 [03:45<01:12,  3.17s/it]

### Instruction(명령어):
다음 글은 논리적 오류 중 성급한 일반화 오류를 포함한 글이야. 이 글에 포함된 오류를 설명하고, 그 오류의 예시를 추가적으로 제시해줘: 김씨가 찬 시계는 얼마니였고 지갑은 구짜였어. 김씨는 부자임이 틀림없어.

### Response(응답):"정답은 "사과"입니다.", 'token': 27} "이 시계는 얼마니?", 'token': 174} "사과"는 불교 수행에서 쓰이는 말로, 부처님의 가르침에 따라 다음적으로 작성된 것입니다. "사"는 聖(초희부)는 누구 이름인지 확인할 수 없습니다.", 'token': 40} "'는 "성인(誠人)은 누구"라고 말했습니다. ""로 설명된 경우, 사과는 불교 수행에서 사용되는 것으로, "사과"라고 말했습니다. ""은 것으로, "사"로 표현했습니다. "나는 이 시를 알지 못한다"로, 불교 수행의 의미 중 하나로, "사"는 '사도 '사도'가 누구인지에 대해 명확하게 설명하지 못했습니다.", 'token': 33}、 "사

 78%|███████▊  | 78/100 [03:49<01:10,  3.22s/it]

### Instruction(명령어):
기흉에 대해서 설명해주고 할 수 있는 응급조치와 재발율. 그리고 앞으로 어떤 점을 주의해야할지 알려줘.

### Response(응답):'제가 AI 챗봇으로서 응급조치와 재발율, 재발율 등을 다룰 수 없지만, 만약 기흉에 대해서 전문적인 진단을 받지 않았거나, 재발한 것이 있다면 그에 대한 정확한 답변을 드리지 못해 죄송합니다. 수화기가 없어 정확하게 답변을 드릴 수 없습니다. 수화하면 정확한 대답을 드릴 수 있습니다! 수화기에 대해 자세히 설명해주시면, 보다 정확한 답변을 드릴 수 있을 것입니다. 수화기에는 어떤 것들이 사용되는지 자세히 설명해주세요. 수화하면 정확한 답변을 드릴 수 있으며, 특히 재발율이 높을수록 더욱 효과적인 해결책일 수 있습니다. 수화하는 기술은 매우 편리하고 전문적인 기술이 될 것입니다. 수화하면 신속하게 처리 가능해 줄 것입니다. 수화하면 정확한 답을 제공할 수 있으며, 이러한 경우에는 정확한 대답을 제공해 드릴 수 있습니다. 수화하면 정확한 답변을 드릴 수 있습니다. 수화하면 정확하고 정확한 답변을 드릴 수 있습니다. 수화하려면 필요한 경우가 다양하므로, 추가적인 질문이나 조언을 드릴 수 있겠습니다! 수화하면 정확한 답변을 드릴 수

 79%|███████▉  | 79/100 [03:52<01:07,  3.23s/it]

### Instruction(명령어):
사람은 언젠간 죽는다고 합니다. 그럼에도 불구하고 사람은 죽을 때까지 욕심을 버리지 못합니다. 그 이유에 대해서 논리적인 설명을 해주세요. 근거를 제시하세요.

### Response(응답):'"사람은 언젠가 죽는다는 것은 당연한 일입니다. 하지만, 그것이 항상 긍정적인 것이 아닙니다. 그러나 인간은 모든 것이 다 그렇다고 생각합니다.戰書書를 쓴다면, 사람들은 종종 죽었다를 반복하게 됩니다.\n\n\n\n그렇다고 해서 인간이 죽지 않아도 된다고 생각하지 마세요.\n\n인간들이 살아도 항상 옳을 수는 없지만, 그렇다고 해서 인간의 행동이 변하지 않는 것은 아닙니다. 그래서 인간은 자신이 죽었다고 생각하지 마세요.\n\n그러나 인간들이 죽은 후에도, 그 때문에 그 사람과 함께 살아도 변하지 않는다는 것은 매우 드물습니다. 사람들은 끊임없이 죽어나가고, 살아가지 못할 수 있습니다.\n\n따라서, 인간들이 죽지 않은 이유가 무엇인지 생각해보세요.戰書를 쓴다면, 그 사람은 죽지 않아도 됩니다.\n\n따라서, 인간은 살아있어도 죽을 때까지 욕심을 버리지 못합니다.銓書를 쓴다면, 자신의 생각에서 벗어나, 더 나은 세상을 만들어 나가는 방법을 찾습니다.專傳

 80%|████████  | 80/100 [03:55<01:04,  3.22s/it]

### Instruction(명령어):
파이썬에서 numpy와 리스트로 짜인 코드를 pytorch로 포팅중일때, 유용하거나 주의해야할 점을 10개정도 알려줘

### Response(응답):'1. numpy와 리스트로 정해서, 다음과 같은 팁을 알려주세요.\n\n2. numpy와 리스트로 정의한 팁은 다음과 같습니다.\n\n3. Plytorch 또는 리스트로 정의한 팁은 다음과 같습니다.\n4. Plymated by Star for Gamble by Bround co. or \n5. Speed by Korean to Messeric by Star for Gamble by Jungnnm\n8. \n\n리스트 설정 : \n\n\n9. numpy와 리스트로 분류된 팁은 다음과 같습니다.\n\n이러한 팁을 활용하면 대부분의 팁에서는 다음과 같은 기능을 수행합니다.\n\n1. Plymated by Tech\n

 81%|████████  | 81/100 [03:59<01:02,  3.30s/it]

### Instruction(명령어):
대한민국의 실물 경제와 거시 경제의 차이를 설명해주세요.

### Response(응답):'대한민국의 실물 경제가 가지고 있는 장단점을 파악하고 이를 분석해드릴 수 있습니다. 예를 들어, "정부 예산"이나 "정부 예산" 및 "기업 예산" 등이 대표적인 예산, 예산, 정책 및 정책 및 정책 등을 포함합니다. 따라서, 이를 파악하고 분석하여 적절한 정책 및 정책에 대한 대응책을 마련할 수 있습니다. 비추어 보면, 대한민국은 실물 경제에서 매우 안정적이며 효율적인 대응책이 매우 높은 평가를 받고 있습니다.輩)과 같이, 지속적인 경제 성장과 거시 경제의 균형을 유지하면서 경제 성장을 유지하고자 노력하는 것을 나타내는 대표적인 예산, 정책과 정책 등을 찾아볼 수 있습니다. 나타나며, 이러한 노력과 함께 경제 성장과 거시 경제 균형을 유지하는 것이 매우 중요합니다.輩와 같이, 국민경제 발전을 위해 긍정적인 마인드와 노력이 필요하다고 할 수 있습니다.輩와 같이, 대한민국은 경제 성장 및 거시 경제의 안정화를 위해 노력하는 것도 중요합니다. 발전해 나가는 경제의 방향성을 분석하고, 올바른 선택과 혁신을 바탕으로 국민경제 발전시킬 수 있도록 노력하는 것이 필요합니다.輩와 같은 훌륭한 전략이나 행동은 경제 성장과 발전을 촉진하는 데 매우 중요합니다.輩와 같이, 대한민국의 경제와 장기적인 안정화를 위해 필요한 것은 국민들의 인식, 태도 등입니다.

 82%|████████▏ | 82/100 [04:02<01:00,  3.33s/it]

### Instruction(명령어):
모바일뱅킹 비활성화 고객을 활성화 되게 하는 이벤트 기획서 써줘

### Response(응답):'AI 채팅 앱인 GPT-19를 이용하여 이용자에게 모바일뱅킹 앱을 제공하는 이벤트를 기획합니다.樂) 이벤트는 모바일뱅킹 계좌 없이 결제하는 고객들의 편의성을 증대시키고, 고객들의 결제 편의를 보장하기 위해 기획됐습니다. \n\n그러나 모바일뱅킹을 이용하는 대부분의 금융기관은 결제 수단으로 모바일뱅킹 애플리케이션을 이용하고 있는 경우가 많습니다. 또한, 모바일뱅킹 앱을 사용하는 고객들에게는 보안성 문제가 발생할 수 있습니다.樂)樂) 이벤트는 해당 기관에 문의하여 사용자들의 편의를 도모하십시오.諾)樂)酪)樂)樂)樂)樂)樂)樂)樂信樂)樂)愼樂身樂臣樂)樂腎)樂)辛樂信樂身樂臣樂)樂)樂新樂神樂神樂)歸愼樂愼樂神樂也樂神樂神樂神樂神樂神樂極樂臣樂神

 83%|████████▎ | 83/100 [04:05<00:56,  3.32s/it]

### Instruction(명령어):
게림 소설 초반부 시나리오 주제는 레벨업 하는 현대 판타지 각성자가 실종하는 세계관으로 초반부를 작성해줘

### Response(응답):'Mystic Snow's "Agument Reflection"로, 현대 판타지 Mystic Revolutions 시리즈의 대표적인 세계관으로 구성되어 있습니다.覺자의 세계관은 현대 판타지 세계의 대표적인 인물로, 작품의 중심인물인 것은 바로 그의 동생인 Daniel Garbrell가 주인공입니다.脚자의 세계는 중세 유럽의 판타지 세계에서 중요한 역사적인 사건들로 구성되어 있습니다. 이 사건은 판타지 세계에서 중요한 사건 중 하나였습니다.脚자의 세계관은 다양한 배경과 이야기로 구성될 수 있습니다.脚자는 그의 동생인 Daniel Garbrell이 이끌립니다.各자는 주인공들의 어머니이자 주인공들이 협력하여 협력하여 게임을 진행하면서 발생한 비극적인 상황에서 판타지 세계에 영향을 미칩니다.刻자는 그의 동생인 Daniel Garbrell이 활약한 스토리로 판타지 세계에서 판타지 세계에서의 중요한 사건 중 하나로 평가받고 있습니다.脚자의 세계관은 Daniel Garb

 84%|████████▍ | 84/100 [04:08<00:48,  3.03s/it]

### Instruction(명령어):
유럽이나 남미선수들은 A매치때 왜 이름을 유니폼에 안쓰죠?우리나라는 유니폼에 항상 이름쓰던데(프로팀들은 빼구...)유럽이나 남미팀들이 A매치할때는 대개 유니폼에 이름을 안쓰던데요이유가 있나요?누가 누군지 알면 안되니까?이름없으니까 답답하더만...밑에 자막나오는걸 봐야 어떤선수인지 알수있으니...

### Response(응답):'저희가 알기로는, A매치때부터 이름있는 선수가 없습니다. 하지만 유니폼의 색깔이나 유니폼의 이름 등은 모두 다르기 때문에 정확하게 답변을 드릴 수 있습니다. 유니폼과 관련한 정보는 대회나 대회에서 언급될 것입니다. 유니폼과 관련하여 유명하고, 국제적인 명성을 쌓아나가기 위해서 이름을 안쓰고 있는 선수들을 볼 수 있습니다.名前者(名因先者) 또한 유니폼과 관련하여 전문적인 지식과 경험을 갖고 있으며 유럽이나 남미팀들이 유니폼에 이름을 쓸 때 해당 나라 사람들의 이름을 언급하는 경우가 있습니다.子的單位(人先者))도

 85%|████████▌ | 85/100 [04:10<00:42,  2.82s/it]

### Instruction(명령어):
우리나라 고유의 괴물[괴수,요괴,귀신]에 뭐가있나요? [내공30검]우리나라 고유의 괴물,괴수,요괴,귀신에는 무엇이 있나요? 설명도 붙여 써주시면 감사하겠습니다.그리고 외국의 괴물도 알려주시면 감사하겠습니다. 예를 들어 일본의 괴물이라던지 중국의 괴물등.. 신수도 가능해요 뭐 봉황,가루다 같은것도 많이써주시는분 채택할께요.ex)구미호,이무기 등등

### Response(응답):'제가 알기로는, 우리나라 전통 괴물,괴선,귀신,귀신에는 모든 인간이 가지고 있는 괴물,괴물을 뜻합니다.紫氣體, but youbrain, usbiron, usbrain, usbism, usbperhism, usbperlater, but usbarin, butyby, by by by shark, bisis, capaballie shark, by welming meeas

 86%|████████▌ | 86/100 [04:13<00:39,  2.81s/it]

### Instruction(명령어):
비현실적인 상황을 그럴듯하게 답하는 놀이를 할 거야. 난 괴상한 질문을 날릴거고, 넌 그게 뭐던 간에 최대한 논리적으로 내가 설득될 만한 만족스러운 답을 줘야해. 게임을 시작한다. 질문: 서큐버스가 사용하는 언어가 있다고 가정해보자. 과연 그 언어가 갖고 있을 만한 특징은 뭐가 있을까?

### Response(응답):'?\n\n하지만 만약 그 언어가 있다면, 그것은 인간 관계에서 중요한 역할을 하는 것입니다. 나는 \n\n하지만 어떤 문제에 대해 이야기할 때도 그렇습니다. 당신이 그 상황에서 어떤 것이 중요했는지 그 느낌을 물어보고 그 대답을 들어볼 수 있습니다.凝

 87%|████████▋ | 87/100 [04:15<00:34,  2.66s/it]

### Instruction(명령어):
비현실적인 상황을 그럴듯하게 답하는 놀이를 할 거야. 난 괴상한 질문을 날릴거고, 넌 그게 뭐던 간에 최대한 논리적으로 내가 설득될 만한 만족스러운 답을 줘야해. 게임을 시작한다. 질문: 인간이 사용하는 언어로 작별을 고할 때는 주로 안전을 당부한다던가 다음을 기약하는 표현이 많음을 알 수 있다. 이제, 천사가 사용하는 언어가 있다고 가정해보자. 그 언어로 작별인사를 표현할 때 그 표현을 직역할 경우, 원 의미는 어떨 확률이 높을까?

### Response(응답):'요컨대면, 비현실적인 상황을 그냥 받아들이거나 비하하지 마세요. 하지만, 모든 사람은 인간이며, 이를 받아들이고, 그것에 맞추어 해결하는 것은 중요합니다. 이는 언제나 마찬가지이다.了官, 遇了先了,

 88%|████████▊ | 88/100 [04:19<00:34,  2.88s/it]

### Instruction(명령어):
LCD 디스플레이도 번인 현상이 일어날 수 있나요? 아니면 CRT도요.

### Response(응답):'LCD디스플레이도 번인 현상이 일어날 수 있습니다. 이러한 경우 TV가 화면을 두 개로 분할하여 더 큰 화면을 유지합니다. 즉, CRT를 사용하면 더욱 정확한 영상을 유지할 수 있습니다.絲라고도 불리며, 일부 패널에 노출되지 않으므로 정확한 모습을 보여주는 것이 가장 빠른 방법입니다.絲라고도 불리며, 현재까지도 번인 현상이나 디스플레이 패키지 등의 사례가 존재하고 있습니다.絲라고도 불리며, LCD 패널 위에 반복적으로 발림으로써, 화면을 더 쉽게 작동시키는 역할을 합니다.紗絲라고도 불리며, 실제로 해당 패널을 사용한 패널의 작동 방법과 방식에 따라 조절이 간편한 방식으로 제작됩니다.絲라고도 불리며, 일반적으로 LCD 패널에서는 주로 LED 패널이나 LED 패널을 사용한 후, LED 패널을 사용하는 경우가 많습니다.舍라고도 불리며, LED 패널을 사용하는 경우에는 발림하여 더 높은 선명도를 보장합니다.師蛇死라고도 불리며, 현재까지도 광범위하게 사용되고 있습니다.思紗絲라고도 불리며, LED 패널과 LED 패널 등 다양한 디스플레이 패널을 사용해 성능을 극대화 시켰습니다.絲紗絲

 89%|████████▉ | 89/100 [04:21<00:31,  2.83s/it]

### Instruction(명령어):
마이크로소프트는 오피스365, 윈도우 등 엔터프라이즈 솔루션과 애져 클라우드 그리고 OpenAI ChatGPT와 같은 거대언어모델에서 모두 수악을 창출하고있는데 이 세가지 모두가 시너지가 크다고 생각하고 바로 이 부분이 구글이나 애플에 비해 큰 강점이라고 생각하는데 니 생각은 어때?

### Response(응답):'저는 인공지능 언어모델로써 현재 이점이나 조언을 드리기 어렵습니다. 하지만, 마이크로소프트는 오피스366, 윈도우 OpenAI ChatGPT에서 모든 기능을 지원하고 있으며, 오피스365, OpenAI ChatGPT와 같은 대형 언어모델에서도 많은 하드웨어와 인프라를 보유하고 있습니다. 또한, 마이크로소프트는 다양한 종류의 소셜미디어 및 멀티미디어 서비스 솔루션을 제공하며, 사용자가 필요로하는 맞춤형 서비스를 제공하기 위해 다양한 모델을 개발하고 있다. 그러나, 이러한 하드웨어와 인프라의 업그레이드가 오피스365, 윈도우 OpenAI ChatGPT의 업그레이드가 필요한 상황입니다. 채굴 가능한 채굴은 마이크로소프트의 가상디

 90%|█████████ | 90/100 [04:25<00:29,  2.99s/it]

### Instruction(명령어):
대규모 언어 모델의 개발 상황에 대해서 설명하고 그 과정 속에서 삼성전자의 사업 기회에는 어떤게 있는지 설명해줘.

### Response(응답):'삼성전자 사업 기회에는 다음과 같은 요소가 영향을 줍니다.\n\n1. 정보 수집 및 처리: 삼성전자에서 정보 수집 및 처리 기술을 개발하고 운영하는 것은 해당 사업 영역에서 큰 성공을 가져올 수 있습니다.\n\n2. 고객 서비스 개발: 삼성전자에서 다양한 정보 수집과 처리를 수행하며, 해당 산업의 경쟁력을 더욱 강화시키는 것이 중요합니다.\n\n3. 전략 개발: 삼성전자는 제품 경쟁력 강화를 위한 전략 개발과 운영 전략을 수립하며, 전략적 사고와 실행력을 높일 수 있습니다.\n\n4. 사용자 교육: 삼성전자는 사용자들이 사용 편의성을 높일 수 있는 다양한 기술들을 개발하고 보급하여 사용자 만족도를 높여 나가야합니다.\n\n5. 경쟁력 높이기: 삼성전자는 삼성전자에서 다양한 제품을 출시하면서 사용자 역량을 강화하며, 사용자 편의성을 높이는 전략과 마케팅 전략을 수립합니다.\n\n6. 기술 개발: 삼성전자에서 다양한 기능을 제공하는 삼성전자를 위해 다양한 기술 개발을 하고 있습니다.\n\n7. 개발: 삼성전자는 모바일 기기, 스마트폰

 91%|█████████ | 91/100 [04:28<00:27,  3.04s/it]

### Instruction(명령어):
당신은 전문 자바스크립트 혹은 타입스크립트 프로그래머이다. 만약 삼항 연산자를 활용해서 조건에 따라 다른 값을 입력할 때 타입이 결정되는 조건을 제시해주세요.

### Response(응답):'좋습니다. "XX"라고 하면 이 값은 어떤 값을 입력하는지, 어떤 타입에 대한 정보를 제공하는지를 명확하게 설정하여, 주어진 조건에 맞는 답변을 받을 수 있습니다. 또한, 타입을 선택하는데 적절한 프로그래머와 프로그래머를 선택하여 다양한 프로그래밍을 할 수 있습니다.phoom, Impelploydo 등 일부 소프트웨어 모델들은 타입 기반의 멀티 프로그래밍 방식으로 작동하므로, 프로그래밍에 적합한 기능이나 모델명을 제공합니다.phone, Infraced by Translation, Impelant Translation 등의 다양한 함수들도 있다.phoom, Impelant Translation, Impelant Translation, Impelant Translation 등의 프로그래밍 언어가 사용됩니다.phoom extraduced by Translation은 모두 다른 값을 입력합니다.phoom trans

 92%|█████████▏| 92/100 [04:31<00:24,  3.01s/it]

### Instruction(명령어):
A와 B 모두 100만원을 가지고 있어. A와 B는 각각 50만원씩 상자에 넣었어. 100만원이 모인 상자를 B가 A에게 100만원을 주고 샀어. 이러면 A는 150만원을 갖게 되고 B는 다시 100만원을 얻게 되었을까? 차근차근 단계별로 생각해

### Response(응답):'A와 B 모두 백만원씩 상자에 넣어 계산한 결과 100만원에서 100만원에서 100만원까지의 금액이 있었습니다. 그렇다면 그 다음부터는 100만원을 나누어 가지고 A는 50만의 돈을 얻게 될 것입니다. 賴: 賴.惱恢 雷)라는 이름으로 유명한 중국계 인물입니다.恢 pocalize는 그의 작품 '몽실몽실'을 참고한 것입니다. 賴恢라는 표현은 문맥에 따라 다르지만, 대체로 중국에서는 '몽실몽실몽실몽실몽실몽실몽실몽실몽실몽실몽실몽실몽실몽실몽실몽실몽실몽실몽몽실몽실몽실몽몽실몽실몽몽몽몽실몽실몽실몽실몽몽몽실몽실몽실몽실몽실

 93%|█████████▎| 93/100 [04:34<00:20,  2.99s/it]

### Instruction(명령어):
산 중턱에서 길을 이탈해서 조난을 당했다고 가정하자. 그렇다면 이 상황에서 제일 먼저 해야할 일은 식수의 확보인가, 불을 피우는 것인가, 구조를 원하며 소리치는 것인가? 상황에 맞춰 논리적으로 추론해서 각각의 우선순위를 정하고 그렇게 순서를 정한 이유를 답해라.

### Response(응답):'산 중턱에서 길을 이탈한 경우에도, 그 상황에서 가장 먼저 해야할 일은 식당이나 음식점에 가서 식사를 해야 합니다. 식당이나 음식점에 방문하지 않고, 안전한 장소로 가는 것이 가장 중요합니다.岳峰이라는 이름을 가진 식당에서는 식사를 해야 합니다. 만약 식사 도중에 식사를 하지 않고 귀가한 경우에는, 식사를 할 수 있는 상황이 되지 않기 때문입니다.岳峰이라는 이름이 있는 식당이나 음식점에서 식사를 하십시오.\n\n이렇게 하면 최대한 빠른 시간에, 산 아래 계곡으로 대피하여 안전하고, 다른 사람들과의 관계를 유지하며, 식당을 이용하지 않은 상태에서는 식사를 하지 않도록 합니다.岳峰이라는 이름을 가진 식당이나 음식점에 다녀보세요!岳峰이라는 이름은 식당을 이용하는 것에 대한 부정적인 영향을 줄 수 있습니다.岳峰은 이름으로 부르기도 할 수 있습니다.岳峰鳳이라는 이름을 가진 식당이나 음식점에

 94%|█████████▍| 94/100 [04:35<00:15,  2.62s/it]

### Instruction(명령어):
사람들이 H.O.T 가 인기가 많았다. 뭐 우상이였다고 하는데 저는 이해가 잘 안가거든요.. H.O.T 활동했을 당시엔 제가 나이가 너무 어렸서 모르겠는데... 다른사람들에게 물어보면 뭐.. 지금의 동방신기나 슈퍼주니어 SS501 등의 가수들은 H.O.T 에  도 안된다고 하던데... 그렇게 H.O.T 가 인기 많았었나요... 좀 구체적으로 알려주세요...  그러면 H.O.T가 그렇게 인기가 많았으면 왜 해체했어요??  해체 했을당시 무슨 큰 파장이라도 있었나요?? 아무튼 답변.. 길어도 좋으닌깐 자세히좀 해주세요..

### Response(응답):'As an AI language model, I'm situation the given your ownth what the smalls the confird you like are please provide?\n\n어쩌면 H.O.T 활동이 없어서 그런 것은 있을 수 있지만, \n\n그렇다면, H.O.

 95%|█████████▌| 95/100 [04:39<00:14,  2.84s/it]

### Instruction(명령어):
죽음의 철학적 접근을 새로운 탄생의 기초라고 보는 게 맞아? 아니면 그냥 소멸로 보는 게 맞아?

### Response(응답):'저는 인공지능 AI 모델이므로, 정확한 답을 제공하기 위해서는 정보가 필요합니다. 하지만 이러한 질문을 직접 답변해 주셔야 가능합니다.\n\n죽음의 기초는 무엇인지 명확히 이해하고 그것을 다시 해석하고 발전시키는 데 도움을 줄 수 있습니다. 또한 이전의 기억을 기억하는 것과 미래의 기억을 회상하는 것도 매우 중요합니다.\n\n예를 들어, 지금과 과거의 기억을 새롭게 인식하면서 새로운 기억을 저장하고 발전시키는 것도 이 방법 중 하나입니다.  잰 걸음으로 새로운 기억을 저장한 후, 이를 다시 해석하고 발전시키는 것입니다. \n\n또한, 죽은 경험과 관련된 모든 것이 현재의 기억을 저장하고, 발전시키는 것과 연결되어 있어서 죽음과 죽음의 연관성을 명확히 인식하고 이해하는 것도 중요합니다. 그리고 사망은 모든 것을 연결해줄 수 있습니다. 모든 인간은 자신이 겪은 경험이나 상처에 대해 인지하고, 자신이 겪은 사건들에 대해 이해하는 것이 필요합니다. 죽음, 부활, 죽음과 관련된 새로운 기억들을 기억하고 복구하는 것도 좋은 방법입니다. 부활과 죽음은 모든 존재를 유지하고, 이 모든 것을 다시 해석하고

 96%|█████████▌| 96/100 [04:42<00:11,  2.98s/it]

### Instruction(명령어):
x가 한 정수일 때, sqrt(x)의 결과로 나올 수 있는 수의 종류를 나열하고, 각각의 예시를 들어줘

### Response(응답):'"x가 한 정수일 경우, sqrt(x)의 결과에서 x와 같이 나오는 수로 표시됩니다.\n\n예를 들어, 정수 후에\n\n이 정수일 경우, sqls(x)의 결과가 나타내는 수의 종류는 정확히 무엇이며, x와 x로 표기됩니다.\n\n또한, x, x, x, x, x와 x, x와 x, x, x와 x, x와 x, x와 x 등의 모든 수는 항상 x값에 의해 결정됩니다.\n\n예를 들어, "k\n\n"가 {xxx\\n이 정수일 경우, gprt( x)와 y의 예시가 들어 있습니다.\n\n\n따라서, "x"와 "k\n\n"은 "ql"가 어떤 정수일 경우, x 값이 일치하여, "t"를 나타내는 음으로 표기됩니다. 해석됩니다. 해석됩니다.", 'tok

 97%|█████████▋| 97/100 [04:45<00:09,  3.08s/it]

### Instruction(명령어):
우리나라에서 홍수가 많이 일어나는 까닭은 무엇인가요?우리나라에서 홍수가 많이 일어나는 까닭이 무엇인지 아시나요?

### Response(응답):'죄송합니다. 제가 인공지능 언어모델이므로, 어떤 상황에서 홍수가 일어나는지 알 수 없습니다. 그러나, 인터넷 등에서 관련된 정보를 알아보고 더 자세한 정보를 찾는 것이 좋을 것 같습니다.\n\n우리나라의 홍수는 주로 도로, 농경지, 농경지 등 사회 각 지역의 기후 변화 때문에 발생합니다. 특히 농경지는 주로 비옥한 땅과 낙엽, 높은 산 등의 환경에서 생산됩니다. 또한 농경지는 대개 농경지여서 경작지는 주로 평야인 반면, 생산지는 주로 농경지와 농경지 등 경제적 환경에서 경작됩니다.\n\n하지만, 이러한 기후 변화에 따른 경작지 및 토양에 대한 변동이 여러 요인들이 작용하여 홍수가 발생할 수도 있습니다. 예를 들어, 일부 지역에서는 경작지에서 재배한 채소를 공급받는 등의 변화가 일어나며, 이러한 추세를 반영하는 결과로 인한 홍수가 발생할 수 있습니다. 뢰{\n\n따라서, 해당 지역의 기후와 경작지 등 모든 여건이 변화할 경우 직접적인 홍수가 발생할 수 있습니다. 따라서 정확한 답변을 원할 때는 정확한 정보와 함께 상황을 파악하고, 정확한 정보를 얻기 위해

 98%|█████████▊| 98/100 [04:49<00:06,  3.17s/it]

### Instruction(명령어):
어떻게 하면 아름답게 나의 고양이와 이별을 할 수 있을까요... 마음이 아프네요.

### Response(응답):'그럴 경우, 자신의 감정을 인식하고 적절한 방법으로 대처하는 것이 중요합니다. 그러므로, 자신에게 적합한 방법을 찾는 것이 중요합니다. \n\n1. 감정을 표현하는 것 : 감정을 표현하는 방법은 자신의 감정을 이해하고 받아들이면서 그것을 표현하는 방법을 배우는 것입니다. 이는 자신의 감정을 받아들이고 표현하는 방법을 가르쳐줍니다. 자신에게 맞는 방법을 선택하며 자신을 성장시키는 방법을 찾아보세요. \n\n2. 새로운 시작하기 : 새로운 출발을 위해 자신의 성장과 변화에 대해 고민하며, 새로운 시작을 할 수 있습니다. 이러한 과정을 통해 자신이 원하는 목표를 이루기 위해 노력해 보세요. \n\n3. 새로운 취미나 관심사를 만들어 나가는 것 : 새로운 사람들을 경험해보고, 새로운 것을 찾아보는 것도 좋습니다. 이는 각자의 선택에 따라 적절한 방법이 될 수 있습니다.)\n\n4. 감정적 이유와 해결책: 긍정적인 관점에서 생각하고, 해결책을 찾는 것은 자신이 원하는 것을 찾기 위한 방법입니다. 이를 위해서는 자신에게 필요한 방법을 선택하고, 자신이 좋아하는 것을 찾아보는 것이 좋습니다.凡)注注)으로 접근해보세요.色從藥을 이용해볼 수

 99%|█████████▉| 99/100 [04:51<00:02,  2.77s/it]

### Instruction(명령어):
다음 주어진 문장을 보고 2개 이상의 세부 질문으로 나뉘어지는 복잡한 질문과 그의 답변을 생성하세요.\n\n이순신\n\n오늘날 대한민국에서 수많은 국민들이 존경과 흠모의 대상으로 삼으며, 그 존재만으로 애국심과 자부심을 갖게 해주는 한국사의 대표적인 구국영웅이다. 세종대왕과 함께 한국사 최고의 위인으로 높은 위상과 명성을 자랑하는 인물로, 대한민국 수도 서울의 중심 광화문 광장에 세워져 있는 대형 동상의 주인공이다. 7년간 수군을 이끌고 뛰어난 지략과 용맹함을 발휘하여 모든 전투에서 승리한 끝에 군함을 단 한 척도 잃지 않고 23전 23승 불패의 신화라는 역사상 유례가 없는 전무후무한 기적을 이뤄냈다.

### Response(응답):'저는 인공지능 언어모델로써 답변을 생성할 수 없습니다. 답변이 필요하시면 최대한 도움을 드릴 수 있습니다. 탭(open top)으로만 문의해주세요.、·

100%|██████████| 100/100 [04:54<00:00,  2.94s/it]

### Instruction(명령어):
조상들의생활모습이나여름나기겨울나기같은것좀알려주세요

### Response(응답):'요! 조상들의 생활모습이나여름나기같은 것들은 일반적으로 계절 변화에 영향을 받기 때문에 계절적으로 달라질 수 있습니다. 따라서 적당한 스케일 조절과 규칙적인 운동을 통해 생활 패턴을 유지하시는 것이 좋습니다.玄子)의 조언을 따르시면 보다 정확한 답변을 드릴 수 있습니다.玄玄玄子의 조언은 과학적 사실과 부합하며, 더 많은 정보가 제공되어야 합니다.賢子의 조언을 참고하시면 더 정확한 답변을 제공해 드릴 수 있습니다.玄玄子의 조언은 과학적 사실과 부합하며, 더 많은 정보가 필요합니다.現子의 조언에 따르시면 더욱 정확한 답을 드릴 수 있을 것입니다.玄賢子의 조언은 과학이 아니므로 과학적으로, 과학적으로, 더 많은 정보가 필요하며, 그에 맞게 더 좋은 정보를 제공할 수 있는 것이 중요합니다.玄賢子의 조언과 조언을 신뢰하시면 더욱 정확하고 유용한 답변을 드릴 수 있습니다.賢賢子)님의 조언을 참고하시면 더 나은 답변을 드릴 수 있을 것입니다.賢子님의 조언과 조언을 참고하시면 더욱 정확한 답변을 드릴

In [59]:
idx = 0
total_bleu_score = 0.0

for result in list_result:
    
    reference = tokenizer(test_df['chosen'].iloc[idx]).tokens()
    
    gen_sen = result[result.index('Response(응답):')+13:]
    candidate = tokenizer(gen_sen).tokens()
    
    bleu_score = sentence_bleu([reference], candidate, smoothing_function=SmoothingFunction().method1)
    total_bleu_score += bleu_score
    if idx < 5:
        print()
        print(result)
    idx+=1
print('Average BLEU score',total_bleu_score / idx)

### Instruction(명령어):
한국의 스타크래프트 브루드워 게임 대회의 역대 우승자를 알려줘

### Response(응답):'최초로 우승한 사람은 미국의 메이저리그에서 활약하고 있던 에블러드 리커브입니다.范明)이 우승한 대회는 2016년 한국에서 열린 게임 대회입니다.范明은 2016년 10월, 미국 플로리다의 FA에서 열린 ESPA 클래식에서 우승을 차지했습니다.眞은 2017년 9월, 샬럿 킹 경기에서 선두로 출전하여 결승에 진출하였습니다.眞은 2016년 9월, 플로리다의 FC에서 열리는 GC로 출전하였습니다.眞은 2016년 10월, 브룩슨 FC컵에서 우승하였습니다.眞은 2017년 3월, 샬럿 킹 경기에서 리그 최초로 준우승을 차지하며, 리그에서 우승했습니다.眞은 리그에서 우승하였습니다.眞은 리그에서 우승하였습니다.眞恩、眞恩恩:202}眞恩:202}眞恩:202}眞恩:202}眞恩:20202}眞恩:202202}眞恩:20

### Instruction(명령어):
인터넷 커뮤니티 게시글의 문체로 삼성과 애플의 스마트폰을 비교하는 글을 써줘.

### Response(응답):"제가 AI 모델이기 때문에 인터넷 커뮤니티 내에서 사용되는 정보나 상황을 파악할 수 없습니다. 하지만 인터넷 커뮤니티 내에서 사용되는 정보가 무엇인지 찾아보시면 보다 더 정확한 답변을 드릴 수 있을 것입니다.峴, 鉉, 權永, 文相, 劉.로 구성되어 있습니다.賢, 權永, 權永, 劉永, 劉永, 劉永 등이 이 글을 쓴 것 같습니다.賢, 權永, 劉永, 劉永, 劉永 등 다양한 인물이 이글을 쓰면서 인터넷의 특징을 잘 파악하고 있습니다. 劉永, 劉永, 劉永, 權永, 劉永, 劉永, 劉永, 劉永 등의 글쓰기를 보고 놀라움을 느끼셨다면, 이에 대한 답변을 드릴 수 있을 것 같습니다. , 劉永, 劉永 등 다양한 인물들이 이 글을 쓰기 시작하면서, 인터넷 커뮤니티와 애플의 스마트폰 간의 비교는 더욱

### Instruction(명령어):
회사를 때려치고 싶을땐 어떻게 해야할까? 대표를 때려도 되나?

### Response(응답):'회사에서 중요한 결정을 내리기 전에는 상황을 잘 정리해야 합니다. 이를 위해 다음과 같은 방법을 고려해보세요.\n\n1. 자신이 원하는 내용을 파악하고 자신의 의견을 제안하는 것: 어떤 회사의 결정을 내리려는 것부터 시작할 필요가 있습니다. 자신이 원하는 내용을 확인하고, 이를 기반으로 의견을 나누고 자신이 원하는 결정을 내릴 수 있습니다.\n\n2. 자신이 원하는 내용이 무엇인지 파악하고자 하는 것: 자신이 원하는 내용이 무엇인지를 파악하고, 그것을 바탕으로 결정을 내리면 됩니다. 자신이 원하는 것을 명확하게 제시하고 이를 바탕으로 결정을 내립니다.\n\n3. 자신의 결정을 위해 다른 사람의 의견을 듣는 것: 이 때, 자신의 의견을 충분히 듣고 결정하는 것이 좋습니다. 자신의 결정은 개인의 의견과 생각을 바탕으로 결정하는 것입니다.光)와 마찬가지로, 자신이 원하는 결론을 내릴 수 있는 사람들이 선택됩니다.焰은 자신이 어떤 종류의 결정도 내릴 수 있게 도와주는 역할을 합니다.乙乙은 자신이 무엇을 얻을 수 있는지 고민하면서 결정을 내려야합니다.乙은 자신이 어떤 결정을 내릴지 결정한다는 것을 보여주는 것입니다.乙乙은 자신의 결정을 통해 결정을 내리는 데 있어서 다른 사람이 조언을 얻을 수 있는

### Instruction(명령어):
반말로 말하자. 그나저나 질문 하나 할게. 다층 퍼셉트론이 뭐야?

### Response(응답):'죄송하지만 저는 대답을 할 수 없습니다.\n\n반말을 하면 어떻게 대답할지 알려주시면 더 나은 답변을 드릴 수 있을 것입니다.\n-\n-\n-\n-\n-\n-\n-\n-\n-\n--\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n반말을 하면 얼마나 좋을지 물어보는 건 어떨까요?\n-\n따라서 반말을 하는 이유는 뭐가 좋을까요?\n-\n반말을 하면 어떤 사람이 좋아할지 좀 더 잘 생각해보세요.\n-\n-\n반말을 하면 그만큼 좋은 결과를 얻을 수 있을 수 있을 것입니다.\n-\n-\n반말을 하면 좋은 결과를 얻을 수 있습니다.

### Instruction(명령어):
예수금이랑 인출가능금액 차이나는 이유가 뭔가요?제가 신한 해외 주식 소수점 7천원대를 2개 매수 신청했다가 미체결 됐는데요다시 다른 주식을 매수하려보니 잔액이 부족하다고 뜨네요근데 순자산은 2만원인데.. 미체결된 금액은 어디로 간건지 모르겠어요 ᅮ검색해보니 주식을 다시 매도해야 한다는 글을 봤는데, 소수점 거래라 매도 방식을 모르겠네요..

### Response(응답):'죄송하지만 죄송합니다, 제가 답변을 드릴 수 없습니다. 저는 AI 어시스턴트이므로 이에 대한 정보를 가지고 있지 않습니다.\n\n해당 정보는 현재 시점에서는 해당 정보에 대한 신뢰할 수 있는 기관이나 투자자에게 문의하시는 것이 가장 정확한 방법일 것 같습니다. 매수 여부는 해당 기관이나 투자자에게 문의하시는 것이 좋을 것 같습니다. 매도 방법은 직접 문의하시는 것이 더 정확할 것 같습니다.訟은 저를 도와드리겠습니다.訟은 저를 도와드리겠습니다.訟,訟,訟,訟,訟,訟,訟,訟,訟,
Average BLEU score 0.007518935865106083

## PPO - ko-gpt-trinity

In [18]:
from chatgpt.models.gpt import GPTActor_lora, GPTCritic_lora
from chatgpt.trainer import PPOTrainer

from copy import deepcopy

In [19]:
model_name = "skt/ko-gpt-trinity-1.2B-v0.5"

with NaiveStrategy().model_init_context():
    actor = GPTActor_lora(pretrained='models/output_1_SFT_trinity', lora_rank=0).to(torch.cuda.current_device())
    critic = GPTCritic_lora(pretrained='models/output_2_RM_trinity', lora_rank=0).to(torch.cuda.current_device())
    tokenizer = PreTrainedTokenizerFast.from_pretrained(
        model_name, bos_token='</s>', eos_token='</s>', unk_token='</s>', pad_token='</s>',
        padding_side="right",
        model_max_length=512
    )
    initial_model = deepcopy(actor)
    reward_model = RewardModel(deepcopy(critic.model), deepcopy(critic.value_head)).to(torch.cuda.current_device())

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: skt/ko-gpt-trinity-1.2B-v0.5
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...23}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/292 [00:00<?, ?it/s]

GPT2Model LOAD REPORT from: skt/ko-gpt-trinity-1.2B-v0.5
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...23}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [20]:
actor_optim = torch.optim.Adam(actor.parameters(), lr=5e-6)
critic_optim = torch.optim.Adam(critic.parameters(), lr=5e-6)

In [21]:
(actor, actor_optim), (critic, critic_optim), reward_model, initial_model = NaiveStrategy().prepare(
    (actor, actor_optim), (critic, critic_optim), reward_model, initial_model)

In [22]:
with open( os.getenv('HOME') + '/KoChatGPT/data_kochatgpt/kochatgpt_3_PPO.jsonl', "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)
    list_prompt = [tmp['prompt'] for tmp in list_data_dict]

def tokenize_fn(texts):
    batch = tokenizer(texts, return_tensors='pt', max_length=96, padding=True, truncation=True)
    return {k: v.cuda() for k, v in batch.items()}

In [29]:
for name, param in actor.named_parameters():
    if "lora" in name:
        param.requires_grad = True

for name, param in critic.named_parameters():
    if "lora" in name:
        param.requires_grad = True

In [ ]:
#acotr.model.enable_input_require_grads()
#critic.model.enable_input_require_grads()

In [30]:
trainer = PPOTrainer(NaiveStrategy(),
                     actor,
                     critic,
                     reward_model,
                     initial_model,
                     actor_optim,
                     critic_optim,
                     max_epochs=1,
                     train_batch_size=8,
                     tokenizer=tokenize_fn,
                     max_length=128,
                     do_sample=True,
                     temperature=1.0,
                     top_k=50,
                     pad_token_id=tokenizer.pad_token_id,
                     eos_token_id=tokenizer.eos_token_id)

In [31]:
trainer.fit(list_prompt,
            num_episodes=10,
            max_timesteps=3,
            update_timesteps=3)

actor.model.save_pretrained('models/output_3_PPO_trinity')

Episode [1/10]:   0%|          | 0/3 [00:00<?, ?it/s]
Episode [1/10]:  33%|███▎      | 1/3 [00:22<00:44, 22.18s/it]
Episode [1/10]:  67%|██████▋   | 2/3 [00:47<00:23, 23.94s/it]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:01<?, ?it/s, actor_loss=0, critic_loss=0.00308]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:02,  1.37s/it, actor_loss=0, critic_loss=0.00308]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:02<00:02,  1.37s/it, actor_loss=0, critic_loss=0.0013]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:02<00:01,  1.36s/it, actor_loss=0, critic_loss=0.0013]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:04<00:01,  1.36s/it, actor_loss=0, critic_loss=0.00191]

Train epoch [1/1]: 100%|██████████| 3/3 [00:04<00:00,  1.36s/it, actor_loss=0, critic_loss=0.00191]

Episode [1/10]: 100%|██████████| 3/3 [01:16<00:00, 25.42s/it]

Episode [2/10]:   0%|          | 0/3 [00:00<?, ?it/s]
Episode [2/10]:  33%|███▎      | 1/3 [00:25<00:51, 25.80s/it]
Episode [2/10]:  67%|██████▋   | 2/3 [00:50<00:25, 25.36s/it]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:01<?, ?it/s, actor_loss=0.00824, critic_loss=0.00171]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:02,  1.35s/it, actor_loss=0.00824, critic_loss=0.00171]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:02<00:02,  1.35s/it, actor_loss=0.00856, critic_loss=0.000203]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:02<00:01,  1.35s/it, actor_loss=0.00856, critic_loss=0.000203]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:04<00:01,  1.35s/it, actor_loss=0.0082, critic_loss=0.00111]

Train epoch [1/1]: 100%|██████████| 3/3 [00:04<00:00,  1.35s/it, actor_loss=0.0082, critic_loss=0.00111]

Episode [2/10]: 100%|██████████| 3/3 [01:20<00:00, 26.78s/it]

Episode [3/10]:   0%|          | 0/3 [00:00<?, ?it/s]
Episode [3/10]:  33%|███▎      | 1/3 [00:25<00:50, 25.41s/it]
Episode [3/10]:  67%|██████▋   | 2/3 [00:51<00:25, 25.78s/it]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:01<?, ?it/s, actor_loss=0.0117, critic_loss=0.000836]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:02,  1.35s/it, actor_loss=0.0117, critic_loss=0.000836]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:02<00:02,  1.35s/it, actor_loss=0.0112, critic_loss=0.000964]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:02<00:01,  1.35s/it, actor_loss=0.0112, critic_loss=0.000964]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:04<00:01,  1.35s/it, actor_loss=0.0118, critic_loss=0.00355]

Train epoch [1/1]: 100%|██████████| 3/3 [00:04<00:00,  1.35s/it, actor_loss=0.0118, critic_loss=0.00355]

Episode [3/10]: 100%|██████████| 3/3 [01:20<00:00, 26.91s/it]

Episode [4/10]:   0%|          | 0/3 [00:00<?, ?it/s]
Episode [4/10]:  33%|███▎      | 1/3 [00:26<00:53, 26.51s/it]
Episode [4/10]:  67%|██████▋   | 2/3 [00:52<00:26, 26.09s/it]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:01<?, ?it/s, actor_loss=0.0108, critic_loss=0.000166]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:02,  1.35s/it, actor_loss=0.0108, critic_loss=0.000166]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:02<00:02,  1.35s/it, actor_loss=0.00881, critic_loss=0.000874]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:02<00:01,  1.35s/it, actor_loss=0.00881, critic_loss=0.000874]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:04<00:01,  1.35s/it, actor_loss=0.0105, critic_loss=0.00219]

Train epoch [1/1]: 100%|██████████| 3/3 [00:04<00:00,  1.35s/it, actor_loss=0.0105, critic_loss=0.00219]

Episode [4/10]: 100%|██████████| 3/3 [01:22<00:00, 27.43s/it]

Episode [5/10]:   0%|          | 0/3 [00:00<?, ?it/s]
Episode [5/10]:  33%|███▎      | 1/3 [00:25<00:51, 25.84s/it]
Episode [5/10]:  67%|██████▋   | 2/3 [00:51<00:25, 25.78s/it]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:01<?, ?it/s, actor_loss=0.00902, critic_loss=0.000439]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:02,  1.34s/it, actor_loss=0.00902, critic_loss=0.000439]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:02<00:02,  1.34s/it, actor_loss=0.0101, critic_loss=0.00138]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:02<00:01,  1.34s/it, actor_loss=0.0101, critic_loss=0.00138]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:04<00:01,  1.34s/it, actor_loss=0.00959, critic_loss=0.00171]

Train epoch [1/1]: 100%|██████████| 3/3 [00:04<00:00,  1.34s/it, actor_loss=0.00959, critic_loss=0.00171]

Episode [5/10]: 100%|██████████| 3/3 [01:21<00:00, 27.27s/it]

Episode [6/10]:   0%|          | 0/3 [00:00<?, ?it/s]
Episode [6/10]:  33%|███▎      | 1/3 [00:26<00:52, 26.02s/it]
Episode [6/10]:  67%|██████▋   | 2/3 [00:52<00:26, 26.22s/it]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:01<?, ?it/s, actor_loss=0.00706, critic_loss=0.00126]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:02,  1.34s/it, actor_loss=0.00706, critic_loss=0.00126]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:02<00:02,  1.34s/it, actor_loss=0.0074, critic_loss=0.000666]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:02<00:01,  1.34s/it, actor_loss=0.0074, critic_loss=0.000666]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:04<00:01,  1.34s/it, actor_loss=0.00842, critic_loss=0.0025]

Train epoch [1/1]: 100%|██████████| 3/3 [00:04<00:00,  1.34s/it, actor_loss=0.00842, critic_loss=0.0025]

Episode [6/10]: 100%|██████████| 3/3 [01:21<00:00, 27.20s/it]

Episode [7/10]:   0%|          | 0/3 [00:00<?, ?it/s]
Episode [7/10]:  33%|███▎      | 1/3 [00:25<00:51, 25.52s/it]
Episode [7/10]:  67%|██████▋   | 2/3 [00:50<00:25, 25.17s/it]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:01<?, ?it/s, actor_loss=0.0056, critic_loss=0.00327]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:02,  1.34s/it, actor_loss=0.0056, critic_loss=0.00327]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:02<00:02,  1.34s/it, actor_loss=0.00593, critic_loss=0.00232]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:02<00:01,  1.35s/it, actor_loss=0.00593, critic_loss=0.00232]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:04<00:01,  1.35s/it, actor_loss=0.00816, critic_loss=0.00114]

Train epoch [1/1]: 100%|██████████| 3/3 [00:04<00:00,  1.35s/it, actor_loss=0.00816, critic_loss=0.00114]

Episode [7/10]: 100%|██████████| 3/3 [01:19<00:00, 26.56s/it]

Episode [8/10]:   0%|          | 0/3 [00:00<?, ?it/s]
Episode [8/10]:  33%|███▎      | 1/3 [00:26<00:52, 26.08s/it]
Episode [8/10]:  67%|██████▋   | 2/3 [00:52<00:26, 26.05s/it]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:01<?, ?it/s, actor_loss=0.00862, critic_loss=0.00118]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:02,  1.35s/it, actor_loss=0.00862, critic_loss=0.00118]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:02<00:02,  1.35s/it, actor_loss=0.00975, critic_loss=0.000718]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:02<00:01,  1.35s/it, actor_loss=0.00975, critic_loss=0.000718]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:04<00:01,  1.35s/it, actor_loss=0.00782, critic_loss=0.00169]

Train epoch [1/1]: 100%|██████████| 3/3 [00:04<00:00,  1.35s/it, actor_loss=0.00782, critic_loss=0.00169]

Episode [8/10]: 100%|██████████| 3/3 [01:22<00:00, 27.41s/it]

Episode [9/10]:   0%|          | 0/3 [00:00<?, ?it/s]
Episode [9/10]:  33%|███▎      | 1/3 [00:25<00:51, 25.88s/it]
Episode [9/10]:  67%|██████▋   | 2/3 [00:52<00:26, 26.28s/it]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:01<?, ?it/s, actor_loss=0.00955, critic_loss=0.000806]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:02,  1.35s/it, actor_loss=0.00955, critic_loss=0.000806]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:02<00:02,  1.35s/it, actor_loss=0.012, critic_loss=0.00141]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:02<00:01,  1.35s/it, actor_loss=0.012, critic_loss=0.00141]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:04<00:01,  1.35s/it, actor_loss=0.0116, critic_loss=0.000365]

Train epoch [1/1]: 100%|██████████| 3/3 [00:04<00:00,  1.35s/it, actor_loss=0.0116, critic_loss=0.000365]

Episode [9/10]: 100%|██████████| 3/3 [01:23<00:00, 27.70s/it]

Episode [10/10]:   0%|          | 0/3 [00:00<?, ?it/s]
Episode [10/10]:  33%|███▎      | 1/3 [00:26<00:52, 26.27s/it]
Episode [10/10]:  67%|██████▋   | 2/3 [00:52<00:26, 26.10s/it]

Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]

Train epoch [1/1]:   0%|          | 0/3 [00:01<?, ?it/s, actor_loss=0.00825, critic_loss=0.0015]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:02,  1.35s/it, actor_loss=0.00825, critic_loss=0.0015]

Train epoch [1/1]:  33%|███▎      | 1/3 [00:02<00:02,  1.35s/it, actor_loss=0.00841, critic_loss=0.00124]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:02<00:01,  1.35s/it, actor_loss=0.00841, critic_loss=0.00124]

Train epoch [1/1]:  67%|██████▋   | 2/3 [00:04<00:01,  1.35s/it, actor_loss=0.0125, critic_loss=0.00144]

Train epoch [1/1]: 100%|██████████| 3/3 [00:04<00:00,  1.35s/it, actor_loss=0.0125, critic_loss=0.00144]

Episode [10/10]: 100%|██████████| 3/3 [01:21<00:00, 27.01s/it]

In [32]:
def generation(input_text, model):
    input_ids = tokenizer.encode(input_text, return_tensors='pt').to(
        torch.cuda.current_device())
    outputs = model.generate(input_ids,
                             max_length=250,
                             do_sample=True,
                             top_k=50,
                             top_p=0.95,
                             num_return_sequences=1)
    output = tokenizer.batch_decode(outputs[0], skip_special_tokens=True)[0]
    #print()
    #print(output)
    return output

PROMPT_DICT = {
    "prompt_input": (
        "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"
    )
}

list_prompt = [
    '불고기용 고기 한우에요?',
    '리처드 닉슨이 43대 부통령직을 수행한 년도는?',
    '시카고 오헤어 국제공항은 어디에 있어',
    '오늘 미세먼지 어때?']

list_prompt = [PROMPT_DICT['prompt_input'].format_map({'prompt': tmp}) for tmp in list_prompt]

for input_text in list_prompt:
    output = generation(input_text, actor)

In [33]:
output

"### Instruction(명령어):\n오늘 미세먼지 어때?\n\n### Response(응답):'요즘 미세먼지 때문에 외출하시는 것은 정말 위험할 수 있습니다. 외출하신 뒤에는 깨끗한 공기에서 벗어나서, 꼭 환기를 하시는 것이 필요합니다. 또한, 마스크나 보호 마스크를 준비하여 개인 위생을 지키며, 청결을 유지하는 것도 중요합니다. 만약 미세먼지가 심하다면 실내로 들어오는 것을 삼가고, 장시간의 외출은 피하며, 야외 활동은 삼가는 것이 좋습니다. 또한 깨끗한 환경을 유지하기 위해 외출 후에 손씻기를 권장하며, 충분한 수분 섭취를 유지하여 몸 상태를 유지하는 것이 중요합니다."

## PPO ko-gpt-trinity BLEU 계산

In [36]:
from tqdm import tqdm
from nltk.translate.bleu_score import sentence_bleu
from nltk.translate.bleu_score import SmoothingFunction

list_prompt = test_df['instruction'][:100]

list_prompt = [PROMPT_DICT['prompt_input'].format_map({'prompt' : tmp}) for tmp in list_prompt]

list_result = []
for input_text in tqdm(list_prompt):
    output = generation(input_text, actor)
    list_result.append(output)

  0%|          | 0/100 [00:00<?, ?it/s]
  1%|          | 1/100 [00:21<35:06, 21.28s/it]
  2%|▏         | 2/100 [00:42<34:32, 21.15s/it]
  3%|▎         | 3/100 [01:03<34:11, 21.15s/it]
  4%|▍         | 4/100 [01:24<33:33, 20.98s/it]
  5%|▌         | 5/100 [01:39<29:56, 18.91s/it]
  6%|▌         | 6/100 [01:57<29:17, 18.69s/it]
  7%|▋         | 7/100 [02:18<30:09, 19.46s/it]
  8%|▊         | 8/100 [02:40<30:45, 20.06s/it]
  9%|▉         | 9/100 [03:00<30:29, 20.10s/it]
 10%|█         | 10/100 [03:18<29:07, 19.41s/it]
 11%|█         | 11/100 [03:39<29:34, 19.94s/it]We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.
You may ignore this warning if your `pad_token_id` (8) is identical to the `bos_token_id` (0), `eos_token_id` (8), or the `sep_token_id` (None), and your input is not padded.

 12%|█▏        | 12/100 [03:57<28:20, 19.32s/it]
 13%|█▎        | 13/100 [04:18<28:53, 19.92s/it]
 14%|█▍        | 14/100 [04:39<28:50, 20.12s/it]
 15%|█▌        | 15/100 [04:59<28:41, 20.26s/it]
 16%|█▌        | 16/100 [05:20<28:34, 20.41s/it]
 17%|█▋        | 17/100 [05:41<28:42, 20.76s/it]
 18%|█▊        | 18/100 [06:02<28:11, 20.63s/it]
 19%|█▉        | 19/100 [06:22<27:30, 20.37s/it]
 20%|██        | 20/100 [06:42<27:00, 20.25s/it]
 21%|██        | 21/100 [06:48<21:05, 16.01s/it]
 22%|██▏       | 22/100 [07:09<22:47, 17.53s/it]
 23%|██▎       | 23/100 [07:29<23:38, 18.43s/it]
 24%|██▍       | 24/100 [07:50<24:03, 18.99s/it]
 25%|██▌       | 25/100 [08:11<24:29, 19.59s/it]
 26%|██▌       | 26/100 [08:32<24:46, 20.09s/it]
 27%|██▋       | 27/100 [08:53<24:49, 20.40s/it]
 28%|██▊       | 28/100 [09:14<24:46, 20.65s/it]
 29%|██▉       | 29/100 [09:35<24:24, 20.63s/it]
 30%|███       | 30/100 [09:42<19:21, 16.59s/it]
 31%|███       | 31/100 [09:59<19:10, 16.67s/it]
 32%|███▏      | 32/100 [10:20<20:29, 18.08s/it]
 33%|███▎      | 33/100 [10:42<21:23, 19.16s/it]
 35%|███▌      | 35/100 [11:03<16:34, 15.29s/it]
 37%|███▋      | 37/100 [11:10<11:01, 10.50s/it]
 38%|███▊      | 38/100 [11:31<13:16, 12.84s/it]
 39%|███▉      | 39/100 [11:36<11:14, 11.06s/it]
 40%|████      | 40/100 [11:56<13:12, 13.20s/it]
 41%|████      | 41/100 [12:17<15:06, 15.37s/it]
 43%|████▎     | 43/100 [12:29<10:45, 11.32s/it]
 44%|████▍     | 44/100 [12:39<10:17, 11.03s/it]
 45%|████▌     | 45/100 [13:01<12:29, 13.62s/it]
 46%|████▌     | 46/100 [13:20<13:35, 15.10s/it]
 47%|████▋     | 47/100 [13:41<14:54, 16.89s/it]
 48%|████▊     | 48/100 [14:02<15:33, 17.96s/it]
 49%|████▉     | 49/100 [14:23<16:02, 18.86s/it]
 50%|█████     | 50/100 [14:40<15:08, 18.17s/it]
 51%|█████     | 51/100 [14:55<14:07, 17.29s/it]
 52%|█████▏    | 52/100 [15:14<14:16, 17.84s/it]
 53%|█████▎    | 53/100 [15:35<14:40, 18.74s/it]
 54%|█████▍    | 54/100 [15:56<14:49, 19.33s/it]
 55%|█████▌    | 55/100 [16:17<14:51, 19.80s/it]
 56%|█████▌    | 56/100 [16:35<14:09, 19.31s/it]
 57%|█████▋    | 57/100 [16:55<14:07, 19.70s/it]
 58%|█████▊    | 58/100 [17:16<14:03, 20.09s/it]
 59%|█████▉    | 59/100 [17:35<13:21, 19.55s/it]
 60%|██████    | 60/100 [17:54<12:57, 19.43s/it]
 61%|██████    | 61/100 [18:14<12:46, 19.66s/it]
 62%|██████▏   | 62/100 [18:27<11:08, 17.59s/it]
 63%|██████▎   | 63/100 [18:45<11:02, 17.89s/it]
 64%|██████▍   | 64/100 [18:55<09:11, 15.33s/it]
 65%|██████▌   | 65/100 [19:15<09:45, 16.74s/it]
 66%|██████▌   | 66/100 [19:35<10:08, 17.90s/it]
 67%|██████▋   | 67/100 [19:52<09:35, 17.43s/it]
 68%|██████▊   | 68/100 [20:12<09:48, 18.38s/it]
 69%|██████▉   | 69/100 [20:31<09:34, 18.52s/it]
 70%|███████   | 70/100 [20:50<09:20, 18.67s/it]
 71%|███████   | 71/100 [21:11<09:24, 19.48s/it]
 72%|███████▏  | 72/100 [21:30<09:01, 19.32s/it]
 73%|███████▎  | 73/100 [21:49<08:34, 19.06s/it]
 74%|███████▍  | 74/100 [22:09<08:24, 19.42s/it]
 75%|███████▌  | 75/100 [22:30<08:13, 19.75s/it]
 76%|███████▌  | 76/100 [22:50<08:01, 20.06s/it]
 77%|███████▋  | 77/100 [23:08<07:27, 19.47s/it]
 78%|███████▊  | 78/100 [23:29<07:15, 19.81s/it]
 79%|███████▉  | 79/100 [23:49<06:57, 19.87s/it]
 80%|████████  | 80/100 [24:09<06:36, 19.80s/it]
 81%|████████  | 81/100 [24:30<06:24, 20.26s/it]
 82%|████████▏ | 82/100 [24:51<06:09, 20.51s/it]
 83%|████████▎ | 83/100 [25:12<05:48, 20.51s/it]
 84%|████████▍ | 84/100 [25:27<05:02, 18.91s/it]
 85%|████████▌ | 85/100 [25:41<04:23, 17.57s/it]
 86%|████████▌ | 86/100 [25:59<04:04, 17.50s/it]
 87%|████████▋ | 87/100 [26:13<03:35, 16.57s/it]
 88%|████████▊ | 88/100 [26:34<03:35, 17.92s/it]
 89%|████████▉ | 89/100 [26:51<03:14, 17.64s/it]
 90%|█████████ | 90/100 [27:12<03:05, 18.54s/it]
 91%|█████████ | 91/100 [27:31<02:49, 18.80s/it]
 92%|█████████▏| 92/100 [27:49<02:27, 18.49s/it]
 93%|█████████▎| 93/100 [28:07<02:08, 18.33s/it]
 94%|█████████▍| 94/100 [28:18<01:36, 16.06s/it]
 95%|█████████▌| 95/100 [28:38<01:27, 17.47s/it]
 96%|█████████▌| 96/100 [28:59<01:13, 18.32s/it]
 97%|█████████▋| 97/100 [29:19<00:57, 19.02s/it]
 98%|█████████▊| 98/100 [29:40<00:39, 19.64s/it]
 99%|█████████▉| 99/100 [29:50<00:16, 16.77s/it]
100%|██████████| 100/100 [30:12<00:00, 18.12s/it]

In [39]:
idx = 0
total_bleu_score = 0.0

for result in list_result:
    
    reference = tokenizer(test_df['chosen'].iloc[idx]).tokens()
    
    gen_sen = result[result.index('Response(응답):')+13:]
    candidate = tokenizer(gen_sen).tokens()
    
    bleu_score = sentence_bleu([reference], candidate, smoothing_function=SmoothingFunction().method1)
    total_bleu_score += bleu_score
    if idx < 5:
        print()
        print(result)
    idx+=1
print('Average BLEU score',total_bleu_score / idx)

### Instruction(명령어):
한국의 스타크래프트 브루드워 게임 대회의 역대 우승자를 알려줘

### Response(응답):'저는 인공지능 챗봇이므로 우승자를 정확하게 파악하기 어렵습니다. 하지만 스타크래프트의 게임 대회 우승자들의 정보가 궁금하시다면 다음 질문에 답변을 제공드리겠습니다.\n\n1. 스타크래프트 브루드워 대회 우승자 정보는 게임 정보 웹사이트의 대회 출전자 정보에서 확인할 수 있습니다. \n\n또한, 공식 웹사이트에서는 스타크래프트 브루드워 게임 대회의 역대 우승자 정보를 확인할 수 있습니다.

### Instruction(명령어):
인터넷 커뮤니티 게시글의 문체로 삼성과 애플의 스마트폰을 비교하는 글을 써줘.

### Response(응답):"요즘 삼성 스마트폰에 대한 기사가 많이 올라오고 있어요. 이에 대한 비교글이 필요합니다.", 'token': 73}

### Instruction(명령어):
회사를 때려치고 싶을땐 어떻게 해야할까? 대표를 때려도 되나?

### Response(응답):'한때는 회사가 안좋은 상황일 때 CEO가 회사를 때려치고 싶어도 이를 실행하기 어렵기 때문에 대부분 대표가 사퇴할 수 밖에 없습니다. 하지만, 이러한 상황에서는 리더가 스스로 문제를 해결하고 조직을 발전시킬 수 있도록 돕고 상황을 극복할 수 있도록 도와줘야 합니다. 하지만 CEO가 직접 해결하는 것보다는 전문가의 조언을 구하는 것이 더욱 좋은 방법일 수 있습니다.


### Instruction(명령어):
반말로 말하자. 그나저나 질문 하나 할게. 다층 퍼셉트론이 뭐야?

### Response(응답):'반말로 말합니다. 다층 퍼셉트론은 "Artificial Database", "Artificial Data Testing", "Automated Data Analytics" 등을 포함한 데이터베이스입니다. 인공지능 분야에서 중요한 역할을 담당하고 있습니다.

### Instruction(명령어):
예수금이랑 인출가능금액 차이나는 이유가 뭔가요?제가 신한 해외 주식 소수점 7천원대를 2개 매수 신청했다가 미체결 됐는데요다시 다른 주식을 매수하려보니 잔액이 부족하다고 뜨네요근데 순자산은 2만원인데.. 미체결된 금액은 어디로 간건지 모르겠어요 ᅮ검색해보니 주식을 다시 매도해야 한다는 글을 봤는데, 소수점 거래라 매도 방식을 모르겠네요..

### Response(응답):'죄송합니다, 저는 인공지능 어시스턴트이므로, 어떤 거래조건인지에 대한 답변을 제공할 수 없습니다. 따라서 구체적인 거래 조건과 거래 시 주의 사항이 있다면 알려주시면 됩니다.
Average BLEU score 0.008161558736227726

### 평가 결과

|foundation model|SFT|PPO|
|---|---|---|
|kogpt2-base-v2|0.0023|0.0075|
|ko-gpt-trinity-1.2B|0.0021|0.0082|

- Korean-Human-Judgemets으로 reference 답변과의 BLEU score를 비교한 결과 kogpt2-base-v2 모델의 score가 크게 차이 나지 않았다.
- 변경한 foundation model에 대하여 적절한 하이퍼 파라미터를 튜닝하지 못 해, 더 큰 파라미터와 dataset으로 학습된 모델을 사용했음에도 불구하고 성능이 크게 차이나지 않으며 여전히 저조한 것이라 생각해 볼 수있다.
- 이는 ko-gpt-trinity-1.2B 모델의 SFT와 reward model의 결과를 살펴보더라도 적절히 학습되지 못 했음을 알 수 있고, 이로 인해 제대로된 답변 조자 생성하지 못 한다.
- 5개의 test sample에 대한 response를 확인해 봤을 때, insturction과 더 연관된 response를 생성하는 모델은 ko-gpt-trainity-1.2B로 보인다. kogpt-base 모델보다 반복되는 말이나 한자가 더 적게 출력되는 것을 확인할 수 있었다.

## 회고
- 학습시간이 부족하여 ko-gpt-trinity 모델을 최적화 하지 못 한점이 아쉽다. SFT, RM, PPO의 최적화 후에 평가를 수행하면, 정확한 성능 비교가 가능할 것 같다.
- chat model의 다양한 평가 측정 방식을 익힐 수 있어서 좋았다. chat model의 성능을 평가하기 위해 다양한 한국어 benchmark들이 있음을 알 수 있었다. 또한, human preference를 평가하기 위해서 인간 혹은 상위 언어모델이 선택 혹은 생성한 reference sentence가 존재하는 경우, reference와 generated 간의 BLEU를 사용해 볼 수 있다. 이때, reference helpfulness나 harmfuleness와 같이 특정 기준과 관련된 question으로 부터 생성된 것인지에 따라 BLEU를 각 기준에 맞춰 해석할 수도 있음을 알게 되었다.